# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [7]:
# your code here
# Read tic-tac-toe.csv into a dataframe.
import pandas as pd

df = pd.read_csv("/content/tic-tac-toe.csv")

In [10]:
# Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [11]:
df.tail()

    TL TM TR ML MM MR BL BM BR  class
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

In [13]:
df.shape

(958, 10)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

In [15]:
df.describe()

         TL   TM   TR   ML   MM   MR   BL   BM   BR class
count   958  958  958  958  958  958  958  958  958   958
unique    3    3    3    3    3    3    3    3    3     2
top       x    x    x    x    x    x    x    x    x  True
freq    418  378  418  378  458  378  418  378  418   626

In [16]:
df.dtypes

TL       object
TM       object
TR       object
ML       object
MM       object
MR       object
BL       object
BM       object
BR       object
class      bool
dtype: object

In [27]:
# Convert the categorical values to numeric in all columns.
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
print(categorical_cols)

Index(['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR'], dtype='object')

In [34]:
dataframe = pd.get_dummies(df, columns=categorical_cols, dtype=int)

In [35]:
dataframe.dtypes

class     bool
TL_b     int64
TL_o     int64
TL_x     int64
TM_b     int64
TM_o     int64
TM_x     int64
TR_b     int64
TR_o     int64
TR_x     int64
ML_b     int64
ML_o     int64
ML_x     int64
MM_b     int64
MM_o     int64
MM_x     int64
MR_b     int64
MR_o     int64
MR_x     int64
BL_b     int64
BL_o     int64
BL_x     int64
BM_b     int64
BM_o     int64
BM_x     int64
BR_b     int64
BR_o     int64
BR_x     int64
dtype: object

In [39]:
# Separate the inputs and output.
X = dataframe.drop('class', axis=1)  # all columns except 'Purchased'
y = dataframe['class']               # only the target column

In [40]:
# Normalize the input data.
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [56]:
# Split the training and test data.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(X_train.shape)

(766, 27)

In [59]:
# your code here
# Create a Sequential model.
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.optimizers import Adam


model = Sequential()

# Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.

# input layer
model.add(Dense(64, activation='relu', input_shape=(27,)))

# hidden layers
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))

#output layer
model.add(Dense(10, activation='softmax'))

model.summary()

# Define the optimizer
my_opt = tf.keras.optimizers.Adam(learning_rate=0.01, epsilon=0.1)

# Compile your model
model.compile(loss='sparse_categorical_crossentropy', optimizer=my_opt, metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_40 (Dense)                │ (None, 64)             │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_41 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_42 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_43 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_44 (Dense)                │ (None, 10)             │           330 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,314 (24.66 KB)

 Trainable params: 6,314 (24.66 KB)

 Non-trainable params: 0 (0.00 B)

In [62]:
# Fit the training data.
model.fit(X_train, y_train, epochs=5, batch_size=32)

Epoch 1/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7390 - loss: 0.5077
Epoch 2/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7623 - loss: 0.4786
Epoch 3/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8321 - loss: 0.4225
Epoch 4/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8225 - loss: 0.3878
Epoch 5/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8695 - loss: 0.3318

In [63]:
# Evaluate your neural network model with the test data.
model.evaluate(X_test, y_test, batch_size=32)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8576 - loss: 0.3395

[0.3364733159542084, 0.859375]

In [65]:
# Save your model as tic-tac-toe.model.
model.save("tic-tac-toe.keras")

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [71]:
# your code here
import numpy as np
from tensorflow.keras.models import load_model
model = load_model("tic-tac-toe.keras")
model.predict(X_test)
classes = model.predict(X_test, batch_size=32)
print(classes)
proba = model.predict(X_test, batch_size=32)  # probabilities
classes = np.argmax(proba, axis=1)
print(proba)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
[[9.6091680e-02 9.0384477e-01 7.7366758e-06 ... 1.2002521e-06
  1.1306945e-05 1.2971071e-05]
 [2.8638402e-02 9.7100765e-01 4.6654455e-05 ... 1.9446412e-05
  6.0344839e-05 6.8169807e-05]
 [2.4064814e-01 7.5772423e-01 2.2222972e-04 ... 8.1110884e-05
  2.6202211e-04 2.7739775e-04]
 ...
 [6.1592307e-02 9.3725044e-01 1.6542939e-04 ... 5.1724699e-05
  1.4936736e-04 2.3425439e-04]
 [1.9213082e-01 8.0566204e-01 3.0477945e-04 ... 1.0916658e-04
  2.9131054e-04 3.9867777e-04]
 [2.4110618e-01 7.5577164e-01 4.3973399e-04 ... 1.3444654e-04
  4.3311287e-04 5.3959968e-04]]
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[9.6091680e-02 9.0384477e-01 7.7366758e-06 ... 1.2002521e-06
  1.1306945e-05 1.2971071e-05]
 [2.8638402e-02 9.7100765e-01 4.6654455e-05 ... 1.9446412e-05
  6.0344839e-05 6.8169807e-05]
 [2.4064814e-01 7.5772423e-01 2.2222972e-04 ... 8.1110884e-05
  2.6202211e-04 2.7739775e-04]
 ...
 [6.1592307e-02 9.3725044e-01 1.6542939e-04 ... 5.1724699e-05
  1.4936736e-04 2.3425439e-04]
 [1.9213082e-01 8.0566204e-01 3.0477945e-04 ... 1.0916658e-04
  2.9131054e-04 3.9867777e-04]
 [2.4110618e-01 7.5577164e-01 4.3973399e-04 ... 1.3444654e-04
  4.3311287e-04 5.3959968e-04]]

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [73]:
# your code here
# Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.

# your code here
# Create a Sequential model.
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.optimizers import Adam


model = Sequential()

# Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.

# input layer
model.add(Dense(64, activation='relu', input_shape=(27,)))

# hidden layers - added 6 layers
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))

#output layer
model.add(Dense(10, activation='softmax'))

model.summary()

# Define the optimizer
my_opt = tf.keras.optimizers.Adam(learning_rate=0.01, epsilon=0.1)

# Compile your model
model.compile(loss='sparse_categorical_crossentropy', optimizer=my_opt, metrics=['accuracy'])

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_53 (Dense)                │ (None, 64)             │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_54 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_55 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_56 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_57 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_58 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_59 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_60 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_61 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_62 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_63 (Dense)                │ (None, 10)             │           330 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,650 (49.41 KB)

 Trainable params: 12,650 (49.41 KB)

 Non-trainable params: 0 (0.00 B)

In [74]:
# Fit the training data.
model.fit(X_train, y_train, epochs=5, batch_size=32)

Epoch 1/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.2979 - loss: 2.2896
Epoch 2/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6692 - loss: 2.1012
Epoch 3/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6762 - loss: 1.7843
Epoch 4/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6667 - loss: 1.3130
Epoch 5/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6497 - loss: 0.8574

In [75]:
# Evaluate your neural network model with the test data.
model.evaluate(X_test, y_test, batch_size=32)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6453 - loss: 0.7100

[0.7057134509086609, 0.6510416865348816]

In [ ]:
# Adjust the learning rate when you compile the model. This means you will create a custom tf.keras.optimizers.Adam instance where you specify the learning rate you want. Then pass the instance to model.compile as the optimizer.
# tf.keras.optimizers.Adam reference.
# Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.

In [76]:
# your code here
# Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.

# your code here
# Create a Sequential model.
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.optimizers import Adam


model = Sequential()

# Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.

# input layer
model.add(Dense(64, activation='relu', input_shape=(27,)))

# hidden layers - removed 6 layers
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))

#output layer
model.add(Dense(10, activation='softmax'))

model.summary()

# Define the optimizer - changed learning_rate from 0.01 to 0.1
my_opt = tf.keras.optimizers.Adam(learning_rate=0.1, epsilon=0.1)

# Compile your model
model.compile(loss='sparse_categorical_crossentropy', optimizer=my_opt, metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_64 (Dense)                │ (None, 64)             │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_65 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_66 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_67 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_68 (Dense)                │ (None, 10)             │           330 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,314 (24.66 KB)

 Trainable params: 6,314 (24.66 KB)

 Non-trainable params: 0 (0.00 B)

In [77]:
# Fit the training data.
model.fit(X_train, y_train, epochs=5, batch_size=32)

Epoch 1/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3622 - loss: 1.9105
Epoch 2/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5324 - loss: 0.7408
Epoch 3/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6820 - loss: 0.5952
Epoch 4/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7641 - loss: 0.4815
Epoch 5/5
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8304 - loss: 0.3623

In [78]:
# Evaluate your neural network model with the test data.
model.evaluate(X_test, y_test, batch_size=32)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9416 - loss: 0.1581

[0.14140494167804718, 0.9583333134651184]

**Which approach(es) did you find helpful to improve your model performance?**

In [79]:
# your answer here
'''
- Changing the epochs from 10 to 5 improved accuracy.
- Increasing the layers did not improve accuracy.
- Increasing the learning rate from 0.01 to 0.1 improved the accuracy significantly.
'''