# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [44]:
# your code here

import pandas as pd
data = pd.read_csv('tic-tac-toe.csv')
ttt = data.copy()
ttt.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [45]:
ttt.dtypes

TL        str
TM        str
TR        str
ML        str
MM        str
MR        str
BL        str
BM        str
BR        str
class    bool
dtype: object

In [46]:
# Encoding
# x/o/b
mapping = {'x':2, 'o':1, 'b':0}

ttt = ttt.replace(mapping)
ttt = ttt.astype(int)
ttt['class']=ttt['class'].astype(int)
ttt.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   2   2   2   2   1   1   2   1   1      1
1   2   2   2   2   1   1   1   2   1      1
2   2   2   2   2   1   1   1   1   2      1
3   2   2   2   2   1   1   1   0   0      1
4   2   2   2   2   1   1   0   1   0      1

In [47]:
X = ttt.drop(columns='class')
y = ttt['class']
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[1. , 1. , 1. , ..., 1. , 0.5, 0.5],
       [1. , 1. , 1. , ..., 0.5, 1. , 0.5],
       [1. , 1. , 1. , ..., 0.5, 0.5, 1. ],
       ...,
       [0.5, 1. , 0.5, ..., 1. , 0.5, 1. ],
       [0.5, 1. , 0.5, ..., 1. , 0.5, 1. ],
       [0.5, 0.5, 1. , ..., 0.5, 1. , 1. ]], shape=(958, 9))

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [48]:
# your code here
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, test_size=0.2,random_state=42)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()

model.add(Dense(16, activation= 'relu', input_shape=(9,) ))
model.add(Dense(8, activation= 'relu'))
model.add(Dense(2, activation= 'softmax'))

/opt/anaconda3/envs/tensorflow/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
from keras.optimizers import Adam
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6514 - loss: 0.6573 - val_accuracy: 0.6719 - val_loss: 0.6483
Epoch 2/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.6658 - loss: 0.6464 - val_accuracy: 0.6667 - val_loss: 0.6391
Epoch 3/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.6684 - loss: 0.6389 - val_accuracy: 0.6510 - val_loss: 0.6312
Epoch 4/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.6710 - loss: 0.6330 - val_accuracy: 0.6615 - val_loss: 0.6239
Epoch 5/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.6710 - loss: 0.6269 - val_accuracy: 0.6615 - val_loss: 0.6187
Epoch 6/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.6749 - loss: 0.6204 - val_accuracy: 0.6667 - val_loss: 0.6133
Epoch 7/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.6854 - loss: 0.6152 - val_accuracy: 0.6719 - val_loss: 0.6091
Epoch 8/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.6906 - loss: 0.6096 - val_accuracy: 0.6719 - val_loss: 0.6048
Epoch 9/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6997 - loss: 0.6053 - val_accuracy: 0.6823 - val_loss: 0.6004
Epoch 10/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6997 - loss: 0.5999 - val_accuracy: 0.6927 - val_loss: 0.5974
Epoch 11/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7050 - loss: 0.5969 - val_accuracy: 0.6927 - val_loss: 0.5932
Epoch 12/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7089 - loss: 0.5919 - val_accuracy: 0.6979 - val_loss: 0.5911
Epoch 13/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7154 - loss: 0.5872 - val_accuracy: 0.6979 - val_loss: 0.5885
Epoch 14/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7115 - loss: 0.5828 - val_accuracy: 0.7083 - val_loss: 0.5845
Epoch 15/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7193 - loss: 0.5783 - val_accuracy: 0.7135 - val_loss: 0.5816
Epoch 16/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7219 - loss: 0.5745 - val_accuracy: 0.7083 - val_loss: 0.5789
Epoch 17/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7245 - loss: 0.5710 - val_accuracy: 0.7396 - val_loss: 0.5751
Epoch 18/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7298 - loss: 0.5650 - val_accuracy: 0.7135 - val_loss: 0.5746
Epoch 19/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.7232 - loss: 0.5610 - val_accuracy: 0.7448 - val_loss: 0.5697
Epoch 20/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7285 - loss: 0.5571 - val_accuracy: 0.7344 - val_loss: 0.5675

In [51]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.5674865245819092
Test accuracy: 0.734375

In [52]:
import tensorflow as tf
model.save('tic-tac-toe.model.keras')
my_model=tf.keras.models.load_model('tic-tac-toe.model.keras')

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [54]:
# your code here
my_model = tf.keras.models.load_model('tic-tac-toe.model.keras')

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Predict class probabilities
y_pred_probs = my_model.predict(X_test)

# Convert probabilities to class predictions
y_pred = y_pred_probs.argmax(axis=1)
y_true = y_test  # original integer labels

# Compute metrics
acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred, average='weighted')
rec = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')

print(f"Accuracy: {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall: {rec:.4f}")
print(f"F1 Score: {f1:.4f}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Accuracy: 0.7344
Precision: 0.7525
Recall: 0.7344
F1 Score: 0.6945

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [58]:
# your code here
my_model = Sequential([
    Dense(32, activation='relu', input_shape=(9,)),
    Dense(16, activation='relu'),
    Dense(8, activation='relu'),
    Dense(2, activation='softmax')])
my_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history = my_model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/100

/opt/anaconda3/envs/tensorflow/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6397 - loss: 0.6492 - val_accuracy: 0.6510 - val_loss: 0.6476
Epoch 2/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6554 - loss: 0.6238 - val_accuracy: 0.6510 - val_loss: 0.6414
Epoch 3/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6580 - loss: 0.6146 - val_accuracy: 0.6562 - val_loss: 0.6340
Epoch 4/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6736 - loss: 0.6042 - val_accuracy: 0.6771 - val_loss: 0.6246
Epoch 5/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.6854 - loss: 0.5935 - val_accuracy: 0.6771 - val_loss: 0.6177
Epoch 6/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.7076 - loss: 0.5860 - val_accuracy: 0.6771 - val_loss: 0.6180
Epoch 7/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7037 - loss: 0.5756 - val_accuracy: 0.6719 - val_loss: 0.6034
Epoch 8/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.7350 - loss: 0.5648 - val_accuracy: 0.6875 - val_loss: 0.6062
Epoch 9/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7363 - loss: 0.5525 - val_accuracy: 0.6875 - val_loss: 0.5892
Epoch 10/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.7428 - loss: 0.5409 - val_accuracy: 0.6927 - val_loss: 0.5812
Epoch 11/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.7663 - loss: 0.5288 - val_accuracy: 0.6979 - val_loss: 0.5742
Epoch 12/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.7663 - loss: 0.5142 - val_accuracy: 0.7135 - val_loss: 0.5679
Epoch 13/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7807 - loss: 0.4990 - val_accuracy: 0.7344 - val_loss: 0.5511
Epoch 14/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.7781 - loss: 0.4878 - val_accuracy: 0.7396 - val_loss: 0.5436
Epoch 15/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7963 - loss: 0.4755 - val_accuracy: 0.7292 - val_loss: 0.5469
Epoch 16/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8055 - loss: 0.4596 - val_accuracy: 0.7188 - val_loss: 0.5526
Epoch 17/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.8081 - loss: 0.4471 - val_accuracy: 0.7448 - val_loss: 0.5206
Epoch 18/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.8172 - loss: 0.4426 - val_accuracy: 0.7552 - val_loss: 0.5123
Epoch 19/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.8238 - loss: 0.4276 - val_accuracy: 0.7552 - val_loss: 0.5059
Epoch 20/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.8264 - loss: 0.4174 - val_accuracy: 0.7500 - val_loss: 0.5174
Epoch 21/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.8303 - loss: 0.4049 - val_accuracy: 0.7448 - val_loss: 0.5052
Epoch 22/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.8316 - loss: 0.4004 - val_accuracy: 0.7448 - val_loss: 0.5061
Epoch 23/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.8316 - loss: 0.3927 - val_accuracy: 0.7708 - val_loss: 0.4823
Epoch 24/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8512 - loss: 0.3758 - val_accuracy: 0.7812 - val_loss: 0.4843
Epoch 25/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.8368 - loss: 0.3756 - val_accuracy: 0.7708 - val_loss: 0.4847
Epoch 26/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.8446 - loss: 0.3637 - val_accuracy: 0.7812 - val_loss: 0.4736
Epoch 27/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8433 - loss: 0.3569 - val_accuracy: 0.7760 - val_loss: 0.4746
Epoch 28/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.8460 - loss: 0.3551 - val_accuracy: 0.7760 - val_loss: 0.4706
Epoch 29/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.8603 - loss: 0.3439 - val_accuracy: 0.7969 - val_loss: 0.4693
Epoch 30/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.8538 - loss: 0.3428 - val_accuracy: 0.7812 - val_loss: 0.4707
Epoch 31/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.8590 - loss: 0.3332 - val_accuracy: 0.7865 - val_loss: 0.4642
Epoch 32/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.8590 - loss: 0.3421 - val_accuracy: 0.7917 - val_loss: 0.4667
Epoch 33/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.8655 - loss: 0.3308 - val_accuracy: 0.7760 - val_loss: 0.4688
Epoch 34/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.8629 - loss: 0.3272 - val_accuracy: 0.7917 - val_loss: 0.4599
Epoch 35/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.8616 - loss: 0.3215 - val_accuracy: 0.7969 - val_loss: 0.4779
Epoch 36/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.8681 - loss: 0.3137 - val_accuracy: 0.7865 - val_loss: 0.4640
Epoch 37/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.8655 - loss: 0.3114 - val_accuracy: 0.7760 - val_loss: 0.4669
Epoch 38/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.8747 - loss: 0.3036 - val_accuracy: 0.7969 - val_loss: 0.4604
Epoch 39/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.8681 - loss: 0.3055 - val_accuracy: 0.7917 - val_loss: 0.4702
Epoch 40/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.8695 - loss: 0.3013 - val_accuracy: 0.7969 - val_loss: 0.4469
Epoch 41/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.8681 - loss: 0.2917 - val_accuracy: 0.7917 - val_loss: 0.4627
Epoch 42/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.8629 - loss: 0.2944 - val_accuracy: 0.7812 - val_loss: 0.4669
Epoch 43/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.8773 - loss: 0.2861 - val_accuracy: 0.8021 - val_loss: 0.4609
Epoch 44/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.8786 - loss: 0.2883 - val_accuracy: 0.8073 - val_loss: 0.4420
Epoch 45/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.8825 - loss: 0.2805 - val_accuracy: 0.7812 - val_loss: 0.4887
Epoch 46/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.8825 - loss: 0.2832 - val_accuracy: 0.8073 - val_loss: 0.4433
Epoch 47/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.8838 - loss: 0.2743 - val_accuracy: 0.7969 - val_loss: 0.4475
Epoch 48/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.8825 - loss: 0.2704 - val_accuracy: 0.8021 - val_loss: 0.4520
Epoch 49/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.8838 - loss: 0.2700 - val_accuracy: 0.8125 - val_loss: 0.4420
Epoch 50/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.8943 - loss: 0.2631 - val_accuracy: 0.7969 - val_loss: 0.4510
Epoch 51/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.8864 - loss: 0.2606 - val_accuracy: 0.8125 - val_loss: 0.4305
Epoch 52/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.8851 - loss: 0.2660 - val_accuracy: 0.8021 - val_loss: 0.4504
Epoch 53/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8969 - loss: 0.2601 - val_accuracy: 0.7917 - val_loss: 0.4563
Epoch 54/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.8916 - loss: 0.2620 - val_accuracy: 0.8229 - val_loss: 0.4344
Epoch 55/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.9008 - loss: 0.2571 - val_accuracy: 0.7969 - val_loss: 0.4580
Epoch 56/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.8943 - loss: 0.2529 - val_accuracy: 0.8177 - val_loss: 0.4360
Epoch 57/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.8969 - loss: 0.2478 - val_accuracy: 0.8073 - val_loss: 0.4427
Epoch 58/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.9008 - loss: 0.2385 - val_accuracy: 0.7969 - val_loss: 0.4477
Epoch 59/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.8995 - loss: 0.2466 - val_accuracy: 0.8229 - val_loss: 0.4290
Epoch 60/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.8982 - loss: 0.2403 - val_accuracy: 0.8333 - val_loss: 0.4347
Epoch 61/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.9034 - loss: 0.2326 - val_accuracy: 0.8177 - val_loss: 0.4280
Epoch 62/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.9099 - loss: 0.2309 - val_accuracy: 0.8073 - val_loss: 0.4312
Epoch 63/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - accuracy: 0.9021 - loss: 0.2250 - val_accuracy: 0.8125 - val_loss: 0.4300
Epoch 64/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9073 - loss: 0.2263 - val_accuracy: 0.8281 - val_loss: 0.4283
Epoch 65/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.8982 - loss: 0.2309 - val_accuracy: 0.8073 - val_loss: 0.4322
Epoch 66/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.9060 - loss: 0.2249 - val_accuracy: 0.7969 - val_loss: 0.4407
Epoch 67/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.9060 - loss: 0.2344 - val_accuracy: 0.8073 - val_loss: 0.4329
Epoch 68/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.9086 - loss: 0.2143 - val_accuracy: 0.8333 - val_loss: 0.4112
Epoch 69/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.9099 - loss: 0.2173 - val_accuracy: 0.8333 - val_loss: 0.4179
Epoch 70/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.9138 - loss: 0.2135 - val_accuracy: 0.7969 - val_loss: 0.4404
Epoch 71/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.9191 - loss: 0.2095 - val_accuracy: 0.8281 - val_loss: 0.4177
Epoch 72/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.9164 - loss: 0.2058 - val_accuracy: 0.8229 - val_loss: 0.4132
Epoch 73/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9164 - loss: 0.2025 - val_accuracy: 0.8125 - val_loss: 0.4340
Epoch 74/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.9151 - loss: 0.1994 - val_accuracy: 0.8229 - val_loss: 0.4057
Epoch 75/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.9243 - loss: 0.2002 - val_accuracy: 0.8125 - val_loss: 0.4376
Epoch 76/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.9178 - loss: 0.2027 - val_accuracy: 0.8281 - val_loss: 0.4256
Epoch 77/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.9178 - loss: 0.1952 - val_accuracy: 0.8229 - val_loss: 0.4151
Epoch 78/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.9230 - loss: 0.1907 - val_accuracy: 0.8229 - val_loss: 0.4305
Epoch 79/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.9217 - loss: 0.1888 - val_accuracy: 0.8125 - val_loss: 0.4310
Epoch 80/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.9178 - loss: 0.1971 - val_accuracy: 0.8229 - val_loss: 0.4197
Epoch 81/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.9243 - loss: 0.1891 - val_accuracy: 0.8125 - val_loss: 0.4177
Epoch 82/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.9191 - loss: 0.2028 - val_accuracy: 0.8229 - val_loss: 0.4177
Epoch 83/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.9256 - loss: 0.1865 - val_accuracy: 0.8229 - val_loss: 0.4271
Epoch 84/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.9269 - loss: 0.1844 - val_accuracy: 0.8229 - val_loss: 0.4102
Epoch 85/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.9230 - loss: 0.1825 - val_accuracy: 0.8333 - val_loss: 0.4126
Epoch 86/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9308 - loss: 0.1741 - val_accuracy: 0.8490 - val_loss: 0.4034
Epoch 87/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9360 - loss: 0.1708 - val_accuracy: 0.8438 - val_loss: 0.3987
Epoch 88/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9373 - loss: 0.1719 - val_accuracy: 0.8125 - val_loss: 0.4424
Epoch 89/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9347 - loss: 0.1732 - val_accuracy: 0.8333 - val_loss: 0.4091
Epoch 90/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9347 - loss: 0.1608 - val_accuracy: 0.8490 - val_loss: 0.4015
Epoch 91/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9321 - loss: 0.1664 - val_accuracy: 0.7969 - val_loss: 0.4283
Epoch 92/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9439 - loss: 0.1559 - val_accuracy: 0.8438 - val_loss: 0.3993
Epoch 93/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9426 - loss: 0.1544 - val_accuracy: 0.8333 - val_loss: 0.4153
Epoch 94/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9373 - loss: 0.1621 - val_accuracy: 0.8281 - val_loss: 0.4193
Epoch 95/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9439 - loss: 0.1541 - val_accuracy: 0.8333 - val_loss: 0.4107
Epoch 96/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9439 - loss: 0.1502 - val_accuracy: 0.8490 - val_loss: 0.4109
Epoch 97/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.9491 - loss: 0.1522 - val_accuracy: 0.8490 - val_loss: 0.4104
Epoch 98/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.9386 - loss: 0.1503 - val_accuracy: 0.8073 - val_loss: 0.4393
Epoch 99/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.9426 - loss: 0.1477 - val_accuracy: 0.8438 - val_loss: 0.3967
Epoch 100/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.9543 - loss: 0.1414 - val_accuracy: 0.8490 - val_loss: 0.4071

In [59]:
# Predict class probabilities
y_pred_probs = my_model.predict(X_test)

# Convert probabilities to class predictions
y_pred = y_pred_probs.argmax(axis=1)
y_true = y_test  # original integer labels

# Compute metrics
acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred, average='weighted')
rec = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')

print(f"Accuracy: {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall: {rec:.4f}")
print(f"F1 Score: {f1:.4f}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Accuracy: 0.8490
Precision: 0.8507
Recall: 0.8490
F1 Score: 0.8437

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here
# Increase epoch, and add layer, change dense.