# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [65]:
# your code here

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("../tic-tac-toe.csv")
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [2]:
df["class"] = df["class"].astype(int)

In [3]:
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o      1
1  x  x  x  x  o  o  o  x  o      1
2  x  x  x  x  o  o  o  o  x      1
3  x  x  x  x  o  o  o  b  b      1
4  x  x  x  x  o  o  b  o  b      1

In [13]:
df.shape

(958, 10)

In [4]:
cols = ["TL","TM","TR","ML","MM","MR","BL","BM","BR"]
df[cols] = df[cols].replace({"x": 1, "o": 0, "b": 2})
df.head()

/tmp/ipython-input-3755670005.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[cols] = df[cols].replace({"x": 1, "o": 0, "b": 2})

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1   0   0   1   0   0      1
1   1   1   1   1   0   0   0   1   0      1
2   1   1   1   1   0   0   0   0   1      1
3   1   1   1   1   0   0   0   2   2      1
4   1   1   1   1   0   0   2   0   2      1

In [5]:
X = df.drop(columns = ["class"])
y = df["class"]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() # Is for normalization
# scaler = StandardScaler() is for standardization
X_scaled = scaler.fit_transform(X)

# We always normalize in deep learning, as it allows for quicker and more stable computations. Thats different from machine learning, where you cant to align ranges.

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [48]:
import tensorflow.keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input, Flatten
from tensorflow.keras.optimizers import RMSprop
from keras.optimizers import Adam

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.2, random_state = 42)

In [34]:
# Build the model

model = Sequential()
model.add(Dense(64, activation="relu", input_shape=(9,)))
model.add(Flatten())
model.add(Dense(16, activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(32, activation="relu"))
model.add(Dropout(0.2))

In [35]:
model.add(Dense(3, activation = "softmax"))

model.summary()
model.compile(optimizer="adam",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_19 (Dense)                │ (None, 64)             │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_8 (Flatten)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_12 (Dropout)            │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 32)             │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_13 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,323 (9.07 KB)

 Trainable params: 2,323 (9.07 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
# Train the model

batch_size = 64
epochs = 20

history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, y_test))

Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9956 - loss: 0.0206 - val_accuracy: 0.9219 - val_loss: 0.2913
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9952 - loss: 0.0209 - val_accuracy: 0.9167 - val_loss: 0.3179
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9922 - loss: 0.0193 - val_accuracy: 0.9219 - val_loss: 0.3032
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9798 - loss: 0.0355 - val_accuracy: 0.9115 - val_loss: 0.2911
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9982 - loss: 0.0187 - val_accuracy: 0.9427 - val_loss: 0.2600
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9977 - loss: 0.0167 - val_accuracy: 0.9271 - val_loss: 0.2864
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9901 - loss: 0.0210 - val_accuracy: 0.9323 - val_loss: 0.3061
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9945 - loss: 0.0185 - val_accuracy: 0.9219 - val_loss: 0.3055
Epoch 9/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9968 - loss: 0.0184 - val_accuracy: 0.9115 - val_loss: 0.3542
Epoch 10/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9878 - loss: 0.0271 - val_accuracy: 0.9115 - val_loss: 0.3166
Epoch 11/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9884 - loss: 0.0293 - val_accuracy: 0.9375 - val_loss: 0.2879
Epoch 12/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9935 - loss: 0.0215 - val_accuracy: 0.9427 - val_loss: 0.2871
Epoch 13/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9972 - loss: 0.0121 - val_accuracy: 0.9219 - val_loss: 0.3221
Epoch 14/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9970 - loss: 0.0138 - val_accuracy: 0.9323 - val_loss: 0.2989
Epoch 15/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9947 - loss: 0.0203 - val_accuracy: 0.9271 - val_loss: 0.3114
Epoch 16/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9899 - loss: 0.0201 - val_accuracy: 0.9323 - val_loss: 0.2948
Epoch 17/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9865 - loss: 0.0260 - val_accuracy: 0.9271 - val_loss: 0.3094
Epoch 18/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9974 - loss: 0.0145 - val_accuracy: 0.9219 - val_loss: 0.3354
Epoch 19/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9951 - loss: 0.0163 - val_accuracy: 0.9271 - val_loss: 0.3170
Epoch 20/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9972 - loss: 0.0161 - val_accuracy: 0.9323 - val_loss: 0.3159

In [41]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.3158528804779053
Test accuracy: 0.9322916865348816

In [53]:
model.save("tic-tac-toe.model.keras")

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [54]:
from tensorflow.keras.models import load_model

my_model = load_model("tic-tac-toe.model.keras")

In [56]:
predictions = my_model.predict(X_test)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

In [57]:
predictions[0]

array([9.9912620e-01, 8.3891844e-04, 3.4774705e-05], dtype=float32)

In [61]:
import numpy as np

print(np.argmax(predictions[2]))

1

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [11]:
# I already have 5 layers, so I wont add more layers to the model

In [70]:
# Adjust learning rate

optimizer= Adam(learning_rate=0.005)

model.compile(optimizer = optimizer,
              loss = "sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [71]:
history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, y_test))

Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.9810 - loss: 0.0671 - val_accuracy: 0.9219 - val_loss: 0.3121
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9822 - loss: 0.0630 - val_accuracy: 0.9062 - val_loss: 0.2725
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9895 - loss: 0.0365 - val_accuracy: 0.9323 - val_loss: 0.3029
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9962 - loss: 0.0183 - val_accuracy: 0.9375 - val_loss: 0.3387
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9922 - loss: 0.0291 - val_accuracy: 0.9323 - val_loss: 0.2933
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9916 - loss: 0.0300 - val_accuracy: 0.9271 - val_loss: 0.3064
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9849 - loss: 0.0367 - val_accuracy: 0.9219 - val_loss: 0.3275
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9911 - loss: 0.0338 - val_accuracy: 0.9323 - val_loss: 0.3386
Epoch 9/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9729 - loss: 0.0653 - val_accuracy: 0.9062 - val_loss: 0.3113
Epoch 10/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9818 - loss: 0.0369 - val_accuracy: 0.9427 - val_loss: 0.2841
Epoch 11/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9875 - loss: 0.0288 - val_accuracy: 0.9271 - val_loss: 0.3467
Epoch 12/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9832 - loss: 0.0449 - val_accuracy: 0.9062 - val_loss: 0.3775
Epoch 13/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9830 - loss: 0.0394 - val_accuracy: 0.9219 - val_loss: 0.2813
Epoch 14/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9588 - loss: 0.0743 - val_accuracy: 0.9062 - val_loss: 0.4686
Epoch 15/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9837 - loss: 0.0396 - val_accuracy: 0.8906 - val_loss: 0.4138
Epoch 16/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9830 - loss: 0.0422 - val_accuracy: 0.9167 - val_loss: 0.3522
Epoch 17/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9934 - loss: 0.0244 - val_accuracy: 0.9062 - val_loss: 0.4050
Epoch 18/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9920 - loss: 0.0219 - val_accuracy: 0.9375 - val_loss: 0.3288
Epoch 19/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9908 - loss: 0.0253 - val_accuracy: 0.9167 - val_loss: 0.4412
Epoch 20/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9841 - loss: 0.0384 - val_accuracy: 0.9167 - val_loss: 0.3442

In [73]:
# Adjust the number of epochs

history = model.fit(X_train, y_train,
                    batch_size=64,
                    epochs=50,
                    verbose=1,
                    validation_data=(X_test, y_test))

Epoch 1/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9962 - loss: 0.0102 - val_accuracy: 0.9375 - val_loss: 0.2871
Epoch 2/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9945 - loss: 0.0080 - val_accuracy: 0.9531 - val_loss: 0.3083
Epoch 3/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9978 - loss: 0.0044 - val_accuracy: 0.9635 - val_loss: 0.2659
Epoch 4/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9978 - loss: 0.0050 - val_accuracy: 0.9531 - val_loss: 0.2607
Epoch 5/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9967 - loss: 0.0058 - val_accuracy: 0.9583 - val_loss: 0.2771
Epoch 6/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0047 - val_accuracy: 0.9583 - val_loss: 0.2954
Epoch 7/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.9583 - val_loss: 0.2965
Epoch 8/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9997 - loss: 0.0027 - val_accuracy: 0.9583 - val_loss: 0.2924
Epoch 9/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9932 - loss: 0.0082 - val_accuracy: 0.9531 - val_loss: 0.2864
Epoch 10/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9989 - loss: 0.0046 - val_accuracy: 0.9375 - val_loss: 0.2853
Epoch 11/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9962 - loss: 0.0119 - val_accuracy: 0.9583 - val_loss: 0.2874
Epoch 12/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9583 - val_loss: 0.2989
Epoch 13/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.9583 - val_loss: 0.3034
Epoch 14/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9996 - loss: 0.0018 - val_accuracy: 0.9531 - val_loss: 0.3220
Epoch 15/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9978 - loss: 0.0053 - val_accuracy: 0.9583 - val_loss: 0.3487
Epoch 16/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9963 - loss: 0.0053 - val_accuracy: 0.9583 - val_loss: 0.3355
Epoch 17/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9962 - loss: 0.0081 - val_accuracy: 0.9427 - val_loss: 0.3231
Epoch 18/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9959 - loss: 0.0121 - val_accuracy: 0.9479 - val_loss: 0.3548
Epoch 19/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9427 - val_loss: 0.3541
Epoch 20/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9427 - val_loss: 0.3513
Epoch 21/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 6.0033e-04 - val_accuracy: 0.9427 - val_loss: 0.3530
Epoch 22/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9987 - loss: 0.0047 - val_accuracy: 0.9427 - val_loss: 0.3442
Epoch 23/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9987 - loss: 0.0030 - val_accuracy: 0.9427 - val_loss: 0.3548
Epoch 24/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9479 - val_loss: 0.3602
Epoch 25/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.9427 - val_loss: 0.3482
Epoch 26/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9980 - loss: 0.0049 - val_accuracy: 0.9375 - val_loss: 0.3593
Epoch 27/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9962 - loss: 0.0249 - val_accuracy: 0.9531 - val_loss: 0.3374
Epoch 28/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9959 - loss: 0.0047 - val_accuracy: 0.9375 - val_loss: 0.3731
Epoch 29/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.9375 - val_loss: 0.3709
Epoch 30/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9996 - loss: 0.0031 - val_accuracy: 0.9531 - val_loss: 0.3776
Epoch 31/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.9479 - val_loss: 0.3645
Epoch 32/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9998 - loss: 0.0048 - val_accuracy: 0.9583 - val_loss: 0.3971
Epoch 33/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9982 - loss: 0.0036 - val_accuracy: 0.9427 - val_loss: 0.3614
Epoch 34/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9963 - loss: 0.0192 - val_accuracy: 0.9531 - val_loss: 0.3819
Epoch 35/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9961 - loss: 0.0190 - val_accuracy: 0.9427 - val_loss: 0.4248
Epoch 36/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9917 - loss: 0.0151 - val_accuracy: 0.9427 - val_loss: 0.3621
Epoch 37/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9959 - loss: 0.0148 - val_accuracy: 0.9375 - val_loss: 0.3385
Epoch 38/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9885 - loss: 0.0294 - val_accuracy: 0.9375 - val_loss: 0.3550
Epoch 39/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9979 - loss: 0.0118 - val_accuracy: 0.9479 - val_loss: 0.3135
Epoch 40/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9948 - loss: 0.0102 - val_accuracy: 0.9531 - val_loss: 0.3383
Epoch 41/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9989 - loss: 0.0051 - val_accuracy: 0.9479 - val_loss: 0.3656
Epoch 42/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9927 - loss: 0.0104 - val_accuracy: 0.9479 - val_loss: 0.3768
Epoch 43/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9932 - loss: 0.0088 - val_accuracy: 0.9479 - val_loss: 0.3365
Epoch 44/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9946 - loss: 0.0130 - val_accuracy: 0.9583 - val_loss: 0.3329
Epoch 45/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9916 - loss: 0.0251 - val_accuracy: 0.9479 - val_loss: 0.2963
Epoch 46/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9901 - loss: 0.0519 - val_accuracy: 0.9271 - val_loss: 0.3209
Epoch 47/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9766 - loss: 0.0793 - val_accuracy: 0.9427 - val_loss: 0.2305
Epoch 48/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9955 - loss: 0.0187 - val_accuracy: 0.9479 - val_loss: 0.2758
Epoch 49/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9921 - loss: 0.0159 - val_accuracy: 0.9531 - val_loss: 0.2763
Epoch 50/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9987 - loss: 0.0097 - val_accuracy: 0.9583 - val_loss: 0.3034

**Which approach(es) did you find helpful to improve your model performance?**

In [12]:
# All three approaches worked well and it is about finding a balance between all three. The biggest effect in this example was the adjustment of the learning rate.
# The adjustment in the learning rate led to an immediate jump of the accuracy metric in the first epoch. With the defaul learning rate of 0.0001 I needed 80+ epochs to get close
# to the same accuracy. Given that we want to save computational resources in deep learning, while remaining high accuracy, adjust the learning rate seems to have the biggest impact
# for this example.