# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [3]:
import pandas as pd

filename = "tic-tac-toe.csv"

df = pd.read_csv(filename)

In [4]:
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [ ]:
# Method_1: replacing 
# x: 1
# o: 0
# b: -1

# True: 1
# False: 0

cleaned_df = df.copy()
cleaned_df["class"] = df["class"].astype("int")

replacements = {"x":1,
                "o": 0,
                "b": -1}

cleaned_df = cleaned_df.replace(replacements)

y = cleaned_df["class"]

X = cleaned_df.drop("class", axis=1).astype(float)

X

In [ ]:
# Version 2 of the dataset: one hot encoding
df.head()

one_hot_encoding = pd.get_dummies(df, drop_first=True)
one_hot_encoding = one_hot_encoding.astype(float)

y_2 = one_hot_encoding["class"]

X_2 = one_hot_encoding.drop("class", axis=1).astype(float)

X_2

,TL_o,TL_x,TM_o,TM_x,TR_o,TR_x,ML_o,ML_x,MM_o,MM_x,MR_o,MR_x,BL_o,BL_x,BM_o,BM_x,BR_o,BR_x
0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
1,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
3,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
954,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
955,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
956,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
957,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [15]:
# split dataset
from sklearn.model_selection import train_test_split

seed = 13
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=seed)

X_train.shape

(766, 9)

In [69]:
# Normalize
from keras.utils import normalize

X_train = normalize(X_train, axis=1) #The axis=1 argument means the normalization is performed along the second axis (which represents the pixel values within each image).
X_test = normalize(X_test, axis=1)

print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

766 train samples
192 test samples

In [70]:
X_train[1,:]

<tf.Tensor: shape=(9,), dtype=float64, numpy=
array([ 0.        ,  0.        ,  0.40824829,  0.40824829,  0.40824829,
       -0.40824829,  0.40824829, -0.40824829,  0.        ])>

In [71]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Input, Flatten

model = Sequential()
model.add(Input(shape=(9,)))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(2, activation='softmax'))

model.summary()

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_46 (Dense)                │ (None, 32)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_32 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_47 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_33 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_48 (Dense)                │ (None, 2)              │            66 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,442 (5.63 KB)

 Trainable params: 1,442 (5.63 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# split dataset 2
from sklearn.model_selection import train_test_split

seed = 13
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_2,y_2, test_size=0.2, random_state=seed)

X_train_2.shape

(766, 18)

In [ ]:
# Normalize dataset 2
from keras.utils import normalize

X_train_2 = normalize(X_train_2, axis=1) #The axis=1 argument means the normalization is performed along the second axis (which represents the pixel values within each image).
X_test_2 = normalize(X_test_2, axis=1)

print(X_train_2.shape[0], 'train samples')
print(X_test_2.shape[0], 'test samples')

766 train samples
192 test samples

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Input, Flatten

model_2 = Sequential()
model_2.add(Input(shape=(18,)))
model_2.add(Dense(32, activation='relu'))
model_2.add(Dropout(0.2))
model_2.add(Dense(32, activation='relu'))
model_2.add(Dropout(0.2))
model_2.add(Dense(2, activation='softmax'))

model_2.summary()

model_2.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_43 (Dense)                │ (None, 32)             │           608 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_30 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_44 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_31 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_45 (Dense)                │ (None, 2)              │            66 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,730 (6.76 KB)

 Trainable params: 1,730 (6.76 KB)

 Non-trainable params: 0 (0.00 B)

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [72]:
batch_size = 32
epochs = 50


history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, y_test))

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - accuracy: 0.6149 - loss: 0.6531 - val_accuracy: 0.6354 - val_loss: 0.6379
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6684 - loss: 0.6289 - val_accuracy: 0.6667 - val_loss: 0.6451
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6697 - loss: 0.6193 - val_accuracy: 0.6510 - val_loss: 0.6540
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6762 - loss: 0.6192 - val_accuracy: 0.6771 - val_loss: 0.6471
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6789 - loss: 0.6268 - val_accuracy: 0.6875 - val_loss: 0.6450
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6802 - loss: 0.6251 - val_accuracy: 0.6615 - val_loss: 0.6470
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6775 - loss: 0.6246 - val_accuracy: 0.6719 - val_loss: 0.6469
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6723 - loss: 0.6180 - val_accuracy: 0.6667 - val_loss: 0.6465
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6880 - loss: 0.6198 - val_accuracy: 0.6719 - val_loss: 0.6495
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6684 - loss: 0.6252 - val_accuracy: 0.6823 - val_loss: 0.6472
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6775 - loss: 0.6231 - val_accuracy: 0.6667 - val_loss: 0.6494
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6841 - loss: 0.6192 - val_accuracy: 0.6667 - val_loss: 0.6506
Epoch 13/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.6762 - loss: 0.6308 - val_accuracy: 0.6615 - val_loss: 0.6501
Epoch 14/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6749 - loss: 0.6151 - val_accuracy: 0.6562 - val_loss: 0.6524
Epoch 15/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6671 - loss: 0.6287 - val_accuracy: 0.6615 - val_loss: 0.6507
Epoch 16/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6723 - loss: 0.6235 - val_accuracy: 0.6667 - val_loss: 0.6503
Epoch 17/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6815 - loss: 0.6159 - val_accuracy: 0.6510 - val_loss: 0.6556
Epoch 18/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6671 - loss: 0.6283 - val_accuracy: 0.6510 - val_loss: 0.6525
Epoch 19/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6632 - loss: 0.6218 - val_accuracy: 0.6562 - val_loss: 0.6516
Epoch 20/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6802 - loss: 0.6345 - val_accuracy: 0.6510 - val_loss: 0.6517
Epoch 21/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6828 - loss: 0.6275 - val_accuracy: 0.6667 - val_loss: 0.6491
Epoch 22/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6723 - loss: 0.6310 - val_accuracy: 0.6667 - val_loss: 0.6514
Epoch 23/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6749 - loss: 0.6223 - val_accuracy: 0.6562 - val_loss: 0.6539
Epoch 24/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6658 - loss: 0.6406 - val_accuracy: 0.6615 - val_loss: 0.6548
Epoch 25/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6619 - loss: 0.6416 - val_accuracy: 0.6510 - val_loss: 0.6523
Epoch 26/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6619 - loss: 0.6248 - val_accuracy: 0.6615 - val_loss: 0.6486
Epoch 27/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6749 - loss: 0.6417 - val_accuracy: 0.6510 - val_loss: 0.6560
Epoch 28/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6593 - loss: 0.6328 - val_accuracy: 0.6510 - val_loss: 0.6544
Epoch 29/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6697 - loss: 0.6429 - val_accuracy: 0.6615 - val_loss: 0.6537
Epoch 30/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6671 - loss: 0.6286 - val_accuracy: 0.6458 - val_loss: 0.6520
Epoch 31/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6580 - loss: 0.6425 - val_accuracy: 0.6510 - val_loss: 0.6529
Epoch 32/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6488 - loss: 0.6478 - val_accuracy: 0.6562 - val_loss: 0.6519
Epoch 33/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6606 - loss: 0.6423 - val_accuracy: 0.6354 - val_loss: 0.6521
Epoch 34/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6645 - loss: 0.6429 - val_accuracy: 0.6562 - val_loss: 0.6496
Epoch 35/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6619 - loss: 0.6339 - val_accuracy: 0.6510 - val_loss: 0.6469
Epoch 36/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6893 - loss: 0.6311 - val_accuracy: 0.6562 - val_loss: 0.6487
Epoch 37/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6658 - loss: 0.6334 - val_accuracy: 0.6510 - val_loss: 0.6516
Epoch 38/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6632 - loss: 0.6486 - val_accuracy: 0.6562 - val_loss: 0.6540
Epoch 39/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6919 - loss: 0.6323 - val_accuracy: 0.6458 - val_loss: 0.6481
Epoch 40/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6828 - loss: 0.6271 - val_accuracy: 0.6562 - val_loss: 0.6476
Epoch 41/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6671 - loss: 0.6493 - val_accuracy: 0.6354 - val_loss: 0.6521
Epoch 42/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6527 - loss: 0.6525 - val_accuracy: 0.6458 - val_loss: 0.6510
Epoch 43/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6593 - loss: 0.6263 - val_accuracy: 0.6458 - val_loss: 0.6509
Epoch 44/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6632 - loss: 0.6443 - val_accuracy: 0.6562 - val_loss: 0.6486
Epoch 45/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6554 - loss: 0.6275 - val_accuracy: 0.6562 - val_loss: 0.6488
Epoch 46/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6397 - loss: 0.6668 - val_accuracy: 0.6510 - val_loss: 0.6478
Epoch 47/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6762 - loss: 0.6302 - val_accuracy: 0.6458 - val_loss: 0.6495
Epoch 48/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6789 - loss: 0.6159 - val_accuracy: 0.6406 - val_loss: 0.6504
Epoch 49/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6593 - loss: 0.6434 - val_accuracy: 0.6406 - val_loss: 0.6537
Epoch 50/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6671 - loss: 0.6445 - val_accuracy: 0.6615 - val_loss: 0.6476

In [73]:
score = model.evaluate(X_test, y_test)

print('Test loss:', score[0])
print('Test accuracy:', score[1])

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6615 - loss: 0.6476
Test loss: 0.6475614905357361
Test accuracy: 0.6614583134651184

In [66]:
batch_size = 32
epochs = 50


history_2 = model_2.fit(X_train_2, y_train_2,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test_2, y_test_2))

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9687 - loss: 0.1052 - val_accuracy: 0.9896 - val_loss: 0.0469
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9765 - loss: 0.0915 - val_accuracy: 0.9896 - val_loss: 0.0478
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9739 - loss: 0.0815 - val_accuracy: 0.9896 - val_loss: 0.0465
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9700 - loss: 0.1163 - val_accuracy: 0.9896 - val_loss: 0.0457
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9752 - loss: 0.0917 - val_accuracy: 0.9896 - val_loss: 0.0475
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9726 - loss: 0.0947 - val_accuracy: 0.9896 - val_loss: 0.0501
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9752 - loss: 0.0862 - val_accuracy: 0.9896 - val_loss: 0.0479
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9752 - loss: 0.0805 - val_accuracy: 0.9896 - val_loss: 0.0486
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9739 - loss: 0.0765 - val_accuracy: 0.9896 - val_loss: 0.0480
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9765 - loss: 0.0866 - val_accuracy: 0.9896 - val_loss: 0.0472
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9752 - loss: 0.0803 - val_accuracy: 0.9896 - val_loss: 0.0482
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9739 - loss: 0.1017 - val_accuracy: 0.9896 - val_loss: 0.0500
Epoch 13/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9713 - loss: 0.1111 - val_accuracy: 0.9896 - val_loss: 0.0506
Epoch 14/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9791 - loss: 0.0883 - val_accuracy: 0.9896 - val_loss: 0.0511
Epoch 15/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9791 - loss: 0.0888 - val_accuracy: 0.9896 - val_loss: 0.0471
Epoch 16/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9713 - loss: 0.1003 - val_accuracy: 0.9896 - val_loss: 0.0472
Epoch 17/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9765 - loss: 0.0913 - val_accuracy: 0.9896 - val_loss: 0.0447
Epoch 18/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9752 - loss: 0.1010 - val_accuracy: 0.9896 - val_loss: 0.0457
Epoch 19/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9739 - loss: 0.0879 - val_accuracy: 0.9896 - val_loss: 0.0476
Epoch 20/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9830 - loss: 0.0791 - val_accuracy: 0.9896 - val_loss: 0.0452
Epoch 21/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9791 - loss: 0.0912 - val_accuracy: 0.9896 - val_loss: 0.0417
Epoch 22/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9700 - loss: 0.0983 - val_accuracy: 0.9896 - val_loss: 0.0492
Epoch 23/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9804 - loss: 0.0918 - val_accuracy: 0.9896 - val_loss: 0.0450
Epoch 24/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9739 - loss: 0.0836 - val_accuracy: 0.9896 - val_loss: 0.0462
Epoch 25/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9752 - loss: 0.0938 - val_accuracy: 0.9896 - val_loss: 0.0457
Epoch 26/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9713 - loss: 0.1044 - val_accuracy: 0.9896 - val_loss: 0.0447
Epoch 27/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9752 - loss: 0.1029 - val_accuracy: 0.9896 - val_loss: 0.0460
Epoch 28/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9726 - loss: 0.0979 - val_accuracy: 0.9896 - val_loss: 0.0417
Epoch 29/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9765 - loss: 0.0922 - val_accuracy: 0.9896 - val_loss: 0.0420
Epoch 30/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9713 - loss: 0.1133 - val_accuracy: 0.9896 - val_loss: 0.0437
Epoch 31/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9739 - loss: 0.0981 - val_accuracy: 0.9896 - val_loss: 0.0437
Epoch 32/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9713 - loss: 0.0798 - val_accuracy: 0.9896 - val_loss: 0.0418
Epoch 33/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9739 - loss: 0.1162 - val_accuracy: 0.9896 - val_loss: 0.0454
Epoch 34/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9713 - loss: 0.1076 - val_accuracy: 0.9896 - val_loss: 0.0501
Epoch 35/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9739 - loss: 0.0809 - val_accuracy: 0.9896 - val_loss: 0.0467
Epoch 36/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9700 - loss: 0.1077 - val_accuracy: 0.9896 - val_loss: 0.0443
Epoch 37/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9661 - loss: 0.0981 - val_accuracy: 0.9896 - val_loss: 0.0395
Epoch 38/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9726 - loss: 0.1067 - val_accuracy: 0.9896 - val_loss: 0.0443
Epoch 39/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9752 - loss: 0.0765 - val_accuracy: 0.9896 - val_loss: 0.0454
Epoch 40/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9713 - loss: 0.0947 - val_accuracy: 0.9896 - val_loss: 0.0429
Epoch 41/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9791 - loss: 0.0704 - val_accuracy: 0.9896 - val_loss: 0.0480
Epoch 42/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9791 - loss: 0.0824 - val_accuracy: 0.9896 - val_loss: 0.0453
Epoch 43/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9648 - loss: 0.1089 - val_accuracy: 0.9896 - val_loss: 0.0438
Epoch 44/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9739 - loss: 0.0880 - val_accuracy: 0.9896 - val_loss: 0.0475
Epoch 45/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9687 - loss: 0.0832 - val_accuracy: 0.9896 - val_loss: 0.0454
Epoch 46/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9804 - loss: 0.0867 - val_accuracy: 0.9896 - val_loss: 0.0429
Epoch 47/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9752 - loss: 0.1080 - val_accuracy: 0.9896 - val_loss: 0.0469
Epoch 48/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9739 - loss: 0.0911 - val_accuracy: 0.9896 - val_loss: 0.0447
Epoch 49/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9752 - loss: 0.0890 - val_accuracy: 0.9896 - val_loss: 0.0446
Epoch 50/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9752 - loss: 0.1115 - val_accuracy: 0.9896 - val_loss: 0.0453

In [68]:
score_2 = model_2.evaluate(X_test_2, y_test_2)

print('Test loss:', score_2[0])
print('Test accuracy:', score_2[1])

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9896 - loss: 0.0453
Test loss: 0.04525713995099068
Test accuracy: 0.9895833134651184

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [74]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Input
from keras.optimizers import Adam

model_3 = Sequential()
model_3.add(Input(shape=(18,)))
model_3.add(Dense(64, activation='relu'))
model_3.add(Dropout(0.1))
model_3.add(Dense(64, activation='relu'))
model_3.add(Dropout(0.1))
model_3.add(Dense(1, activation='sigmoid'))

model_3.summary()

model_3.compile(optimizer=Adam(learning_rate=0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

Model: "sequential_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_49 (Dense)                │ (None, 64)             │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_34 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_50 (Dense)                │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_35 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_51 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,441 (21.25 KB)

 Trainable params: 5,441 (21.25 KB)

 Non-trainable params: 0 (0.00 B)

In [75]:
batch_size = 32
epochs = 50


history_3 = model_3.fit(X_train_2, y_train_2,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test_2, y_test_2))

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - accuracy: 0.6305 - loss: 0.6410 - val_accuracy: 0.6198 - val_loss: 0.6452
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6671 - loss: 0.5963 - val_accuracy: 0.6562 - val_loss: 0.6214
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7050 - loss: 0.5709 - val_accuracy: 0.6927 - val_loss: 0.6011
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7363 - loss: 0.5514 - val_accuracy: 0.7031 - val_loss: 0.5859
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7363 - loss: 0.5306 - val_accuracy: 0.7031 - val_loss: 0.5702
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7533 - loss: 0.5134 - val_accuracy: 0.7188 - val_loss: 0.5643
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7546 - loss: 0.5084 - val_accuracy: 0.7083 - val_loss: 0.5385
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7702 - loss: 0.4869 - val_accuracy: 0.7448 - val_loss: 0.5305
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7885 - loss: 0.4702 - val_accuracy: 0.7292 - val_loss: 0.4976
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7937 - loss: 0.4489 - val_accuracy: 0.7656 - val_loss: 0.4721
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8016 - loss: 0.4231 - val_accuracy: 0.7812 - val_loss: 0.4445
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8446 - loss: 0.3961 - val_accuracy: 0.7917 - val_loss: 0.4287
Epoch 13/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8603 - loss: 0.3646 - val_accuracy: 0.8333 - val_loss: 0.3725
Epoch 14/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8708 - loss: 0.3326 - val_accuracy: 0.8854 - val_loss: 0.3193
Epoch 15/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9008 - loss: 0.3114 - val_accuracy: 0.9115 - val_loss: 0.2790
Epoch 16/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9217 - loss: 0.2623 - val_accuracy: 0.9167 - val_loss: 0.2547
Epoch 17/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9256 - loss: 0.2503 - val_accuracy: 0.9792 - val_loss: 0.2066
Epoch 18/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9465 - loss: 0.2250 - val_accuracy: 0.9844 - val_loss: 0.1747
Epoch 19/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9517 - loss: 0.1964 - val_accuracy: 0.9896 - val_loss: 0.1424
Epoch 20/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9661 - loss: 0.1642 - val_accuracy: 0.9896 - val_loss: 0.1281
Epoch 21/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9713 - loss: 0.1613 - val_accuracy: 0.9896 - val_loss: 0.1082
Epoch 22/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9687 - loss: 0.1520 - val_accuracy: 0.9896 - val_loss: 0.1091
Epoch 23/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9713 - loss: 0.1400 - val_accuracy: 0.9896 - val_loss: 0.0852
Epoch 24/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9687 - loss: 0.1216 - val_accuracy: 0.9896 - val_loss: 0.0820
Epoch 25/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9687 - loss: 0.1297 - val_accuracy: 0.9896 - val_loss: 0.0671
Epoch 26/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9687 - loss: 0.1220 - val_accuracy: 0.9896 - val_loss: 0.0707
Epoch 27/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9700 - loss: 0.1080 - val_accuracy: 0.9896 - val_loss: 0.0640
Epoch 28/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9791 - loss: 0.0938 - val_accuracy: 0.9896 - val_loss: 0.0577
Epoch 29/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9791 - loss: 0.0922 - val_accuracy: 0.9896 - val_loss: 0.0577
Epoch 30/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9791 - loss: 0.0958 - val_accuracy: 0.9896 - val_loss: 0.0575
Epoch 31/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9752 - loss: 0.0995 - val_accuracy: 0.9896 - val_loss: 0.0527
Epoch 32/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9778 - loss: 0.0851 - val_accuracy: 0.9896 - val_loss: 0.0488
Epoch 33/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9726 - loss: 0.1026 - val_accuracy: 0.9896 - val_loss: 0.0491
Epoch 34/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9778 - loss: 0.0951 - val_accuracy: 0.9896 - val_loss: 0.0514
Epoch 35/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9765 - loss: 0.0940 - val_accuracy: 0.9896 - val_loss: 0.0485
Epoch 36/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9791 - loss: 0.0879 - val_accuracy: 0.9896 - val_loss: 0.0496
Epoch 37/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9791 - loss: 0.0818 - val_accuracy: 0.9896 - val_loss: 0.0471
Epoch 38/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9804 - loss: 0.0852 - val_accuracy: 0.9896 - val_loss: 0.0574
Epoch 39/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9765 - loss: 0.0868 - val_accuracy: 0.9896 - val_loss: 0.0449
Epoch 40/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9752 - loss: 0.0811 - val_accuracy: 0.9896 - val_loss: 0.0467
Epoch 41/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9778 - loss: 0.0864 - val_accuracy: 0.9896 - val_loss: 0.0567
Epoch 42/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9765 - loss: 0.0792 - val_accuracy: 0.9896 - val_loss: 0.0441
Epoch 43/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9778 - loss: 0.0892 - val_accuracy: 0.9896 - val_loss: 0.0456
Epoch 44/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9726 - loss: 0.0772 - val_accuracy: 0.9896 - val_loss: 0.0448
Epoch 45/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9804 - loss: 0.0788 - val_accuracy: 0.9896 - val_loss: 0.0460
Epoch 46/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9778 - loss: 0.0738 - val_accuracy: 0.9896 - val_loss: 0.0528
Epoch 47/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9713 - loss: 0.0905 - val_accuracy: 0.9896 - val_loss: 0.0491
Epoch 48/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9778 - loss: 0.0793 - val_accuracy: 0.9896 - val_loss: 0.0416
Epoch 49/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9778 - loss: 0.0742 - val_accuracy: 0.9896 - val_loss: 0.0414
Epoch 50/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9817 - loss: 0.0697 - val_accuracy: 0.9896 - val_loss: 0.0507

In [77]:
score_3 = model_3.evaluate(X_test_2, y_test_2)

print('Test loss:', score_3[0])
print('Test accuracy:', score_3[1])

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9896 - loss: 0.0507
Test loss: 0.05070307478308678
Test accuracy: 0.9895833134651184

**Which approach(es) did you find helpful to improve your model performance?**

The method that drastically changed my results was changing the way I treated the data.
The first method I tried I replaced x,o and b by 0,1, and -1. When I changed to one-hot-encoding
the performance of the model went from 0.7 to 0.97. 

Considering the hyperparameters for this case what helped improve the model:
- Increase the number of neurons. Increasing the layers did not help much for the data v1.
- Increasing the epochs.
- Changing the learning rate.