# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [493]:
#pip install 'tensorflow'

In [494]:
# your code here
import pandas as pd

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

import tensorflow as tf
import joblib


df_tic= pd.read_csv(r'/Users/ricardomontoyasantos/Desktop/DSML/W13D3-lab-neural-networks/your-code/tic-tac-toe.csv')

#### 2. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data

In [496]:
df_tic

    TL TM TR ML MM MR BL BM BR  class
0    x  x  x  x  o  o  x  o  o   True
1    x  x  x  x  o  o  o  x  o   True
2    x  x  x  x  o  o  o  o  x   True
3    x  x  x  x  o  o  o  b  b   True
4    x  x  x  x  o  o  b  o  b   True
..  .. .. .. .. .. .. .. .. ..    ...
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

[958 rows x 10 columns]

In [497]:
df_tic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

Yes, It is realiable

In [499]:
def encode_tic_tac_toe(value):
    if value == 'x':
        return 2.0
    elif value == 'b':
        return 0.0
    elif value == 'o':
        return 1.0
    return value  
    
for column in df_tic.columns:
    if column != 'class':
        df_tic[column] = df_tic[column].apply(encode_tic_tac_toe)

df_tic['class'] = df_tic['class'].astype(int)

In [500]:
df_tic

      TL   TM   TR   ML   MM   MR   BL   BM   BR  class
0    2.0  2.0  2.0  2.0  1.0  1.0  2.0  1.0  1.0      1
1    2.0  2.0  2.0  2.0  1.0  1.0  1.0  2.0  1.0      1
2    2.0  2.0  2.0  2.0  1.0  1.0  1.0  1.0  2.0      1
3    2.0  2.0  2.0  2.0  1.0  1.0  1.0  0.0  0.0      1
4    2.0  2.0  2.0  2.0  1.0  1.0  0.0  1.0  0.0      1
..   ...  ...  ...  ...  ...  ...  ...  ...  ...    ...
953  1.0  2.0  2.0  2.0  1.0  1.0  1.0  2.0  2.0      0
954  1.0  2.0  1.0  2.0  2.0  1.0  2.0  1.0  2.0      0
955  1.0  2.0  1.0  2.0  1.0  2.0  2.0  1.0  2.0      0
956  1.0  2.0  1.0  1.0  2.0  2.0  2.0  1.0  2.0      0
957  1.0  1.0  2.0  2.0  2.0  1.0  1.0  2.0  2.0      0

[958 rows x 10 columns]

In [501]:
# Step 4: Separate inputs and output
X = df_tic.drop(columns=['class'])
y = df_tic['class']

In [502]:
df_tic

      TL   TM   TR   ML   MM   MR   BL   BM   BR  class
0    2.0  2.0  2.0  2.0  1.0  1.0  2.0  1.0  1.0      1
1    2.0  2.0  2.0  2.0  1.0  1.0  1.0  2.0  1.0      1
2    2.0  2.0  2.0  2.0  1.0  1.0  1.0  1.0  2.0      1
3    2.0  2.0  2.0  2.0  1.0  1.0  1.0  0.0  0.0      1
4    2.0  2.0  2.0  2.0  1.0  1.0  0.0  1.0  0.0      1
..   ...  ...  ...  ...  ...  ...  ...  ...  ...    ...
953  1.0  2.0  2.0  2.0  1.0  1.0  1.0  2.0  2.0      0
954  1.0  2.0  1.0  2.0  2.0  1.0  2.0  1.0  2.0      0
955  1.0  2.0  1.0  2.0  1.0  2.0  2.0  1.0  2.0      0
956  1.0  2.0  1.0  1.0  2.0  2.0  2.0  1.0  2.0      0
957  1.0  1.0  2.0  2.0  2.0  1.0  1.0  2.0  2.0      0

[958 rows x 10 columns]

In [503]:
X = X.astype('float32').to_numpy()
X= tf.keras.utils.normalize(X,axis=1)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [505]:
# your code here

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

In [506]:
model = tf.keras.Sequential()
#model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(2, activation='softmax'))

In [507]:
# Compile
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [508]:
# Train
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)

# Evaluate
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {acc:.4f}")

# Save
model.save('Tic-tac-toe_model.keras')

Test Loss: 0.4475
Test Accuracy: 0.7969

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [510]:
Sample_X = X[100:105]

In [511]:
# your code here

new_model = tf.keras.models.load_model('Tic-tac-toe_model.keras')

pred_probs = new_model.predict(Sample_X)
pred_classes = np.argmax(pred_probs, axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step

In [512]:
pred = pd.DataFrame(Sample_X)

In [513]:
pred['class'] = pred_classes

In [514]:
pred

,0,1,2,3,4,5,6,7,8,class
0,0.458831,0.458831,0.229416,0.000000,0.458831,0.000000,0.229416,0.229416,0.458831,1
1,0.458831,0.458831,0.000000,0.458831,0.229416,0.229416,0.458831,0.229416,0.000000,1
2,0.458831,0.458831,0.000000,0.458831,0.229416,0.229416,0.458831,0.000000,0.229416,0
3,0.458831,0.458831,0.000000,0.458831,0.229416,0.000000,0.458831,0.229416,0.229416,1
4,0.458831,0.458831,0.000000,0.458831,0.000000,0.229416,0.458831,0.229416,0.229416,1

In [515]:
df_tic[100:105]

      TL   TM   TR   ML   MM   MR   BL   BM   BR  class
100  2.0  2.0  1.0  0.0  2.0  0.0  1.0  1.0  2.0      1
101  2.0  2.0  0.0  2.0  1.0  1.0  2.0  1.0  0.0      1
102  2.0  2.0  0.0  2.0  1.0  1.0  2.0  0.0  1.0      1
103  2.0  2.0  0.0  2.0  1.0  0.0  2.0  1.0  1.0      1
104  2.0  2.0  0.0  2.0  0.0  1.0  2.0  1.0  1.0      1

the model did not

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [518]:
model = tf.keras.Sequential()
#model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(2, activation='softmax'))

custom_adam = tf.keras.optimizers.Adam(learning_rate=0.005)

model.compile(
    optimizer=custom_adam,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=0)

# Evaluate
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {acc:.4f}")

# Save
model.save('Tic-tac-toe_model_2.keras')

Test Loss: 0.5840
Test Accuracy: 0.8750

In [519]:
model = tf.keras.Sequential()
#model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(2, activation='softmax'))

custom_adam = tf.keras.optimizers.Adam(learning_rate=0.005)

model.compile(
    optimizer=custom_adam,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train
model.fit(X_train, y_train, epochs=350, batch_size=32, verbose=0)

# Evaluate
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {acc:.4f}")

# Save
model.save('Tic-tac-toe_model_3.keras')

Test Loss: 0.9190
Test Accuracy: 0.9010

**Which approach(es) did you find helpful to improve your model performance?**

I find it useful the second one.