# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [59]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.models import load_model
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

## Reading the file

In [40]:
# your code here
df = pd.read_csv("tic-tac-toe.csv")

# Inspecting the dataset by eye.

In [29]:
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [30]:
print(df.isnull().sum())

TL       0
TM       0
TR       0
ML       0
MM       0
MR       0
BL       0
BM       0
BR       0
class    0
dtype: int64

## Convert the categorical values to numeric.

In [46]:
# All of them are categorical
df.replace({'x':1, 'o':-1, 'b':0}, inplace=True)
df['class'] = df['class'].astype(int)
df.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1   0   0   1   0   0      1
1   1   1   1   1   0   0   0   1   0      1
2   1   1   1   1   0   0   0   0   1      1
3   1   1   1   1   0   0   0  -1  -1      1
4   1   1   1   1   0   0  -1   0  -1      1

## Separate the inputs and output. & Normalize the input data.

In [47]:
# Separating :
X = df.drop('class', axis=1)
y = df['class']

# Normalization :
Scalar = StandardScaler()
x_scaled = Scalar.fit_transform(X)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [48]:
# your code here
# Split the training and test data :
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a `Sequential` model :
model = keras.Sequential()

# Adding layers to the model :
model.add(layers.Dense(32, activation='relu', input_shape=(9,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(2, activation='softmax'))

# Compiling the model :
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Training the model :
history = model.fit(X_train, y_train, epochs=25, batch_size=8, validation_data=(X_test, y_test))

Epoch 1/25

C:\Users\azams\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

96/96 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.4631 - loss: 0.7360 - val_accuracy: 0.6562 - val_loss: 0.6277
Epoch 2/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6853 - loss: 0.6130 - val_accuracy: 0.6615 - val_loss: 0.6052
Epoch 3/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6981 - loss: 0.5946 - val_accuracy: 0.7240 - val_loss: 0.5862
Epoch 4/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7215 - loss: 0.5706 - val_accuracy: 0.7292 - val_loss: 0.5704
Epoch 5/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7461 - loss: 0.5529 - val_accuracy: 0.7240 - val_loss: 0.5528
Epoch 6/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7537 - loss: 0.5215 - val_accuracy: 0.7656 - val_loss: 0.5376
Epoch 7/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7944 - loss: 0.4929 - val_accuracy: 0.7448 - val_loss: 0.5207
Epoch 8/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8174 - loss: 0.4527 - val_accuracy: 0.7552 - val_loss: 0.4996
Epoch 9/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8463 - loss: 0.4245 - val_accuracy: 0.7708 - val_loss: 0.4901
Epoch 10/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8380 - loss: 0.4257 - val_accuracy: 0.7604 - val_loss: 0.4731
Epoch 11/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8291 - loss: 0.4068 - val_accuracy: 0.7760 - val_loss: 0.4602
Epoch 12/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8407 - loss: 0.3823 - val_accuracy: 0.7969 - val_loss: 0.4466
Epoch 13/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8514 - loss: 0.3603 - val_accuracy: 0.8125 - val_loss: 0.4305
Epoch 14/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8524 - loss: 0.3641 - val_accuracy: 0.8177 - val_loss: 0.4252
Epoch 15/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8684 - loss: 0.3411 - val_accuracy: 0.8021 - val_loss: 0.4267
Epoch 16/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8635 - loss: 0.3428 - val_accuracy: 0.8125 - val_loss: 0.4137
Epoch 17/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8757 - loss: 0.3184 - val_accuracy: 0.8281 - val_loss: 0.4020
Epoch 18/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8725 - loss: 0.3134 - val_accuracy: 0.8177 - val_loss: 0.3937
Epoch 19/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8858 - loss: 0.3039 - val_accuracy: 0.8177 - val_loss: 0.3950
Epoch 20/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8800 - loss: 0.2929 - val_accuracy: 0.8281 - val_loss: 0.3887
Epoch 21/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8780 - loss: 0.2929 - val_accuracy: 0.8125 - val_loss: 0.3962
Epoch 22/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8963 - loss: 0.2947 - val_accuracy: 0.8333 - val_loss: 0.3831
Epoch 23/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8710 - loss: 0.3086 - val_accuracy: 0.8281 - val_loss: 0.3829
Epoch 24/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9045 - loss: 0.2644 - val_accuracy: 0.8385 - val_loss: 0.3753
Epoch 25/25
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9001 - loss: 0.2523 - val_accuracy: 0.8490 - val_loss: 0.3640

In [49]:
# Evaluation with test data : 
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test accuracy : {test_accuracy}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8515 - loss: 0.3632
Test accuracy : 0.8489583134651184

In [45]:
model.save('tic-tac-toe.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [55]:
# your code here
model = load_model('tic-tac-toe.h5')

random_rows = np.random.choice(len(X_test), 5, replace=False)
X_sample = X_test.iloc[random_rows]
y_sample = y_test.iloc[random_rows]

predictions = model.predict(X_sample)
predicted_labels = np.argmax(predictions, axis=1)

for i in range(len(X_sample)):
    print(f"Actual Class : {y_sample.iloc[i]}, Predicted Class {predicted_labels[i]}")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
Actual Class : 0, Predicted Class 0
Actual Class : 1, Predicted Class 1
Actual Class : 1, Predicted Class 1
Actual Class : 0, Predicted Class 1
Actual Class : 0, Predicted Class 0

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [70]:
# your code here
model = models.Sequential([
    layers.Dense(64, activation='relu', input_shape=(9,)),  # Increased neurons
    layers.Dense(32, activation='relu'),  
    layers.Dense(16, activation='relu'),
    layers.Dense(8, activation='relu'),
    layers.Dense(2, activation='softmax')
])

# Custom learning rate for Adam optimizer
learning_rate = 0.0005
optimizer = optimizers.Adam(learning_rate=learning_rate)

model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

Epoch 1/50

C:\Users\azams\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

39/39 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.6156 - loss: 0.6821 - val_accuracy: 0.6818 - val_loss: 0.6536
Epoch 2/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6500 - val_accuracy: 0.6818 - val_loss: 0.6248
Epoch 3/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6503 - loss: 0.6294 - val_accuracy: 0.6818 - val_loss: 0.6127
Epoch 4/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6665 - loss: 0.5993 - val_accuracy: 0.6818 - val_loss: 0.6050
Epoch 5/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6420 - loss: 0.5968 - val_accuracy: 0.6818 - val_loss: 0.6008
Epoch 6/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6293 - loss: 0.6002 - val_accuracy: 0.6883 - val_loss: 0.5945
Epoch 7/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6436 - loss: 0.5866 - val_accuracy: 0.6948 - val_loss: 0.5892
Epoch 8/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6896 - loss: 0.5559 - val_accuracy: 0.7078 - val_loss: 0.5824
Epoch 9/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7587 - loss: 0.5173 - val_accuracy: 0.7208 - val_loss: 0.5715
Epoch 10/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7619 - loss: 0.5188 - val_accuracy: 0.7338 - val_loss: 0.5573
Epoch 11/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8001 - loss: 0.4821 - val_accuracy: 0.7597 - val_loss: 0.5466
Epoch 12/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7927 - loss: 0.4715 - val_accuracy: 0.7597 - val_loss: 0.5229
Epoch 13/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8390 - loss: 0.4091 - val_accuracy: 0.7857 - val_loss: 0.4927
Epoch 14/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8285 - loss: 0.4155 - val_accuracy: 0.7857 - val_loss: 0.4668
Epoch 15/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.3732 - val_accuracy: 0.8052 - val_loss: 0.4436
Epoch 16/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8524 - loss: 0.3569 - val_accuracy: 0.8312 - val_loss: 0.4188
Epoch 17/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8645 - loss: 0.3538 - val_accuracy: 0.8377 - val_loss: 0.3989
Epoch 18/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9184 - loss: 0.2819 - val_accuracy: 0.8636 - val_loss: 0.3770
Epoch 19/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9052 - loss: 0.3085 - val_accuracy: 0.8312 - val_loss: 0.3699
Epoch 20/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9096 - loss: 0.2561 - val_accuracy: 0.8506 - val_loss: 0.3606
Epoch 21/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9279 - loss: 0.2301 - val_accuracy: 0.8701 - val_loss: 0.3450
Epoch 22/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9293 - loss: 0.2378 - val_accuracy: 0.8571 - val_loss: 0.3308
Epoch 23/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9313 - loss: 0.2313 - val_accuracy: 0.8636 - val_loss: 0.3213
Epoch 24/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9437 - loss: 0.1852 - val_accuracy: 0.8636 - val_loss: 0.3170
Epoch 25/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9457 - loss: 0.1666 - val_accuracy: 0.8701 - val_loss: 0.3185
Epoch 26/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9596 - loss: 0.1798 - val_accuracy: 0.8831 - val_loss: 0.3193
Epoch 27/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9606 - loss: 0.1514 - val_accuracy: 0.8831 - val_loss: 0.3124
Epoch 28/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9580 - loss: 0.1346 - val_accuracy: 0.8896 - val_loss: 0.3130
Epoch 29/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9695 - loss: 0.1285 - val_accuracy: 0.9026 - val_loss: 0.3108
Epoch 30/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.1079 - val_accuracy: 0.8896 - val_loss: 0.3103
Epoch 31/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9797 - loss: 0.1108 - val_accuracy: 0.8896 - val_loss: 0.3108
Epoch 32/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9861 - loss: 0.1124 - val_accuracy: 0.8961 - val_loss: 0.3162
Epoch 33/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9873 - loss: 0.0881 - val_accuracy: 0.8831 - val_loss: 0.3319
Epoch 34/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9860 - loss: 0.0853 - val_accuracy: 0.8831 - val_loss: 0.3092
Epoch 35/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9961 - loss: 0.0559 - val_accuracy: 0.8961 - val_loss: 0.3122
Epoch 36/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9950 - loss: 0.0590 - val_accuracy: 0.8961 - val_loss: 0.3146
Epoch 37/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9961 - loss: 0.0557 - val_accuracy: 0.9026 - val_loss: 0.3475
Epoch 38/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9895 - loss: 0.0599 - val_accuracy: 0.8961 - val_loss: 0.3335
Epoch 39/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9987 - loss: 0.0486 - val_accuracy: 0.8961 - val_loss: 0.3309
Epoch 40/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9957 - loss: 0.0468 - val_accuracy: 0.8961 - val_loss: 0.3289
Epoch 41/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9958 - loss: 0.0399 - val_accuracy: 0.8961 - val_loss: 0.3231
Epoch 42/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9989 - loss: 0.0300 - val_accuracy: 0.8831 - val_loss: 0.3277
Epoch 43/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9997 - loss: 0.0252 - val_accuracy: 0.8961 - val_loss: 0.3297
Epoch 44/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9977 - loss: 0.0273 - val_accuracy: 0.9026 - val_loss: 0.3245
Epoch 45/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9952 - loss: 0.0258 - val_accuracy: 0.8961 - val_loss: 0.3261
Epoch 46/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9985 - loss: 0.0189 - val_accuracy: 0.9026 - val_loss: 0.3247
Epoch 47/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0174 - val_accuracy: 0.8896 - val_loss: 0.3233
Epoch 48/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0168 - val_accuracy: 0.9026 - val_loss: 0.3312
Epoch 49/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0139 - val_accuracy: 0.8961 - val_loss: 0.3442
Epoch 50/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0107 - val_accuracy: 0.9026 - val_loss: 0.3445

In [71]:
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Final Test Accuracy: {test_acc:.4f}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8886 - loss: 0.3455
Final Test Accuracy: 0.8958

In [72]:
# your code here
model = models.Sequential([
    layers.Dense(128, activation='relu', input_shape=(9,)),  # Increased neurons
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),  
    layers.Dense(16, activation='relu'),
    layers.Dense(8, activation='relu'),
    layers.Dense(2, activation='softmax')
])

# Custom learning rate for Adam optimizer
learning_rate = 0.0005
optimizer = optimizers.Adam(learning_rate=learning_rate)

model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

C:\Users\azams\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.6399 - loss: 0.6673 - val_accuracy: 0.6818 - val_loss: 0.6160
Epoch 2/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6298 - loss: 0.6168 - val_accuracy: 0.6818 - val_loss: 0.6027
Epoch 3/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6562 - loss: 0.5823 - val_accuracy: 0.7013 - val_loss: 0.5943
Epoch 4/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6609 - loss: 0.5570 - val_accuracy: 0.7532 - val_loss: 0.5747
Epoch 5/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7732 - loss: 0.5050 - val_accuracy: 0.7532 - val_loss: 0.5300
Epoch 6/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8118 - loss: 0.4708 - val_accuracy: 0.7987 - val_loss: 0.5123
Epoch 7/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8775 - loss: 0.3992 - val_accuracy: 0.8052 - val_loss: 0.4666
Epoch 8/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8873 - loss: 0.3610 - val_accuracy: 0.8182 - val_loss: 0.4486
Epoch 9/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8845 - loss: 0.3359 - val_accuracy: 0.7922 - val_loss: 0.4462
Epoch 10/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.2573 - val_accuracy: 0.8506 - val_loss: 0.3741
Epoch 11/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9291 - loss: 0.2335 - val_accuracy: 0.8247 - val_loss: 0.3836
Epoch 12/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9553 - loss: 0.2011 - val_accuracy: 0.8636 - val_loss: 0.3591
Epoch 13/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9640 - loss: 0.1507 - val_accuracy: 0.8571 - val_loss: 0.3339
Epoch 14/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9617 - loss: 0.1342 - val_accuracy: 0.8506 - val_loss: 0.4310
Epoch 15/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9470 - loss: 0.1627 - val_accuracy: 0.8766 - val_loss: 0.3340
Epoch 16/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9829 - loss: 0.0971 - val_accuracy: 0.8831 - val_loss: 0.3143
Epoch 17/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9823 - loss: 0.0794 - val_accuracy: 0.8766 - val_loss: 0.3115
Epoch 18/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9953 - loss: 0.0568 - val_accuracy: 0.8831 - val_loss: 0.3049
Epoch 19/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9946 - loss: 0.0553 - val_accuracy: 0.9026 - val_loss: 0.3225
Epoch 20/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0380 - val_accuracy: 0.8896 - val_loss: 0.2815
Epoch 21/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0319 - val_accuracy: 0.8961 - val_loss: 0.3287
Epoch 22/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0211 - val_accuracy: 0.8961 - val_loss: 0.3009
Epoch 23/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0196 - val_accuracy: 0.8961 - val_loss: 0.3226
Epoch 24/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0137 - val_accuracy: 0.9026 - val_loss: 0.3169
Epoch 25/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0125 - val_accuracy: 0.9091 - val_loss: 0.3037
Epoch 26/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0094 - val_accuracy: 0.9156 - val_loss: 0.3226
Epoch 27/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0079 - val_accuracy: 0.9026 - val_loss: 0.3471
Epoch 28/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0070 - val_accuracy: 0.9091 - val_loss: 0.3183
Epoch 29/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0068 - val_accuracy: 0.9156 - val_loss: 0.3196
Epoch 30/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0053 - val_accuracy: 0.9156 - val_loss: 0.3430
Epoch 31/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0050 - val_accuracy: 0.9156 - val_loss: 0.3446
Epoch 32/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0042 - val_accuracy: 0.9221 - val_loss: 0.3474
Epoch 33/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0043 - val_accuracy: 0.9156 - val_loss: 0.3487
Epoch 34/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0034 - val_accuracy: 0.9026 - val_loss: 0.3746
Epoch 35/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.9156 - val_loss: 0.3589
Epoch 36/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.9026 - val_loss: 0.3700
Epoch 37/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9221 - val_loss: 0.3542
Epoch 38/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9091 - val_loss: 0.3744
Epoch 39/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9156 - val_loss: 0.3650
Epoch 40/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.9156 - val_loss: 0.3595
Epoch 41/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.9091 - val_loss: 0.3735
Epoch 42/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.9091 - val_loss: 0.3732
Epoch 43/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9091 - val_loss: 0.3788
Epoch 44/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.9091 - val_loss: 0.3881
Epoch 45/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9156 - val_loss: 0.3733
Epoch 46/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.9091 - val_loss: 0.4073
Epoch 47/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9221 - val_loss: 0.3763
Epoch 48/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 9.9151e-04 - val_accuracy: 0.9091 - val_loss: 0.3997
Epoch 49/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9091 - val_loss: 0.3912
Epoch 50/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.9091 - val_loss: 0.3973

In [73]:
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Final Test Accuracy: {test_acc:.4f}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9431 - loss: 0.2172
Final Test Accuracy: 0.9375

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here
"""the first approach was 3 layers with 32 then 16 then 2 nuerons had an accuracy of 84%
then I tried changing learning rate, num of epochs, batch size, and increasing layers to be 5 with 64, 32, 16, 8, 2 and I got an accuracy of 89%
then lastly I tried increasing one more layer for the same parameter of the second test and I got an accuracy of 93%"""