# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
!find /content/drive/MyDrive -name "tic-tac-toe.csv"

/content/drive/MyDrive/tic-tac-toe.csv
/content/drive/MyDrive/lab neural network/tic-tac-toe.csv
^C

In [12]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/tic-tac-toe.csv')
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [13]:
df.shape

(958, 10)

In [14]:
df.info

<bound method DataFrame.info of     TL TM TR ML MM MR BL BM BR  class
0    x  x  x  x  o  o  x  o  o   True
1    x  x  x  x  o  o  o  x  o   True
2    x  x  x  x  o  o  o  o  x   True
3    x  x  x  x  o  o  o  b  b   True
4    x  x  x  x  o  o  b  o  b   True
..  .. .. .. .. .. .. .. .. ..    ...
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

[958 rows x 10 columns]>

In [15]:
df['class'].value_counts()

class
True     626
False    332
Name: count, dtype: int64

In [16]:
df.isnull().sum()

TL       0
TM       0
TR       0
ML       0
MM       0
MR       0
BL       0
BM       0
BR       0
class    0
dtype: int64

In [17]:
df = df.replace({'x':1, 'o':-1, 'b':0})

/tmp/ipykernel_2471/379675694.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({'x':1, 'o':-1, 'b':0})

In [20]:
df.tail()

     TL  TM  TR  ML  MM  MR  BL  BM  BR  class
953  -1   1   1   1  -1  -1  -1   1   1  False
954  -1   1  -1   1   1  -1   1  -1   1  False
955  -1   1  -1   1  -1   1   1  -1   1  False
956  -1   1  -1  -1   1   1   1  -1   1  False
957  -1  -1   1   1   1  -1  -1   1   1  False

In [21]:
df['class'] = df['class'].replace({True:1, False:0})

/tmp/ipykernel_2471/1275187413.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['class'] = df['class'].replace({True:1, False:0})

In [22]:
df.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1  -1  -1   1  -1  -1      1
1   1   1   1   1  -1  -1  -1   1  -1      1
2   1   1   1   1  -1  -1  -1  -1   1      1
3   1   1   1   1  -1  -1  -1   0   0      1
4   1   1   1   1  -1  -1   0  -1   0      1

In [23]:
X = df.drop(['class'], axis = 1)
y = df['class']

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [30]:
print(X_train.shape)
print('\n')
print(X_test.shape)

(766, 9)


(192, 9)

In [31]:
from keras.models import Sequential
from keras.layers import Dense

In [41]:
def classification_model():
    model = Sequential()
    model.add(Dense(8,activation = 'relu', input_shape = (9,)))
    model.add(Dense(8, activation = 'relu'))
    model.add(Dense(2, activation = 'softmax'))
    model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
    return model

In [42]:
model = classification_model()

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [43]:
model.fit(X_train, y_train, epochs = 20, verbose = 2)

Epoch 1/20
24/24 - 1s - 47ms/step - accuracy: 0.5209 - loss: 0.6819
Epoch 2/20
24/24 - 0s - 6ms/step - accuracy: 0.5653 - loss: 0.6501
Epoch 3/20
24/24 - 0s - 6ms/step - accuracy: 0.5940 - loss: 0.6305
Epoch 4/20
24/24 - 0s - 12ms/step - accuracy: 0.6188 - loss: 0.6151
Epoch 5/20
24/24 - 0s - 6ms/step - accuracy: 0.6371 - loss: 0.6011
Epoch 6/20
24/24 - 0s - 6ms/step - accuracy: 0.6632 - loss: 0.5884
Epoch 7/20
24/24 - 0s - 6ms/step - accuracy: 0.6841 - loss: 0.5773
Epoch 8/20
24/24 - 0s - 6ms/step - accuracy: 0.6841 - loss: 0.5667
Epoch 9/20
24/24 - 0s - 13ms/step - accuracy: 0.6906 - loss: 0.5581
Epoch 10/20
24/24 - 0s - 6ms/step - accuracy: 0.7076 - loss: 0.5497
Epoch 11/20
24/24 - 0s - 6ms/step - accuracy: 0.7167 - loss: 0.5403
Epoch 12/20
24/24 - 0s - 6ms/step - accuracy: 0.7219 - loss: 0.5328
Epoch 13/20
24/24 - 0s - 6ms/step - accuracy: 0.7415 - loss: 0.5249
Epoch 14/20
24/24 - 0s - 6ms/step - accuracy: 0.7415 - loss: 0.5165
Epoch 15/20
24/24 - 0s - 6ms/step - accuracy: 0.7389 - loss: 0.5086
Epoch 16/20
24/24 - 0s - 6ms/step - accuracy: 0.7480 - loss: 0.5009
Epoch 17/20
24/24 - 0s - 12ms/step - accuracy: 0.7546 - loss: 0.4925
Epoch 18/20
24/24 - 0s - 13ms/step - accuracy: 0.7650 - loss: 0.4834
Epoch 19/20
24/24 - 0s - 7ms/step - accuracy: 0.7728 - loss: 0.4741
Epoch 20/20
24/24 - 0s - 6ms/step - accuracy: 0.7833 - loss: 0.4639

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [40]:
model.evaluate(X_test, y_test)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7917 - loss: 0.4750

[0.47501519322395325, 0.7916666865348816]

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [44]:
def classification_model():
    model = Sequential()
    model.add(Dense(16,activation = 'relu', input_shape = (9,)))
    model.add(Dense(16, activation = 'relu'))
    model.add(Dense(2, activation = 'softmax'))
    model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
    return model

In [45]:
model = classification_model()

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [46]:
model.fit(X_train, y_train, epochs = 50, verbose = 2)

Epoch 1/50
24/24 - 1s - 41ms/step - accuracy: 0.4896 - loss: 0.6876
Epoch 2/50
24/24 - 0s - 4ms/step - accuracy: 0.6684 - loss: 0.6363
Epoch 3/50
24/24 - 0s - 3ms/step - accuracy: 0.7050 - loss: 0.5988
Epoch 4/50
24/24 - 0s - 3ms/step - accuracy: 0.7389 - loss: 0.5693
Epoch 5/50
24/24 - 0s - 4ms/step - accuracy: 0.7520 - loss: 0.5431
Epoch 6/50
24/24 - 0s - 4ms/step - accuracy: 0.7533 - loss: 0.5240
Epoch 7/50
24/24 - 0s - 4ms/step - accuracy: 0.7637 - loss: 0.5064
Epoch 8/50
24/24 - 0s - 4ms/step - accuracy: 0.7663 - loss: 0.4925
Epoch 9/50
24/24 - 0s - 4ms/step - accuracy: 0.7820 - loss: 0.4770
Epoch 10/50
24/24 - 0s - 4ms/step - accuracy: 0.7846 - loss: 0.4644
Epoch 11/50
24/24 - 0s - 4ms/step - accuracy: 0.7937 - loss: 0.4490
Epoch 12/50
24/24 - 0s - 4ms/step - accuracy: 0.8068 - loss: 0.4350
Epoch 13/50
24/24 - 0s - 4ms/step - accuracy: 0.8133 - loss: 0.4199
Epoch 14/50
24/24 - 0s - 4ms/step - accuracy: 0.8225 - loss: 0.4047
Epoch 15/50
24/24 - 0s - 4ms/step - accuracy: 0.8316 - loss: 0.3877
Epoch 16/50
24/24 - 0s - 4ms/step - accuracy: 0.8512 - loss: 0.3703
Epoch 17/50
24/24 - 0s - 4ms/step - accuracy: 0.8603 - loss: 0.3529
Epoch 18/50
24/24 - 0s - 3ms/step - accuracy: 0.8864 - loss: 0.3320
Epoch 19/50
24/24 - 0s - 4ms/step - accuracy: 0.8982 - loss: 0.3124
Epoch 20/50
24/24 - 0s - 4ms/step - accuracy: 0.9204 - loss: 0.2924
Epoch 21/50
24/24 - 0s - 4ms/step - accuracy: 0.9282 - loss: 0.2707
Epoch 22/50
24/24 - 0s - 4ms/step - accuracy: 0.9439 - loss: 0.2494
Epoch 23/50
24/24 - 0s - 4ms/step - accuracy: 0.9504 - loss: 0.2283
Epoch 24/50
24/24 - 0s - 5ms/step - accuracy: 0.9569 - loss: 0.2080
Epoch 25/50
24/24 - 0s - 4ms/step - accuracy: 0.9674 - loss: 0.1883
Epoch 26/50
24/24 - 0s - 4ms/step - accuracy: 0.9765 - loss: 0.1706
Epoch 27/50
24/24 - 0s - 4ms/step - accuracy: 0.9778 - loss: 0.1535
Epoch 28/50
24/24 - 0s - 4ms/step - accuracy: 0.9804 - loss: 0.1380
Epoch 29/50
24/24 - 0s - 4ms/step - accuracy: 0.9804 - loss: 0.1253
Epoch 30/50
24/24 - 0s - 4ms/step - accuracy: 0.9817 - loss: 0.1123
Epoch 31/50
24/24 - 0s - 4ms/step - accuracy: 0.9830 - loss: 0.1023
Epoch 32/50
24/24 - 0s - 4ms/step - accuracy: 0.9830 - loss: 0.0925
Epoch 33/50
24/24 - 0s - 4ms/step - accuracy: 0.9843 - loss: 0.0846
Epoch 34/50
24/24 - 0s - 4ms/step - accuracy: 0.9843 - loss: 0.0775
Epoch 35/50
24/24 - 0s - 4ms/step - accuracy: 0.9869 - loss: 0.0711
Epoch 36/50
24/24 - 0s - 4ms/step - accuracy: 0.9856 - loss: 0.0655
Epoch 37/50
24/24 - 0s - 4ms/step - accuracy: 0.9883 - loss: 0.0606
Epoch 38/50
24/24 - 0s - 5ms/step - accuracy: 0.9896 - loss: 0.0564
Epoch 39/50
24/24 - 0s - 4ms/step - accuracy: 0.9896 - loss: 0.0531
Epoch 40/50
24/24 - 0s - 4ms/step - accuracy: 0.9896 - loss: 0.0498
Epoch 41/50
24/24 - 0s - 4ms/step - accuracy: 0.9922 - loss: 0.0464
Epoch 42/50
24/24 - 0s - 4ms/step - accuracy: 0.9896 - loss: 0.0435
Epoch 43/50
24/24 - 0s - 4ms/step - accuracy: 0.9935 - loss: 0.0408
Epoch 44/50
24/24 - 0s - 4ms/step - accuracy: 0.9935 - loss: 0.0389
Epoch 45/50
24/24 - 0s - 5ms/step - accuracy: 0.9935 - loss: 0.0361
Epoch 46/50
24/24 - 0s - 7ms/step - accuracy: 0.9935 - loss: 0.0341
Epoch 47/50
24/24 - 0s - 7ms/step - accuracy: 0.9948 - loss: 0.0323
Epoch 48/50
24/24 - 0s - 12ms/step - accuracy: 0.9935 - loss: 0.0307
Epoch 49/50
24/24 - 0s - 6ms/step - accuracy: 0.9935 - loss: 0.0291
Epoch 50/50
24/24 - 0s - 6ms/step - accuracy: 0.9961 - loss: 0.0278

In [47]:
model.evaluate(X_test, y_test)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9948 - loss: 0.0402

[0.040211021900177, 0.9947916865348816]

**Which approach(es) did you find helpful to improve your model performance?**

In [48]:
# I increased number of hidden layers from 8 to 16 and epochs from 20 to 50 and got amazing result couldn't even expect that