# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
import pandas as pd

# 1. Read the data
data = pd.read_csv('tic-tac-toe.csv')

In [2]:
# 2. Inspect the dataset
print(data.shape)
data.head()

data.info()
data['class'].value_counts()

(958, 10)
<class 'pandas.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    str
 1   TM      958 non-null    str
 2   TR      958 non-null    str
 3   ML      958 non-null    str
 4   MM      958 non-null    str
 5   MR      958 non-null    str
 6   BL      958 non-null    str
 7   BM      958 non-null    str
 8   BR      958 non-null    str
 9   class   958 non-null    bool
dtypes: bool(1), str(9)
memory usage: 68.4 KB

class
True     626
False    332
Name: count, dtype: int64

In [3]:
# 3. Convert the categorical values ('x', 'o', 'b' and True/False) to numeric
data_numeric = data.apply(lambda col: pd.factorize(col)[0])
data_numeric.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   0   0   0   0   0   0   0   0   0      0
1   0   0   0   0   0   0   1   1   0      0
2   0   0   0   0   0   0   1   0   1      0
3   0   0   0   0   0   0   1   2   2      0
4   0   0   0   0   0   0   2   0   2      0

In [4]:
# 4. Separate the inputs and output
X = data_numeric.drop('class', axis=1)
y = data_numeric['class']

display(data.head())
display(data_numeric.head())

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   0   0   0   0   0   0   0   0   0      0
1   0   0   0   0   0   0   1   1   0      0
2   0   0   0   0   0   0   1   0   1      0
3   0   0   0   0   0   0   1   2   2      0
4   0   0   0   0   0   0   2   0   2      0

In [5]:
# 5. Normalize the input data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [6]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# 1. Split the training and test data
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# 2 & 3. Create a Sequential model and add layers
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(2, activation='softmax')
])

# 4. Compile the model
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# 5. Fit the training data
history = model.fit(X_train, y_train, epochs=50, validation_split=0.1, verbose=1)

# 6. Evaluate the model with the test data
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test loss: {test_loss:.4f}, Test accuracy: {test_acc:.4f}")

# 7. Save the model
model.save('tic-tac-toe.model.keras')

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1786025992.504760   14628 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1786025992.571240   14628 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1786025993.459070   14628 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1786025994.270676   14628 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5560 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9

Epoch 1/50

I0000 00:00:1786025995.459800   14721 service.cc:153] XLA service 0x78b1e4032990 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1786025995.459832   14721 service.cc:161]   StreamExecutor [0]: NVIDIA GeForce RTX 4060 Laptop GPU, Compute Capability 8.9 (Driver: 13.3.0; Runtime: 12.9.0; Toolkit: 12.5.0; DNN: 9.20.0)
I0000 00:00:1786025995.479934   14721 dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1786025995.582738   14721 cuda_dnn.cc:461] Loaded cuDNN version 92000
I0000 00:00:1786025995.591688   14721 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_1242__.13

15/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6000 - loss: 0.6581

I0000 00:00:1786025997.149055   14721 device_compiler.h:208] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
I0000 00:00:1786025997.338820   14722 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_1242__.13

22/22 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - accuracy: 0.6125 - loss: 0.6448 - val_accuracy: 0.7013 - val_loss: 0.5705
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6792 - loss: 0.5822 - val_accuracy: 0.8052 - val_loss: 0.5504
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7373 - loss: 0.5532 - val_accuracy: 0.7792 - val_loss: 0.5434
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7489 - loss: 0.5345 - val_accuracy: 0.7662 - val_loss: 0.5332
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7591 - loss: 0.5165 - val_accuracy: 0.7662 - val_loss: 0.5333
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7692 - loss: 0.5030 - val_accuracy: 0.7662 - val_loss: 0.5275
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7808 - loss: 0.4903 - val_accuracy: 0.7792 - val_loss: 0.5176
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7896 - loss: 0.4791 - val_accuracy: 0.7792 - val_loss: 0.5162
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7910 - loss: 0.4689 - val_accuracy: 0.7662 - val_loss: 0.5071
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7983 - loss: 0.4533 - val_accuracy: 0.7922 - val_loss: 0.5004
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8142 - loss: 0.4400 - val_accuracy: 0.7922 - val_loss: 0.4933
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8041 - loss: 0.4314 - val_accuracy: 0.7922 - val_loss: 0.4848
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8200 - loss: 0.4169 - val_accuracy: 0.7922 - val_loss: 0.4845
Epoch 14/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8273 - loss: 0.4061 - val_accuracy: 0.8052 - val_loss: 0.4818
Epoch 15/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8360 - loss: 0.3933 - val_accuracy: 0.7792 - val_loss: 0.4806
Epoch 16/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8476 - loss: 0.3825 - val_accuracy: 0.7922 - val_loss: 0.4743
Epoch 17/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8505 - loss: 0.3723 - val_accuracy: 0.7792 - val_loss: 0.4693
Epoch 18/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8520 - loss: 0.3609 - val_accuracy: 0.8052 - val_loss: 0.4577
Epoch 19/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8433 - loss: 0.3551 - val_accuracy: 0.7403 - val_loss: 0.4577
Epoch 20/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8592 - loss: 0.3411 - val_accuracy: 0.7792 - val_loss: 0.4564
Epoch 21/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8549 - loss: 0.3324 - val_accuracy: 0.7662 - val_loss: 0.4520
Epoch 22/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8621 - loss: 0.3209 - val_accuracy: 0.7532 - val_loss: 0.4383
Epoch 23/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8665 - loss: 0.3095 - val_accuracy: 0.7532 - val_loss: 0.4485
Epoch 24/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8766 - loss: 0.3037 - val_accuracy: 0.7662 - val_loss: 0.4382
Epoch 25/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8766 - loss: 0.2943 - val_accuracy: 0.7922 - val_loss: 0.4246
Epoch 26/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8853 - loss: 0.2850 - val_accuracy: 0.8052 - val_loss: 0.4184
Epoch 27/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8911 - loss: 0.2768 - val_accuracy: 0.7662 - val_loss: 0.4482
Epoch 28/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9013 - loss: 0.2638 - val_accuracy: 0.8052 - val_loss: 0.4118
Epoch 29/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2566 - val_accuracy: 0.7922 - val_loss: 0.4158
Epoch 30/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9028 - loss: 0.2486 - val_accuracy: 0.7662 - val_loss: 0.4282
Epoch 31/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9086 - loss: 0.2399 - val_accuracy: 0.7922 - val_loss: 0.4121
Epoch 32/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9086 - loss: 0.2371 - val_accuracy: 0.7922 - val_loss: 0.4079
Epoch 33/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9231 - loss: 0.2266 - val_accuracy: 0.8052 - val_loss: 0.3980
Epoch 34/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9202 - loss: 0.2170 - val_accuracy: 0.7922 - val_loss: 0.4108
Epoch 35/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9318 - loss: 0.2068 - val_accuracy: 0.7922 - val_loss: 0.3972
Epoch 36/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9376 - loss: 0.2003 - val_accuracy: 0.8052 - val_loss: 0.3934
Epoch 37/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9361 - loss: 0.1914 - val_accuracy: 0.8052 - val_loss: 0.3750
Epoch 38/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9419 - loss: 0.1823 - val_accuracy: 0.7662 - val_loss: 0.3961
Epoch 39/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9507 - loss: 0.1727 - val_accuracy: 0.7922 - val_loss: 0.3763
Epoch 40/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9550 - loss: 0.1685 - val_accuracy: 0.8182 - val_loss: 0.3651
Epoch 41/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9492 - loss: 0.1619 - val_accuracy: 0.8442 - val_loss: 0.3511
Epoch 42/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9594 - loss: 0.1517 - val_accuracy: 0.8312 - val_loss: 0.3522
Epoch 43/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9608 - loss: 0.1515 - val_accuracy: 0.8312 - val_loss: 0.3493
Epoch 44/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9637 - loss: 0.1436 - val_accuracy: 0.8182 - val_loss: 0.3547
Epoch 45/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9666 - loss: 0.1352 - val_accuracy: 0.8571 - val_loss: 0.3433
Epoch 46/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9710 - loss: 0.1270 - val_accuracy: 0.8442 - val_loss: 0.3381
Epoch 47/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.1232 - val_accuracy: 0.8571 - val_loss: 0.3335
Epoch 48/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9753 - loss: 0.1170 - val_accuracy: 0.8571 - val_loss: 0.3350
Epoch 49/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9797 - loss: 0.1099 - val_accuracy: 0.8701 - val_loss: 0.3247
Epoch 50/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9797 - loss: 0.1062 - val_accuracy: 0.8701 - val_loss: 0.3309
Test loss: 0.3526, Test accuracy: 0.8438

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [7]:
import numpy as np

# Load the saved model
loaded_model = keras.models.load_model('tic-tac-toe.model.keras')

# Pick a few random rows from the test set
sample_idx = np.random.choice(len(X_test), 5, replace=False)
sample_X = X_test[sample_idx]
sample_y = np.array(y_test)[sample_idx]

# Make predictions
predictions = loaded_model.predict(sample_X)
predicted_labels = np.argmax(predictions, axis=1)

print("Predicted:", predicted_labels)
print("Actual:   ", sample_y)
print("Correct:  ", (predicted_labels == sample_y))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 458ms/step
Predicted: [0 0 1 0 0]
Actual:    [0 0 1 0 0]
Correct:   [ True  True  True  True  True]

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [8]:
# Try a deeper model, a custom learning rate, and more epochs

model_v2 = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(2, activation='softmax')
])

optimizer = keras.optimizers.Adam(learning_rate=0.001)

model_v2.compile(
    optimizer=optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_v2 = model_v2.fit(X_train, y_train, epochs=100, validation_split=0.1, verbose=0)

test_loss_v2, test_acc_v2 = model_v2.evaluate(X_test, y_test, verbose=0)
print(f"Improved model -> Test loss: {test_loss_v2:.4f}, Test accuracy: {test_acc_v2:.4f}")

I0000 00:00:1786026008.843118   14723 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_9641__.14
I0000 00:00:1786026009.206510   14723 dot_search_space.cc:240] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs? Working around this by using the full hints set instead.
I0000 00:00:1786026011.160916   14721 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_9641__.14

Improved model -> Test loss: 0.4306, Test accuracy: 0.8958

**Which approach(es) did you find helpful to improve your model performance?**

In [9]:
# Adding more layers and training for more epochs helped the most - the extra capacity and training time let the model fit the (fairly complex, non-linear) tic-tac-toe win patterns better.
# Adjusting the learning rate had a smaller effect on its own, but combining it with more epochs gave the most stable convergence.