# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [6]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense

# load the data
df = pd.read_csv("tic-tac-toe.csv")

# quick look at it, just to see if anything looks weird
display(df.head())
display(df.info())
display(df.describe(include="all"))
display(df["class"].value_counts())

# change x, o, b into numbers
# I used 1 for x, -1 for o, and 0 for blank because that makes sense for this board
board_map = {"x": 1, "o": -1, "b": 0}
df_num = df.copy()

for col in df_num.columns[:-1]:
    df_num[col] = df_num[col].map(board_map)

df_num["class"] = df_num["class"].astype(int)

# split inputs and target
X = df_num.drop("class", axis=1)
y = df_num["class"]

X.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

None

         TL   TM   TR   ML   MM   MR   BL   BM   BR class
count   958  958  958  958  958  958  958  958  958   958
unique    3    3    3    3    3    3    3    3    3     2
top       x    x    x    x    x    x    x    x    x  True
freq    418  378  418  378  458  378  418  378  418   626

class
True     626
False    332
Name: count, dtype: int64

   TL  TM  TR  ML  MM  MR  BL  BM  BR
0   1   1   1   1  -1  -1   1  -1  -1
1   1   1   1   1  -1  -1  -1   1  -1
2   1   1   1   1  -1  -1  -1  -1   1
3   1   1   1   1  -1  -1  -1   0   0
4   1   1   1   1  -1  -1   0  -1   0

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# fit the scaler only on the train data so the test data does not leak in
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# basic first model
model = Sequential()
model.add(Dense(32, activation="relu", input_shape=(X_train.shape[1],)))
model.add(Dense(16, activation="relu"))
model.add(Dense(2, activation="softmax"))

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    X_train,
    y_train,
    epochs=30,
    validation_split=0.2,
    verbose=1
)

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print("Test loss:", loss)
print("Test accuracy:", accuracy)

model.save("tic-tac-toe.keras")

Epoch 1/30

/opt/anaconda3/envs/ironhack/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.6814 - loss: 0.6416 - val_accuracy: 0.6753 - val_loss: 0.6395
Epoch 2/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7059 - loss: 0.6088 - val_accuracy: 0.6948 - val_loss: 0.6132
Epoch 3/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7222 - loss: 0.5851 - val_accuracy: 0.7338 - val_loss: 0.5881
Epoch 4/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7222 - loss: 0.5617 - val_accuracy: 0.7338 - val_loss: 0.5661
Epoch 5/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7337 - loss: 0.5411 - val_accuracy: 0.7338 - val_loss: 0.5493
Epoch 6/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7467 - loss: 0.5251 - val_accuracy: 0.7727 - val_loss: 0.5319
Epoch 7/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7598 - loss: 0.5081 - val_accuracy: 0.7662 - val_loss: 0.5188
Epoch 8/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7761 - loss: 0.4913 - val_accuracy: 0.7857 - val_loss: 0.4980
Epoch 9/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7778 - loss: 0.4778 - val_accuracy: 0.7987 - val_loss: 0.4840
Epoch 10/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7925 - loss: 0.4621 - val_accuracy: 0.8182 - val_loss: 0.4631
Epoch 11/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8088 - loss: 0.4454 - val_accuracy: 0.8117 - val_loss: 0.4508
Epoch 12/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8235 - loss: 0.4276 - val_accuracy: 0.8312 - val_loss: 0.4341
Epoch 13/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8350 - loss: 0.4106 - val_accuracy: 0.8442 - val_loss: 0.4215
Epoch 14/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8513 - loss: 0.3929 - val_accuracy: 0.8442 - val_loss: 0.4020
Epoch 15/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8725 - loss: 0.3739 - val_accuracy: 0.8571 - val_loss: 0.3802
Epoch 16/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8824 - loss: 0.3553 - val_accuracy: 0.8766 - val_loss: 0.3659
Epoch 17/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9036 - loss: 0.3374 - val_accuracy: 0.8896 - val_loss: 0.3483
Epoch 18/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9020 - loss: 0.3221 - val_accuracy: 0.8766 - val_loss: 0.3352
Epoch 19/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9150 - loss: 0.3019 - val_accuracy: 0.9091 - val_loss: 0.3110
Epoch 20/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9216 - loss: 0.2844 - val_accuracy: 0.9286 - val_loss: 0.2910
Epoch 21/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9281 - loss: 0.2680 - val_accuracy: 0.9351 - val_loss: 0.2751
Epoch 22/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9330 - loss: 0.2514 - val_accuracy: 0.9416 - val_loss: 0.2668
Epoch 23/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9379 - loss: 0.2356 - val_accuracy: 0.9416 - val_loss: 0.2470
Epoch 24/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9428 - loss: 0.2199 - val_accuracy: 0.9481 - val_loss: 0.2327
Epoch 25/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9526 - loss: 0.2052 - val_accuracy: 0.9481 - val_loss: 0.2159
Epoch 26/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9575 - loss: 0.1908 - val_accuracy: 0.9481 - val_loss: 0.2051
Epoch 27/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9575 - loss: 0.1763 - val_accuracy: 0.9610 - val_loss: 0.1890
Epoch 28/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9657 - loss: 0.1633 - val_accuracy: 0.9675 - val_loss: 0.1797
Epoch 29/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9722 - loss: 0.1504 - val_accuracy: 0.9610 - val_loss: 0.1685
Epoch 30/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9820 - loss: 0.1375 - val_accuracy: 0.9740 - val_loss: 0.1589
Test loss: 0.20098192989826202
Test accuracy: 0.9427083134651184

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [9]:
saved_model = load_model("tic-tac-toe.keras")

# grab a few rows from the test set
random_index = np.random.choice(len(X_test), size=10, replace=False)
sample_X = X_test[random_index]
sample_y = y_test.iloc[random_index].values

pred_probs = saved_model.predict(sample_X)
pred_classes = np.argmax(pred_probs, axis=1)

results = pd.DataFrame({
    "actual": sample_y,
    "prediction": pred_classes,
    "correct": sample_y == pred_classes
})

results

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step

   actual  prediction  correct
0       1           1     True
1       0           1    False
2       0           1    False
3       0           0     True
4       1           1     True
5       0           0     True
6       1           1     True
7       1           1     True
8       0           0     True
9       1           1     True

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [10]:
# trying a slightly bigger model and training it longer
better_model = Sequential()
better_model.add(Dense(64, activation="relu", input_shape=(X_train.shape[1],)))
better_model.add(Dense(64, activation="relu"))
better_model.add(Dense(32, activation="relu"))
better_model.add(Dense(16, activation="relu"))
better_model.add(Dense(2, activation="softmax"))

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

better_model.compile(
    optimizer=optimizer,
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

better_history = better_model.fit(
    X_train,
    y_train,
    epochs=100,
    validation_split=0.2,
    verbose=1
)

better_loss, better_accuracy = better_model.evaluate(X_test, y_test, verbose=0)
print("Better model loss:", better_loss)
print("Better model accuracy:", better_accuracy)

Epoch 1/100

/opt/anaconda3/envs/ironhack/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6863 - loss: 0.6537 - val_accuracy: 0.6753 - val_loss: 0.6041
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7386 - loss: 0.5647 - val_accuracy: 0.7662 - val_loss: 0.5193
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7908 - loss: 0.4864 - val_accuracy: 0.7857 - val_loss: 0.4679
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8235 - loss: 0.4144 - val_accuracy: 0.8247 - val_loss: 0.4027
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8660 - loss: 0.3361 - val_accuracy: 0.8506 - val_loss: 0.3358
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9085 - loss: 0.2669 - val_accuracy: 0.8701 - val_loss: 0.2740
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9428 - loss: 0.1955 - val_accuracy: 0.9286 - val_loss: 0.2029
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9690 - loss: 0.1306 - val_accuracy: 0.9675 - val_loss: 0.1465
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9869 - loss: 0.0852 - val_accuracy: 0.9805 - val_loss: 0.0967
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9951 - loss: 0.0533 - val_accuracy: 0.9870 - val_loss: 0.0721
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9951 - loss: 0.0328 - val_accuracy: 0.9935 - val_loss: 0.0471
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9984 - loss: 0.0220 - val_accuracy: 0.9935 - val_loss: 0.0430
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0143 - val_accuracy: 0.9935 - val_loss: 0.0283
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0110 - val_accuracy: 0.9935 - val_loss: 0.0264
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0070 - val_accuracy: 0.9935 - val_loss: 0.0194
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.9935 - val_loss: 0.0164
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.9935 - val_loss: 0.0144
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.9935 - val_loss: 0.0120
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 1.0000 - val_loss: 0.0103
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 1.0000 - val_loss: 0.0090
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 1.0000 - val_loss: 0.0085
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 1.0000 - val_loss: 0.0074
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 1.0000 - val_loss: 0.0073
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 1.0000 - val_loss: 0.0067
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 1.0000 - val_loss: 0.0063
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 9.2829e-04 - val_accuracy: 1.0000 - val_loss: 0.0056
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 8.3868e-04 - val_accuracy: 1.0000 - val_loss: 0.0054
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 7.5476e-04 - val_accuracy: 1.0000 - val_loss: 0.0054
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 6.5773e-04 - val_accuracy: 1.0000 - val_loss: 0.0048
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 6.1021e-04 - val_accuracy: 1.0000 - val_loss: 0.0044
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 5.5232e-04 - val_accuracy: 1.0000 - val_loss: 0.0043
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.1841e-04 - val_accuracy: 1.0000 - val_loss: 0.0030
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.8559e-04 - val_accuracy: 1.0000 - val_loss: 0.0030
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.3324e-04 - val_accuracy: 1.0000 - val_loss: 0.0030
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.9874e-04 - val_accuracy: 1.0000 - val_loss: 0.0029
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 3.6900e-04 - val_accuracy: 1.0000 - val_loss: 0.0027
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.4623e-04 - val_accuracy: 1.0000 - val_loss: 0.0026
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.2204e-04 - val_accuracy: 1.0000 - val_loss: 0.0026
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.0378e-04 - val_accuracy: 1.0000 - val_loss: 0.0026
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.8805e-04 - val_accuracy: 1.0000 - val_loss: 0.0026
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.7041e-04 - val_accuracy: 1.0000 - val_loss: 0.0023
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.5322e-04 - val_accuracy: 1.0000 - val_loss: 0.0025
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.4093e-04 - val_accuracy: 1.0000 - val_loss: 0.0024
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.2163e-04 - val_accuracy: 1.0000 - val_loss: 0.0020
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.0863e-04 - val_accuracy: 1.0000 - val_loss: 0.0019
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.9702e-04 - val_accuracy: 1.0000 - val_loss: 0.0019
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.8682e-04 - val_accuracy: 1.0000 - val_loss: 0.0019
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.7786e-04 - val_accuracy: 1.0000 - val_loss: 0.0017
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.6853e-04 - val_accuracy: 1.0000 - val_loss: 0.0018
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.6004e-04 - val_accuracy: 1.0000 - val_loss: 0.0017
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.5308e-04 - val_accuracy: 1.0000 - val_loss: 0.0017
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.4632e-04 - val_accuracy: 1.0000 - val_loss: 0.0017
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.3950e-04 - val_accuracy: 1.0000 - val_loss: 0.0017
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.3345e-04 - val_accuracy: 1.0000 - val_loss: 0.0016
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.2872e-04 - val_accuracy: 1.0000 - val_loss: 0.0016
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.2235e-04 - val_accuracy: 1.0000 - val_loss: 0.0015
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.1747e-04 - val_accuracy: 1.0000 - val_loss: 0.0015
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.1302e-04 - val_accuracy: 1.0000 - val_loss: 0.0015
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.0807e-04 - val_accuracy: 1.0000 - val_loss: 0.0014
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.0361e-04 - val_accuracy: 1.0000 - val_loss: 0.0014
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 9.9671e-05 - val_accuracy: 1.0000 - val_loss: 0.0014
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 9.6093e-05 - val_accuracy: 1.0000 - val_loss: 0.0014
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 9.2305e-05 - val_accuracy: 1.0000 - val_loss: 0.0014
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 8.8692e-05 - val_accuracy: 1.0000 - val_loss: 0.0013
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 8.5774e-05 - val_accuracy: 1.0000 - val_loss: 0.0013
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 8.2583e-05 - val_accuracy: 1.0000 - val_loss: 0.0012
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 7.9768e-05 - val_accuracy: 1.0000 - val_loss: 0.0012
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 7.6884e-05 - val_accuracy: 1.0000 - val_loss: 0.0012
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 7.3842e-05 - val_accuracy: 1.0000 - val_loss: 0.0012
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 7.1772e-05 - val_accuracy: 1.0000 - val_loss: 0.0011
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 6.9253e-05 - val_accuracy: 1.0000 - val_loss: 0.0012
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 6.6850e-05 - val_accuracy: 1.0000 - val_loss: 0.0012
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 6.4294e-05 - val_accuracy: 1.0000 - val_loss: 0.0012
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 6.2154e-05 - val_accuracy: 1.0000 - val_loss: 0.0011
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 5.9950e-05 - val_accuracy: 1.0000 - val_loss: 0.0011
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 5.7834e-05 - val_accuracy: 1.0000 - val_loss: 0.0010
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.6128e-05 - val_accuracy: 1.0000 - val_loss: 9.8809e-04
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 5.4557e-05 - val_accuracy: 1.0000 - val_loss: 9.9132e-04
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 5.2746e-05 - val_accuracy: 1.0000 - val_loss: 9.5442e-04
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 5.1126e-05 - val_accuracy: 1.0000 - val_loss: 9.4247e-04
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.9600e-05 - val_accuracy: 1.0000 - val_loss: 9.4185e-04
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.8178e-05 - val_accuracy: 1.0000 - val_loss: 9.1684e-04
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.6747e-05 - val_accuracy: 1.0000 - val_loss: 8.9494e-04
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.5548e-05 - val_accuracy: 1.0000 - val_loss: 9.0482e-04
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.3980e-05 - val_accuracy: 1.0000 - val_loss: 8.8581e-04
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 4.2854e-05 - val_accuracy: 1.0000 - val_loss: 8.5208e-04
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.1354e-05 - val_accuracy: 1.0000 - val_loss: 8.7409e-04
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.9921e-05 - val_accuracy: 1.0000 - val_loss: 8.9810e-04
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.8783e-05 - val_accuracy: 1.0000 - val_loss: 8.8037e-04
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.7704e-05 - val_accuracy: 1.0000 - val_loss: 8.7373e-04
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.6586e-05 - val_accuracy: 1.0000 - val_loss: 8.9482e-04
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.5463e-05 - val_accuracy: 1.0000 - val_loss: 8.5456e-04
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.4558e-05 - val_accuracy: 1.0000 - val_loss: 8.1023e-04
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.3489e-05 - val_accuracy: 1.0000 - val_loss: 7.9618e-04
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.2566e-05 - val_accuracy: 1.0000 - val_loss: 7.9981e-04
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.1674e-05 - val_accuracy: 1.0000 - val_loss: 7.7290e-04
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.0806e-05 - val_accuracy: 1.0000 - val_loss: 7.4911e-04
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.9970e-05 - val_accuracy: 1.0000 - val_loss: 7.4755e-04
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.9243e-05 - val_accuracy: 1.0000 - val_loss: 7.6465e-04
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.8399e-05 - val_accuracy: 1.0000 - val_loss: 7.4849e-04
Better model loss: 0.05480312183499336
Better model accuracy: 0.9791666865348816

**Which approach(es) did you find helpful to improve your model performance?**

In [11]:
"""
Training it for more epochs helped the most for me. The first model was okay,
but it still looked like it had room to learn more. Adding a few more layers also
helped a bit, but I do not think making it super huge is needed because this is
only a small tic tac toe dataset.

The learning rate of 0.001 worked fine, so I just kept it there instead of messing
with it too much.
"""

'\nTraining it for more epochs helped the most for me. The first model was okay,\nbut it still looked like it had room to learn more. Adding a few more layers also\nhelped a bit, but I do not think making it super huge is needed because this is\nonly a small tic tac toe dataset.\n\nThe learning rate of 0.001 worked fine, so I just kept it there instead of messing\nwith it too much.\n'