# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
# your code here
import pandas as pd

df = pd.read_csv('tic-tac-toe.csv')
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [4]:
df.info()
df['class'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

class
True     626
False    332
Name: count, dtype: int64

In [2]:
df.dtypes

TL       object
TM       object
TR       object
ML       object
MM       object
MR       object
BL       object
BM       object
BR       object
class      bool
dtype: object

I will convert values: 
- 'x' → 1
- 'o' → -1
- 'b' → 0

then true/false 1/0

In [6]:
mapping = {'x':1, 'o':-1, 'b':0}
df_num = df.copy()
for col in df_num.columns[:-1]:
    df_num[col] = df_num[col].map(mapping)

df_num['class'] = df_num['class'].astype(int)

In [8]:
df_num.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1  -1  -1   1  -1  -1      1
1   1   1   1   1  -1  -1  -1   1  -1      1
2   1   1   1   1  -1  -1  -1  -1   1      1
3   1   1   1   1  -1  -1  -1   0   0      1
4   1   1   1   1  -1  -1   0  -1   0      1

In [9]:
X = df_num.drop('class', axis=1)
y = df_num['class']

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [12]:
# your code 
import tensorflow as tf 
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(32, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    layers.Dense(16, activation='relu'), 
    layers.Dense(2, activation='softmax')
])

c:\Users\Lain\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [13]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [14]:
history = model.fit(X_train_scaled, y_train, epochs=30, validation_split=0.2)

Epoch 1/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.5481 - loss: 0.6900 - val_accuracy: 0.6753 - val_loss: 0.6377
Epoch 2/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6899 - loss: 0.6342 - val_accuracy: 0.7013 - val_loss: 0.6009
Epoch 3/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7113 - loss: 0.5837 - val_accuracy: 0.7403 - val_loss: 0.5833
Epoch 4/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7306 - loss: 0.5702 - val_accuracy: 0.7597 - val_loss: 0.5680
Epoch 5/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7385 - loss: 0.5426 - val_accuracy: 0.7662 - val_loss: 0.5554
Epoch 6/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7212 - loss: 0.5481 - val_accuracy: 0.7597 - val_loss: 0.5424
Epoch 7/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7464 - loss: 0.5232 - val_accuracy: 0.7662 - val_loss: 0.5298
Epoch 8/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7558 - loss: 0.4958 - val_accuracy: 0.7727 - val_loss: 0.5192
Epoch 9/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7684 - loss: 0.4697 - val_accuracy: 0.7792 - val_loss: 0.5063
Epoch 10/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7652 - loss: 0.4724 - val_accuracy: 0.7792 - val_loss: 0.4917
Epoch 11/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7960 - loss: 0.4482 - val_accuracy: 0.7857 - val_loss: 0.4783
Epoch 12/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7994 - loss: 0.4295 - val_accuracy: 0.7857 - val_loss: 0.4670
Epoch 13/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8071 - loss: 0.4084 - val_accuracy: 0.7987 - val_loss: 0.4517
Epoch 14/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8391 - loss: 0.3719 - val_accuracy: 0.7987 - val_loss: 0.4382
Epoch 15/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8306 - loss: 0.3848 - val_accuracy: 0.8247 - val_loss: 0.4164
Epoch 16/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8452 - loss: 0.3526 - val_accuracy: 0.8312 - val_loss: 0.3971
Epoch 17/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8805 - loss: 0.3264 - val_accuracy: 0.8571 - val_loss: 0.3809
Epoch 18/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8811 - loss: 0.3100 - val_accuracy: 0.8571 - val_loss: 0.3644
Epoch 19/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9139 - loss: 0.2817 - val_accuracy: 0.8701 - val_loss: 0.3461
Epoch 20/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9242 - loss: 0.2640 - val_accuracy: 0.8766 - val_loss: 0.3294
Epoch 21/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9487 - loss: 0.2518 - val_accuracy: 0.8831 - val_loss: 0.3116
Epoch 22/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9404 - loss: 0.2422 - val_accuracy: 0.9091 - val_loss: 0.2958
Epoch 23/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9718 - loss: 0.2131 - val_accuracy: 0.9221 - val_loss: 0.2806
Epoch 24/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9762 - loss: 0.1936 - val_accuracy: 0.9221 - val_loss: 0.2677
Epoch 25/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9915 - loss: 0.1730 - val_accuracy: 0.9286 - val_loss: 0.2509
Epoch 26/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9895 - loss: 0.1667 - val_accuracy: 0.9351 - val_loss: 0.2350
Epoch 27/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9782 - loss: 0.1655 - val_accuracy: 0.9481 - val_loss: 0.2221
Epoch 28/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9930 - loss: 0.1389 - val_accuracy: 0.9481 - val_loss: 0.2138
Epoch 29/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9936 - loss: 0.1273 - val_accuracy: 0.9545 - val_loss: 0.2044
Epoch 30/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9963 - loss: 0.1160 - val_accuracy: 0.9610 - val_loss: 0.1938

In [15]:
test_loss,test_acc = model.evaluate(X_test, y_test)
print(f"Test accuracy: {test_acc:.2f}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8556 - loss: 0.3107
Test accuracy: 0.85

In [17]:
model.save("tic-tac-toe.keras")

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [ ]:
# your code here
from tensorflow.keras.models import load_model 
model = load_model("tic-tac-toe.keras")

In [29]:
import numpy as np
import random
sample_indices = random.sample(range(len(X_test_scaled)), 5)
X_sample = X_test_scaled[sample_indices]
y_sample_true = y_test.iloc[sample_indices]

In [ ]:
y_pred_probs = model.predict(X_sample)
y_pred = np.argmax(y_pred_probs, axis=1)

for i in range(len(y_sample_true)):
    print(f"Prediction: {y_pred[i]}, True Label: {y_sample_true.iloc[i]}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
Prediction: 0, True Label: 0
Prediction: 1, True Label: 1
Prediction: 1, True Label: 1
Prediction: 1, True Label: 1
Prediction: 1, True Label: 1

In [31]:
df_results = pd.DataFrame({
    "Predicted": y_pred,
    "True Label": y_sample_true.values,
    "Confidence Class 0": y_pred_probs[:, 0],
    "Confidence Class 1": y_pred_probs[:, 1]
})

display(df_results)

   Predicted  True Label  Confidence Class 0  Confidence Class 1
0          0           0            0.846003            0.153997
1          1           1            0.020694            0.979306
2          1           1            0.155324            0.844676
3          1           1            0.038040            0.961960
4          1           1            0.051200            0.948800

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [32]:
# your code here
optimizer = keras.optimizers.Adam(learning_rate=0.001)  

model2 = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(2, activation='softmax')  
])

model2.compile(optimizer=optimizer,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model2.fit(X_train_scaled, y_train, epochs=50, validation_split=0.2)

Epoch 1/50

c:\Users\Lain\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5010 - loss: 0.7066 - val_accuracy: 0.7013 - val_loss: 0.6141
Epoch 2/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6967 - loss: 0.5772 - val_accuracy: 0.7922 - val_loss: 0.5530
Epoch 3/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7487 - loss: 0.5355 - val_accuracy: 0.8182 - val_loss: 0.5040
Epoch 4/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7598 - loss: 0.4862 - val_accuracy: 0.8312 - val_loss: 0.4657
Epoch 5/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8254 - loss: 0.4133 - val_accuracy: 0.8377 - val_loss: 0.4270
Epoch 6/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8808 - loss: 0.3584 - val_accuracy: 0.8506 - val_loss: 0.3835
Epoch 7/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9140 - loss: 0.3153 - val_accuracy: 0.8831 - val_loss: 0.3343
Epoch 8/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9325 - loss: 0.2593 - val_accuracy: 0.9091 - val_loss: 0.2830
Epoch 9/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9502 - loss: 0.2173 - val_accuracy: 0.9481 - val_loss: 0.2307
Epoch 10/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9734 - loss: 0.1785 - val_accuracy: 0.9610 - val_loss: 0.1894
Epoch 11/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9865 - loss: 0.1240 - val_accuracy: 0.9675 - val_loss: 0.1631
Epoch 12/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9885 - loss: 0.1049 - val_accuracy: 0.9870 - val_loss: 0.1342
Epoch 13/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9945 - loss: 0.0756 - val_accuracy: 0.9805 - val_loss: 0.1191
Epoch 14/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9977 - loss: 0.0597 - val_accuracy: 0.9805 - val_loss: 0.1073
Epoch 15/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0442 - val_accuracy: 0.9870 - val_loss: 0.0942
Epoch 16/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9991 - loss: 0.0391 - val_accuracy: 0.9870 - val_loss: 0.0844
Epoch 17/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9987 - loss: 0.0316 - val_accuracy: 0.9870 - val_loss: 0.0815
Epoch 18/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9995 - loss: 0.0261 - val_accuracy: 0.9870 - val_loss: 0.0739
Epoch 19/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9993 - loss: 0.0189 - val_accuracy: 0.9870 - val_loss: 0.0712
Epoch 20/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0196 - val_accuracy: 0.9870 - val_loss: 0.0722
Epoch 21/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0145 - val_accuracy: 0.9870 - val_loss: 0.0644
Epoch 22/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0136 - val_accuracy: 0.9870 - val_loss: 0.0604
Epoch 23/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0108 - val_accuracy: 0.9870 - val_loss: 0.0615
Epoch 24/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0097 - val_accuracy: 0.9870 - val_loss: 0.0599
Epoch 25/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0077 - val_accuracy: 0.9870 - val_loss: 0.0561
Epoch 26/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0077 - val_accuracy: 0.9870 - val_loss: 0.0559
Epoch 27/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0073 - val_accuracy: 0.9870 - val_loss: 0.0550
Epoch 28/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0052 - val_accuracy: 0.9870 - val_loss: 0.0565
Epoch 29/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0048 - val_accuracy: 0.9870 - val_loss: 0.0580
Epoch 30/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0047 - val_accuracy: 0.9870 - val_loss: 0.0539
Epoch 31/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0043 - val_accuracy: 0.9870 - val_loss: 0.0541
Epoch 32/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0032 - val_accuracy: 0.9870 - val_loss: 0.0527
Epoch 33/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0032 - val_accuracy: 0.9870 - val_loss: 0.0514
Epoch 34/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.9870 - val_loss: 0.0524
Epoch 35/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9870 - val_loss: 0.0508
Epoch 36/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.9870 - val_loss: 0.0519
Epoch 37/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.9870 - val_loss: 0.0511
Epoch 38/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.9870 - val_loss: 0.0516
Epoch 39/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.9870 - val_loss: 0.0503
Epoch 40/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.9870 - val_loss: 0.0520
Epoch 41/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.9870 - val_loss: 0.0500
Epoch 42/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.9870 - val_loss: 0.0494
Epoch 43/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.9870 - val_loss: 0.0490
Epoch 44/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9870 - val_loss: 0.0501
Epoch 45/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.9870 - val_loss: 0.0471
Epoch 46/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9870 - val_loss: 0.0479
Epoch 47/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.9870 - val_loss: 0.0472
Epoch 48/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9870 - val_loss: 0.0491
Epoch 49/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 9.5267e-04 - val_accuracy: 0.9870 - val_loss: 0.0468
Epoch 50/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.9870 - val_loss: 0.0469

In [33]:
test_loss,test_acc = model2.evaluate(X_test, y_test)
print(f"Test accuracy: {test_acc:.2f}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8074 - loss: 0.6744
Test accuracy: 0.82

In [34]:
optimizer = keras.optimizers.Adam(learning_rate=0.0005)  

model3 = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(2, activation='softmax')  
])

model3.compile(optimizer=optimizer,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history3 = model3.fit(X_train_scaled, y_train, epochs=60, validation_split=0.2)

Epoch 1/60

c:\Users\Lain\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6377 - loss: 0.6826 - val_accuracy: 0.6753 - val_loss: 0.6545
Epoch 2/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6787 - loss: 0.6522 - val_accuracy: 0.6883 - val_loss: 0.6297
Epoch 3/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6838 - loss: 0.6266 - val_accuracy: 0.7208 - val_loss: 0.6069
Epoch 4/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7126 - loss: 0.5972 - val_accuracy: 0.7338 - val_loss: 0.5818
Epoch 5/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7256 - loss: 0.5778 - val_accuracy: 0.7792 - val_loss: 0.5590
Epoch 6/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7423 - loss: 0.5510 - val_accuracy: 0.7857 - val_loss: 0.5377
Epoch 7/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7635 - loss: 0.5135 - val_accuracy: 0.7987 - val_loss: 0.5192
Epoch 8/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7975 - loss: 0.4766 - val_accuracy: 0.7987 - val_loss: 0.5000
Epoch 9/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8041 - loss: 0.4573 - val_accuracy: 0.8052 - val_loss: 0.4826
Epoch 10/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8021 - loss: 0.4522 - val_accuracy: 0.8117 - val_loss: 0.4653
Epoch 11/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8250 - loss: 0.4245 - val_accuracy: 0.8247 - val_loss: 0.4477
Epoch 12/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8461 - loss: 0.4036 - val_accuracy: 0.8182 - val_loss: 0.4258
Epoch 13/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8471 - loss: 0.3956 - val_accuracy: 0.8182 - val_loss: 0.4096
Epoch 14/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8893 - loss: 0.3382 - val_accuracy: 0.8506 - val_loss: 0.3880
Epoch 15/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9091 - loss: 0.3124 - val_accuracy: 0.8636 - val_loss: 0.3596
Epoch 16/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9214 - loss: 0.2824 - val_accuracy: 0.8766 - val_loss: 0.3314
Epoch 17/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9183 - loss: 0.2708 - val_accuracy: 0.9026 - val_loss: 0.3006
Epoch 18/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9430 - loss: 0.2390 - val_accuracy: 0.9026 - val_loss: 0.2808
Epoch 19/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9658 - loss: 0.1987 - val_accuracy: 0.9351 - val_loss: 0.2549
Epoch 20/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9681 - loss: 0.1890 - val_accuracy: 0.9416 - val_loss: 0.2312
Epoch 21/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9794 - loss: 0.1621 - val_accuracy: 0.9545 - val_loss: 0.2015
Epoch 22/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9817 - loss: 0.1557 - val_accuracy: 0.9545 - val_loss: 0.1801
Epoch 23/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9854 - loss: 0.1176 - val_accuracy: 0.9675 - val_loss: 0.1613
Epoch 24/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9950 - loss: 0.1066 - val_accuracy: 0.9675 - val_loss: 0.1515
Epoch 25/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9919 - loss: 0.0875 - val_accuracy: 0.9675 - val_loss: 0.1339
Epoch 26/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9949 - loss: 0.0727 - val_accuracy: 0.9740 - val_loss: 0.1230
Epoch 27/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9911 - loss: 0.0712 - val_accuracy: 0.9870 - val_loss: 0.1100
Epoch 28/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9939 - loss: 0.0569 - val_accuracy: 0.9870 - val_loss: 0.1057
Epoch 29/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9881 - loss: 0.0583 - val_accuracy: 0.9870 - val_loss: 0.1030
Epoch 30/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9918 - loss: 0.0452 - val_accuracy: 0.9870 - val_loss: 0.0945
Epoch 31/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9974 - loss: 0.0360 - val_accuracy: 0.9870 - val_loss: 0.0926
Epoch 32/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9950 - loss: 0.0407 - val_accuracy: 0.9870 - val_loss: 0.0909
Epoch 33/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9971 - loss: 0.0309 - val_accuracy: 0.9870 - val_loss: 0.0857
Epoch 34/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9982 - loss: 0.0274 - val_accuracy: 0.9870 - val_loss: 0.0815
Epoch 35/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9946 - loss: 0.0288 - val_accuracy: 0.9870 - val_loss: 0.0813
Epoch 36/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9950 - loss: 0.0267 - val_accuracy: 0.9870 - val_loss: 0.0787
Epoch 37/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9989 - loss: 0.0190 - val_accuracy: 0.9870 - val_loss: 0.0749
Epoch 38/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9988 - loss: 0.0159 - val_accuracy: 0.9870 - val_loss: 0.0751
Epoch 39/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9996 - loss: 0.0139 - val_accuracy: 0.9870 - val_loss: 0.0708
Epoch 40/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9980 - loss: 0.0144 - val_accuracy: 0.9870 - val_loss: 0.0677
Epoch 41/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9984 - loss: 0.0138 - val_accuracy: 0.9870 - val_loss: 0.0706
Epoch 42/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0111 - val_accuracy: 0.9870 - val_loss: 0.0689
Epoch 43/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0102 - val_accuracy: 0.9870 - val_loss: 0.0692
Epoch 44/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0095 - val_accuracy: 0.9870 - val_loss: 0.0684
Epoch 45/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0079 - val_accuracy: 0.9870 - val_loss: 0.0661
Epoch 46/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0082 - val_accuracy: 0.9870 - val_loss: 0.0679
Epoch 47/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0068 - val_accuracy: 0.9870 - val_loss: 0.0664
Epoch 48/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.9870 - val_loss: 0.0648
Epoch 49/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0064 - val_accuracy: 0.9870 - val_loss: 0.0657
Epoch 50/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.9870 - val_loss: 0.0657
Epoch 51/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0051 - val_accuracy: 0.9870 - val_loss: 0.0632
Epoch 52/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0046 - val_accuracy: 0.9870 - val_loss: 0.0640
Epoch 53/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0043 - val_accuracy: 0.9870 - val_loss: 0.0635
Epoch 54/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0037 - val_accuracy: 0.9870 - val_loss: 0.0620
Epoch 55/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.9870 - val_loss: 0.0621
Epoch 56/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.9870 - val_loss: 0.0627
Epoch 57/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.9870 - val_loss: 0.0612
Epoch 58/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.9870 - val_loss: 0.0610
Epoch 59/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9870 - val_loss: 0.0617
Epoch 60/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.9870 - val_loss: 0.0609

In [35]:
test_loss,test_acc = model3.evaluate(X_test, y_test)
print(f"Test accuracy: {test_acc:.2f}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7474 - loss: 0.6180
Test accuracy: 0.76

In [36]:
optimizer = keras.optimizers.Adam(learning_rate=0.01)  

model4 = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(2, activation='softmax')  
])

model4.compile(optimizer=optimizer,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history4 = model4.fit(X_train_scaled, y_train, epochs=60, validation_split=0.2)

Epoch 1/60

c:\Users\Lain\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6032 - loss: 0.6485 - val_accuracy: 0.7338 - val_loss: 0.5516
Epoch 2/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7818 - loss: 0.4470 - val_accuracy: 0.8442 - val_loss: 0.3493
Epoch 3/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8961 - loss: 0.2449 - val_accuracy: 0.9610 - val_loss: 0.1221
Epoch 4/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9930 - loss: 0.0660 - val_accuracy: 0.9805 - val_loss: 0.0637
Epoch 5/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0195 - val_accuracy: 0.9675 - val_loss: 0.0888
Epoch 6/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9859 - loss: 0.0280 - val_accuracy: 0.9870 - val_loss: 0.0293
Epoch 7/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9975 - loss: 0.0115 - val_accuracy: 0.9805 - val_loss: 0.0705
Epoch 8/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9950 - loss: 0.0218 - val_accuracy: 0.9805 - val_loss: 0.0317
Epoch 9/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0060 - val_accuracy: 0.9870 - val_loss: 0.0398
Epoch 10/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 6.9589e-04 - val_accuracy: 0.9935 - val_loss: 0.0438
Epoch 11/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.6880e-04 - val_accuracy: 0.9870 - val_loss: 0.0424
Epoch 12/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.6364e-04 - val_accuracy: 0.9870 - val_loss: 0.0401
Epoch 13/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.3820e-04 - val_accuracy: 0.9870 - val_loss: 0.0392
Epoch 14/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.0652e-04 - val_accuracy: 0.9870 - val_loss: 0.0389
Epoch 15/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 8.8923e-05 - val_accuracy: 0.9870 - val_loss: 0.0385
Epoch 16/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 9.2894e-05 - val_accuracy: 0.9870 - val_loss: 0.0380
Epoch 17/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 7.8401e-05 - val_accuracy: 0.9870 - val_loss: 0.0381
Epoch 18/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 7.9805e-05 - val_accuracy: 0.9870 - val_loss: 0.0384
Epoch 19/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 7.7210e-05 - val_accuracy: 0.9870 - val_loss: 0.0383
Epoch 20/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 6.1676e-05 - val_accuracy: 0.9870 - val_loss: 0.0381
Epoch 21/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.2321e-05 - val_accuracy: 0.9870 - val_loss: 0.0383
Epoch 22/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 4.2496e-05 - val_accuracy: 0.9870 - val_loss: 0.0381
Epoch 23/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 5.1915e-05 - val_accuracy: 0.9870 - val_loss: 0.0381
Epoch 24/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.2187e-05 - val_accuracy: 0.9870 - val_loss: 0.0382
Epoch 25/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 3.8321e-05 - val_accuracy: 0.9870 - val_loss: 0.0382
Epoch 26/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 4.3339e-05 - val_accuracy: 0.9870 - val_loss: 0.0384
Epoch 27/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 3.3411e-05 - val_accuracy: 0.9870 - val_loss: 0.0381
Epoch 28/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 3.4180e-05 - val_accuracy: 0.9870 - val_loss: 0.0381
Epoch 29/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 3.6256e-05 - val_accuracy: 0.9870 - val_loss: 0.0385
Epoch 30/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 3.3209e-05 - val_accuracy: 0.9870 - val_loss: 0.0382
Epoch 31/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 3.2675e-05 - val_accuracy: 0.9870 - val_loss: 0.0383
Epoch 32/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 3.3293e-05 - val_accuracy: 0.9870 - val_loss: 0.0384
Epoch 33/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.4917e-05 - val_accuracy: 0.9870 - val_loss: 0.0383
Epoch 34/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.9191e-05 - val_accuracy: 0.9870 - val_loss: 0.0384
Epoch 35/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.7652e-05 - val_accuracy: 0.9870 - val_loss: 0.0384
Epoch 36/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.6973e-05 - val_accuracy: 0.9870 - val_loss: 0.0381
Epoch 37/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.2484e-05 - val_accuracy: 0.9870 - val_loss: 0.0382
Epoch 38/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.9994e-05 - val_accuracy: 0.9870 - val_loss: 0.0384
Epoch 39/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.0538e-05 - val_accuracy: 0.9870 - val_loss: 0.0385
Epoch 40/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.2201e-05 - val_accuracy: 0.9870 - val_loss: 0.0384
Epoch 41/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.0187e-05 - val_accuracy: 0.9870 - val_loss: 0.0385
Epoch 42/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.2157e-05 - val_accuracy: 0.9870 - val_loss: 0.0386
Epoch 43/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.5707e-05 - val_accuracy: 0.9870 - val_loss: 0.0385
Epoch 44/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 1.9305e-05 - val_accuracy: 0.9870 - val_loss: 0.0386
Epoch 45/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.0884e-05 - val_accuracy: 0.9870 - val_loss: 0.0385
Epoch 46/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.0202e-05 - val_accuracy: 0.9870 - val_loss: 0.0386
Epoch 47/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.6243e-05 - val_accuracy: 0.9870 - val_loss: 0.0386
Epoch 48/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.5346e-05 - val_accuracy: 0.9870 - val_loss: 0.0386
Epoch 49/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.5004e-05 - val_accuracy: 0.9870 - val_loss: 0.0386
Epoch 50/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.9164e-05 - val_accuracy: 0.9870 - val_loss: 0.0387
Epoch 51/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.5629e-05 - val_accuracy: 0.9870 - val_loss: 0.0384
Epoch 52/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.3866e-05 - val_accuracy: 0.9870 - val_loss: 0.0385
Epoch 53/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.3277e-05 - val_accuracy: 0.9870 - val_loss: 0.0386
Epoch 54/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.2279e-05 - val_accuracy: 0.9870 - val_loss: 0.0385
Epoch 55/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.2319e-05 - val_accuracy: 0.9870 - val_loss: 0.0381
Epoch 56/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.3664e-05 - val_accuracy: 0.9870 - val_loss: 0.0381
Epoch 57/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.1757e-05 - val_accuracy: 0.9870 - val_loss: 0.0386
Epoch 58/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.2367e-05 - val_accuracy: 0.9870 - val_loss: 0.0386
Epoch 59/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.2832e-05 - val_accuracy: 0.9870 - val_loss: 0.0382
Epoch 60/60
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 1.0193e-05 - val_accuracy: 0.9870 - val_loss: 0.0382

In [37]:
test_loss,test_acc = model4.evaluate(X_test, y_test)
print(f"Test accuracy: {test_acc:.2f}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9199 - loss: 0.2601
Test accuracy: 0.92

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here
the best approach was to put a learning rate of 0.01 , 60 epochs and these layers layers.Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(2, activation='softmax')