In [163]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [164]:
tic_tac = pd.read_csv("tic-tac-toe.csv")

In [165]:
display(tic_tac)

    TL TM TR ML MM MR BL BM BR  class
0    x  x  x  x  o  o  x  o  o   True
1    x  x  x  x  o  o  o  x  o   True
2    x  x  x  x  o  o  o  o  x   True
3    x  x  x  x  o  o  o  b  b   True
4    x  x  x  x  o  o  b  o  b   True
..  .. .. .. .. .. .. .. .. ..    ...
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

[958 rows x 10 columns]

In [166]:
tic_tac_dummies = pd.get_dummies(tic_tac).astype(int)

In [167]:
display(tic_tac_dummies)

,class,TL_b,TL_o,TL_x,TM_b,TM_o,TM_x,TR_b,TR_o,TR_x,...,MR_x,BL_b,BL_o,BL_x,BM_b,BM_o,BM_x,BR_b,BR_o,BR_x
0,1,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,1,0,0,1,0
1,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,1,0
2,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,1,0,0,0,1
3,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,1,0,0,1,0,0
4,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953,0,0,1,0,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,0,1
954,0,0,1,0,0,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,1
955,0,0,1,0,0,0,1,0,1,0,...,1,0,0,1,0,1,0,0,0,1
956,0,0,1,0,0,0,1,0,1,0,...,1,0,0,1,0,1,0,0,0,1
957,0,0,1,0,0,1,0,0,0,1,...,0,0,1,0,0,0,1,0,0,1

In [168]:
tic_tac_target = tic_tac_dummies["class"]

tic_tac_target

0      1
1      1
2      1
3      1
4      1
      ..
953    0
954    0
955    0
956    0
957    0
Name: class, Length: 958, dtype: int64

In [169]:
tic_tac_feature = tic_tac_dummies.drop(columns="class")

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [170]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input, Flatten
from tensorflow.keras.optimizers import RMSprop,Adam

In [171]:
X_train,X_test,y_train,y_test = train_test_split(tic_tac_feature,tic_tac_target,train_size=0.8)

In [172]:
model = Sequential()

model.add(Input(shape=(27,)))  #  define the input shape
model.add(Dense(54, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(27, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(2, activation='softmax'))
model.add(Dropout(0.2))

model.summary()

Model: "sequential_19"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_76 (Dense)                │ (None, 54)             │         1,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_76 (Dropout)            │ (None, 54)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_77 (Dense)                │ (None, 27)             │         1,485 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_77 (Dropout)            │ (None, 27)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_78 (Dense)                │ (None, 2)              │            56 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_78 (Dropout)            │ (None, 2)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,053 (11.93 KB)

 Trainable params: 3,053 (11.93 KB)

 Non-trainable params: 0 (0.00 B)

In [173]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [174]:
model_fitted = model.fit(X_train, y_train, epochs=50, validation_split=0.1)

Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5820 - loss: 2.9092 - val_accuracy: 0.6104 - val_loss: 0.6303
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5878 - loss: 3.1879 - val_accuracy: 0.6104 - val_loss: 0.6442
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5806 - loss: 2.7628 - val_accuracy: 0.6104 - val_loss: 0.6272
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6197 - loss: 2.5665 - val_accuracy: 0.6494 - val_loss: 0.5911
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6052 - loss: 2.8736 - val_accuracy: 0.6753 - val_loss: 0.6036
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6183 - loss: 2.9601 - val_accuracy: 0.7143 - val_loss: 0.6055
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6343 - loss: 2.7134 - val_accuracy: 0.7143 - val_loss: 0.6125
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6110 - loss: 2.9384 - val_accuracy: 0.7143 - val_loss: 0.6377
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6589 - loss: 2.2703 - val_accuracy: 0.7403 - val_loss: 0.5639
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6299 - loss: 2.5903 - val_accuracy: 0.7532 - val_loss: 0.5633
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6589 - loss: 2.5773 - val_accuracy: 0.7662 - val_loss: 0.7365
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 2.6292 - val_accuracy: 0.7662 - val_loss: 0.6534
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6749 - loss: 2.5177 - val_accuracy: 0.7792 - val_loss: 0.6629
Epoch 14/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6488 - loss: 2.3864 - val_accuracy: 0.7403 - val_loss: 0.6886
Epoch 15/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6662 - loss: 2.5474 - val_accuracy: 0.7403 - val_loss: 0.7260
Epoch 16/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6662 - loss: 2.4592 - val_accuracy: 0.7532 - val_loss: 0.7334
Epoch 17/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6851 - loss: 2.0573 - val_accuracy: 0.7532 - val_loss: 0.7101
Epoch 18/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6880 - loss: 1.9420 - val_accuracy: 0.7662 - val_loss: 0.8166
Epoch 19/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6647 - loss: 2.2761 - val_accuracy: 0.7792 - val_loss: 0.7685
Epoch 20/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6633 - loss: 2.2837 - val_accuracy: 0.7792 - val_loss: 0.8733
Epoch 21/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6909 - loss: 2.0919 - val_accuracy: 0.8052 - val_loss: 0.8669
Epoch 22/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6662 - loss: 2.0935 - val_accuracy: 0.7792 - val_loss: 0.7392
Epoch 23/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6967 - loss: 2.0920 - val_accuracy: 0.7922 - val_loss: 0.7101
Epoch 24/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6821 - loss: 1.9296 - val_accuracy: 0.8182 - val_loss: 0.5794
Epoch 25/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7184 - loss: 1.7803 - val_accuracy: 0.8182 - val_loss: 0.4871
Epoch 26/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7329 - loss: 1.7320 - val_accuracy: 0.8571 - val_loss: 0.4820
Epoch 27/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7286 - loss: 1.6826 - val_accuracy: 0.8571 - val_loss: 0.3456
Epoch 28/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7097 - loss: 1.7957 - val_accuracy: 0.8182 - val_loss: 0.3975
Epoch 29/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7083 - loss: 1.6730 - val_accuracy: 0.8312 - val_loss: 0.4449
Epoch 30/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7083 - loss: 1.8313 - val_accuracy: 0.8571 - val_loss: 0.3266
Epoch 31/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6981 - loss: 1.6502 - val_accuracy: 0.9091 - val_loss: 0.2605
Epoch 32/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7315 - loss: 1.5223 - val_accuracy: 0.8961 - val_loss: 0.1797
Epoch 33/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7707 - loss: 1.2152 - val_accuracy: 0.9091 - val_loss: 0.1805
Epoch 34/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7504 - loss: 1.2884 - val_accuracy: 0.9351 - val_loss: 0.1401
Epoch 35/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7417 - loss: 1.2861 - val_accuracy: 0.9221 - val_loss: 0.1653
Epoch 36/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7373 - loss: 1.4983 - val_accuracy: 0.9481 - val_loss: 0.1206
Epoch 37/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7475 - loss: 1.1494 - val_accuracy: 0.9351 - val_loss: 0.1462
Epoch 38/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7663 - loss: 1.1018 - val_accuracy: 0.9740 - val_loss: 0.1103
Epoch 39/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7562 - loss: 1.2681 - val_accuracy: 0.9610 - val_loss: 0.1105
Epoch 40/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7649 - loss: 1.0759 - val_accuracy: 0.9610 - val_loss: 0.1059
Epoch 41/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7852 - loss: 1.1196 - val_accuracy: 0.9610 - val_loss: 0.0489
Epoch 42/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.9349 - val_accuracy: 0.9870 - val_loss: 0.0544
Epoch 43/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7649 - loss: 0.9538 - val_accuracy: 0.9740 - val_loss: 0.0352
Epoch 44/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7692 - loss: 1.0414 - val_accuracy: 0.9740 - val_loss: 0.0757
Epoch 45/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7547 - loss: 1.0661 - val_accuracy: 0.9740 - val_loss: 0.0548
Epoch 46/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7504 - loss: 0.9530 - val_accuracy: 0.9740 - val_loss: 0.0429
Epoch 47/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7866 - loss: 0.8404 - val_accuracy: 0.9870 - val_loss: 0.0273
Epoch 48/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7852 - loss: 0.7616 - val_accuracy: 0.9870 - val_loss: 0.0314
Epoch 49/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7896 - loss: 0.7228 - val_accuracy: 0.9870 - val_loss: 0.0333
Epoch 50/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7489 - loss: 0.9632 - val_accuracy: 0.9740 - val_loss: 0.0618

In [175]:
model_evaluated = model.evaluate(X_test, y_test)

model_evaluated

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9635 - loss: 0.2148

[0.21480692923069, 0.9635416865348816]

In [176]:
model.save("tic_tac.keras")

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [177]:
model_loaded = tf.keras.models.load_model('tic_tac.keras')

In [178]:
random_indices = np.random.choice(len(X_test), 5, replace=False)

y_predicted = model.predict(X_test.iloc[random_indices])
y_predicted = pd.Series(np.argmax(y_predicted, axis=1))

precitions_vs_real = pd.concat([y_predicted, y_test.iloc[random_indices].reset_index(drop=True)], axis=1)
precitions_vs_real.columns = ["prediction","true_value"]

precitions_vs_real

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

   prediction  true_value
0           1           1
1           1           1
2           1           1
3           0           0
4           1           1

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [188]:
X_train,X_test,y_train,y_test = train_test_split(tic_tac_feature,tic_tac_target,train_size=0.8)

##

model = Sequential()

model.add(Input(shape=(27,)))  #  define the input shape
model.add(Dense(54, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(54, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(27, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(1, activation='sigmoid'))
model.add(Dropout(0.1))

##

optimizer = Adam(learning_rate=0.005)

model.compile(
    optimizer=optimizer,
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

##

model_fitted = model.fit(X_train, y_train, epochs=50, validation_split=0.1)
model_evaluated = model.evaluate(X_test, y_test)

model.save("tic_tac_2.keras")

model_evaluated

Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6212 - loss: 1.7334 - val_accuracy: 0.6753 - val_loss: 0.5760
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7054 - loss: 1.4354 - val_accuracy: 0.7143 - val_loss: 0.5154
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7678 - loss: 1.2693 - val_accuracy: 0.7922 - val_loss: 0.4109
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8302 - loss: 1.1271 - val_accuracy: 0.8312 - val_loss: 0.3554
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8505 - loss: 1.4730 - val_accuracy: 0.8442 - val_loss: 0.2966
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8447 - loss: 1.4247 - val_accuracy: 0.8831 - val_loss: 0.2766
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8897 - loss: 0.8991 - val_accuracy: 0.8701 - val_loss: 0.2853
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8940 - loss: 0.9769 - val_accuracy: 0.9351 - val_loss: 0.2012
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9042 - loss: 1.0917 - val_accuracy: 0.9481 - val_loss: 0.1323
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8970 - loss: 1.2718 - val_accuracy: 0.9221 - val_loss: 0.1720
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9013 - loss: 1.1346 - val_accuracy: 0.9481 - val_loss: 0.1318
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9115 - loss: 1.0012 - val_accuracy: 0.9481 - val_loss: 0.1513
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9245 - loss: 1.0425 - val_accuracy: 0.9221 - val_loss: 0.1311
Epoch 14/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9144 - loss: 1.2242 - val_accuracy: 0.9351 - val_loss: 0.1193
Epoch 15/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9216 - loss: 1.2136 - val_accuracy: 0.9740 - val_loss: 0.0696
Epoch 16/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9216 - loss: 1.1085 - val_accuracy: 0.9351 - val_loss: 0.1663
Epoch 17/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9216 - loss: 1.0846 - val_accuracy: 0.8961 - val_loss: 0.2032
Epoch 18/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9187 - loss: 1.0642 - val_accuracy: 0.8961 - val_loss: 0.2450
Epoch 19/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9028 - loss: 1.2477 - val_accuracy: 0.9481 - val_loss: 0.2559
Epoch 20/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9245 - loss: 0.9769 - val_accuracy: 0.9740 - val_loss: 0.1026
Epoch 21/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9057 - loss: 1.3504 - val_accuracy: 0.9740 - val_loss: 0.0790
Epoch 22/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9274 - loss: 1.1421 - val_accuracy: 0.9740 - val_loss: 0.0658
Epoch 23/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9318 - loss: 0.9198 - val_accuracy: 0.9740 - val_loss: 0.0599
Epoch 24/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9303 - loss: 1.0087 - val_accuracy: 0.9610 - val_loss: 0.0845
Epoch 25/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9303 - loss: 0.9592 - val_accuracy: 0.9610 - val_loss: 0.0946
Epoch 26/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8882 - loss: 1.4957 - val_accuracy: 0.9351 - val_loss: 0.1362
Epoch 27/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8984 - loss: 1.2898 - val_accuracy: 0.9610 - val_loss: 0.1318
Epoch 28/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9289 - loss: 1.0578 - val_accuracy: 0.9870 - val_loss: 0.0590
Epoch 29/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9332 - loss: 1.0423 - val_accuracy: 0.9740 - val_loss: 0.0465
Epoch 30/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9245 - loss: 1.1041 - val_accuracy: 0.9740 - val_loss: 0.0804
Epoch 31/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9332 - loss: 1.0396 - val_accuracy: 0.9740 - val_loss: 0.0455
Epoch 32/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9158 - loss: 1.2044 - val_accuracy: 0.9870 - val_loss: 0.0723
Epoch 33/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9187 - loss: 1.1366 - val_accuracy: 0.9740 - val_loss: 0.0688
Epoch 34/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9390 - loss: 0.9078 - val_accuracy: 0.9870 - val_loss: 0.0489
Epoch 35/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9260 - loss: 1.0732 - val_accuracy: 0.9870 - val_loss: 0.0400
Epoch 36/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9332 - loss: 0.9963 - val_accuracy: 0.9740 - val_loss: 0.0906
Epoch 37/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9318 - loss: 1.0860 - val_accuracy: 0.9870 - val_loss: 0.0489
Epoch 38/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9347 - loss: 0.9960 - val_accuracy: 0.9740 - val_loss: 0.0486
Epoch 39/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9129 - loss: 1.3515 - val_accuracy: 0.9870 - val_loss: 0.0463
Epoch 40/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9187 - loss: 1.2180 - val_accuracy: 1.0000 - val_loss: 0.0350
Epoch 41/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9231 - loss: 1.0195 - val_accuracy: 1.0000 - val_loss: 0.0365
Epoch 42/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9216 - loss: 1.2030 - val_accuracy: 0.9610 - val_loss: 0.0671
Epoch 43/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9202 - loss: 1.1883 - val_accuracy: 0.9740 - val_loss: 0.0683
Epoch 44/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9303 - loss: 1.0841 - val_accuracy: 0.9870 - val_loss: 0.0614
Epoch 45/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9390 - loss: 0.9261 - val_accuracy: 0.9870 - val_loss: 0.0422
Epoch 46/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9071 - loss: 1.4798 - val_accuracy: 0.9870 - val_loss: 0.0465
Epoch 47/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9347 - loss: 1.0388 - val_accuracy: 0.9870 - val_loss: 0.0348
Epoch 48/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9318 - loss: 1.0801 - val_accuracy: 0.9870 - val_loss: 0.0365
Epoch 49/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9361 - loss: 1.0312 - val_accuracy: 0.9870 - val_loss: 0.0366
Epoch 50/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9274 - loss: 1.1304 - val_accuracy: 0.9870 - val_loss: 0.0268
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9948 - loss: 0.0207

[0.02072271890938282, 0.9947916865348816]

**Which approach(es) did you find helpful to improve your model performance?**

adjusting the learning rate, adding another hidden layer to the nueral network, changing dropout_rate as it seemed high for the size of the dataset, changing from sparse_categorical_crossentropy to binary_crossentropy and setting soft_max to sigmoid as our target is binary. the last point may not improve model performance but seems more appropriate for the situation.

It should be noted that there is still a sizable variance in results.