# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
# your code here
import pandas as pd
data = pd.read_csv(r"C:\Users\lokes\Desktop\ironhack\week 6\day1\lab1\lab-neural-networks\your-code\tic-tac-toe.csv")

In [2]:
df=data.copy()

In [3]:
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [4]:
df.columns

Index(['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR', 'class'], dtype='object')

In [6]:
df.nunique()

TL       3
TM       3
TR       3
ML       3
MM       3
MR       3
BL       3
BM       3
BR       3
class    2
dtype: int64

In [7]:
mapping = {'x': 1, 'o': 2, 'b': 3}
class_mapping = {True: 1, False: 0}

for col in ['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR']:
    df[col] = df[col].map(mapping)
df['class'] = df['class'].map(class_mapping)

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in ['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR', 'class']:
    df[col] = le.fit_transform(df[col])

In [9]:
df.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   0   0   0   0   1   1   0   1   1      1
1   0   0   0   0   1   1   1   0   1      1
2   0   0   0   0   1   1   1   1   0      1
3   0   0   0   0   1   1   1   2   2      1
4   0   0   0   0   1   1   2   1   2      1

In [61]:
df.dtypes

TL       int64
TM       int64
TR       int64
ML       int64
MM       int64
MR       int64
BL       int64
BM       int64
BR       int64
class    int64
dtype: object

In [13]:
X=df.drop(["class"],axis=1)
y=df["class"]

In [14]:
X.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR
0   0   0   0   0   1   1   0   1   1
1   0   0   0   0   1   1   1   0   1
2   0   0   0   0   1   1   1   1   0
3   0   0   0   0   1   1   1   2   2
4   0   0   0   0   1   1   2   1   2

In [15]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: class, dtype: int64

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [16]:
# your code here
from sklearn.model_selection import train_test_split
# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
from sklearn.preprocessing import MinMaxScaler
# Initialize the scaler
scaler = MinMaxScaler()

# Fit scaler on training data and transform both train and test sets
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
X_train_scaled.shape

(766, 9)

In [20]:
y_train.shape

(766,)

In [25]:
len(y_train.unique())

2

In [47]:
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu', input_shape=(9,)),  # 9 features
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(len(y_train.unique()), activation='softmax')  # Output: number of classes
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train the model
model.fit(X_train_scaled, y_train, epochs=40, batch_size=32, validation_split=0.1)

# Evaluate on test data
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f"Test Loss: {loss}, Test Accuracy: {accuracy}")

# Save the trained model
model.save(r"C:\Users\lokes\Desktop\ironhack\week 6\day1\lab1\lab-neural-networks\your-code\tic-tac-toe.keras")

Epoch 1/40

C:\Users\lokes\AppData\Roaming\Python\Python39\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.6733 - loss: 0.6517 - val_accuracy: 0.7143 - val_loss: 0.6009
Epoch 2/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6467 - loss: 0.6231 - val_accuracy: 0.7143 - val_loss: 0.5882
Epoch 3/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6741 - loss: 0.5931 - val_accuracy: 0.7532 - val_loss: 0.5648
Epoch 4/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7030 - loss: 0.5767 - val_accuracy: 0.7662 - val_loss: 0.5355
Epoch 5/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7638 - loss: 0.5230 - val_accuracy: 0.7922 - val_loss: 0.5084
Epoch 6/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7809 - loss: 0.4758 - val_accuracy: 0.8312 - val_loss: 0.4760
Epoch 7/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8554 - loss: 0.4255 - val_accuracy: 0.8442 - val_loss: 0.4599
Epoch 8/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8487 - loss: 0.4091 - val_accuracy: 0.8571 - val_loss: 0.4106
Epoch 9/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8737 - loss: 0.3452 - val_accuracy: 0.8571 - val_loss: 0.3822
Epoch 10/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8951 - loss: 0.2861 - val_accuracy: 0.8961 - val_loss: 0.3456
Epoch 11/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9272 - loss: 0.2581 - val_accuracy: 0.8831 - val_loss: 0.3313
Epoch 12/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9300 - loss: 0.2173 - val_accuracy: 0.9091 - val_loss: 0.3073
Epoch 13/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9376 - loss: 0.2045 - val_accuracy: 0.8961 - val_loss: 0.2755
Epoch 14/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9473 - loss: 0.1551 - val_accuracy: 0.9351 - val_loss: 0.2310
Epoch 15/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9577 - loss: 0.1567 - val_accuracy: 0.9091 - val_loss: 0.2354
Epoch 16/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9653 - loss: 0.1137 - val_accuracy: 0.9351 - val_loss: 0.2032
Epoch 17/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9797 - loss: 0.0942 - val_accuracy: 0.9351 - val_loss: 0.1812
Epoch 18/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9732 - loss: 0.0921 - val_accuracy: 0.9351 - val_loss: 0.1757
Epoch 19/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9869 - loss: 0.0720 - val_accuracy: 0.9351 - val_loss: 0.1400
Epoch 20/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9977 - loss: 0.0551 - val_accuracy: 0.9481 - val_loss: 0.1499
Epoch 21/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9952 - loss: 0.0441 - val_accuracy: 0.9481 - val_loss: 0.1333
Epoch 22/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9974 - loss: 0.0354 - val_accuracy: 0.9610 - val_loss: 0.1128
Epoch 23/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0275 - val_accuracy: 0.9610 - val_loss: 0.1418
Epoch 24/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0254 - val_accuracy: 0.9610 - val_loss: 0.1375
Epoch 25/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0192 - val_accuracy: 0.9610 - val_loss: 0.1117
Epoch 26/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0164 - val_accuracy: 0.9610 - val_loss: 0.1152
Epoch 27/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0123 - val_accuracy: 0.9610 - val_loss: 0.1203
Epoch 28/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0105 - val_accuracy: 0.9610 - val_loss: 0.1011
Epoch 29/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0089 - val_accuracy: 0.9610 - val_loss: 0.0962
Epoch 30/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0080 - val_accuracy: 0.9740 - val_loss: 0.0870
Epoch 31/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0076 - val_accuracy: 0.9610 - val_loss: 0.0988
Epoch 32/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0058 - val_accuracy: 0.9740 - val_loss: 0.0807
Epoch 33/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0060 - val_accuracy: 0.9740 - val_loss: 0.0779
Epoch 34/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0049 - val_accuracy: 0.9740 - val_loss: 0.0770
Epoch 35/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.9740 - val_loss: 0.0717
Epoch 36/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.9740 - val_loss: 0.0799
Epoch 37/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0032 - val_accuracy: 0.9610 - val_loss: 0.0844
Epoch 38/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.9740 - val_loss: 0.0773
Epoch 39/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9740 - val_loss: 0.0792
Epoch 40/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9610 - val_loss: 0.0911
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9850 - loss: 0.0315
Test Loss: 0.03693774342536926, Test Accuracy: 0.9791666865348816

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [48]:
# your code here
import tensorflow as tf
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the model
model = tf.keras.models.load_model(r"C:\Users\lokes\Desktop\ironhack\week 6\day1\lab1\lab-neural-networks\your-code\tic-tac-toe.keras")

# Predict probabilities for all test samples
pred_probs = model.predict(X_test_scaled)
# Get the predicted class (0 or 1) for each sample
pred_labels = np.argmax(pred_probs, axis=1)

# True labels
true_labels = y_test.values

# Compute metrics
accuracy = accuracy_score(true_labels, pred_labels)
print(f"Accuracy: {accuracy:.4f}")

conf_matrix = confusion_matrix(true_labels, pred_labels)
print("Confusion Matrix:")
print(conf_matrix)

print("Classification Report:")
print(classification_report(true_labels, pred_labels))

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Accuracy: 0.9792
Confusion Matrix:
[[ 63   4]
 [  0 125]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        67
           1       0.97      1.00      0.98       125

    accuracy                           0.98       192
   macro avg       0.98      0.97      0.98       192
weighted avg       0.98      0.98      0.98       192

In [49]:
# Evaluate model on the full test set
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9850 - loss: 0.0315
Test Loss: 0.0369
Test Accuracy: 0.9792

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [59]:
# your code here
#model 2
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu', input_shape=(9,)),  # 9 features
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')  # Output: number of classes
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train the model
model.fit(X_train_scaled, y_train, epochs=20, batch_size=32)

# Evaluate on test data
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f"Test Loss: {loss}, Test Accuracy: {accuracy}")

# Save the trained model
model.save(r"C:\Users\lokes\Desktop\ironhack\week 6\day1\lab1\lab-neural-networks\your-code\tic-tac-toe_model_2.keras")

Epoch 1/20

C:\Users\lokes\AppData\Roaming\Python\Python39\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.6369 - loss: 0.6552
Epoch 2/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6588 - loss: 0.6104
Epoch 3/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6925 - loss: 0.5939
Epoch 4/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6954 - loss: 0.5671
Epoch 5/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7731 - loss: 0.5316
Epoch 6/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7974 - loss: 0.4976
Epoch 7/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8267 - loss: 0.4497
Epoch 8/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8563 - loss: 0.4008
Epoch 9/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8772 - loss: 0.3579
Epoch 10/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9004 - loss: 0.3138
Epoch 11/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9227 - loss: 0.2574
Epoch 12/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9076 - loss: 0.2554
Epoch 13/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9232 - loss: 0.2241
Epoch 14/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9411 - loss: 0.1806
Epoch 15/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9615 - loss: 0.1549
Epoch 16/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9652 - loss: 0.1338
Epoch 17/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9739 - loss: 0.1109
Epoch 18/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9835 - loss: 0.0914
Epoch 19/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9852 - loss: 0.0729
Epoch 20/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9920 - loss: 0.0692
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9597 - loss: 0.1249
Test Loss: 0.1296132355928421, Test Accuracy: 0.9583333134651184

In [63]:
# your code here
import tensorflow as tf
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the model
model = tf.keras.models.load_model(r"C:\Users\lokes\Desktop\ironhack\week 6\day1\lab1\lab-neural-networks\your-code\tic-tac-toe_model_2.keras")

# Predict probabilities for all test samples
pred_probs = model.predict(X_test_scaled)
# Get the predicted class (0 or 1) for each sample
thresold = 0.5
pred_labels = (pred_probs >= thresold)
# True labels
true_labels = y_test.values

# Compute metrics
accuracy = accuracy_score(true_labels, pred_labels)
print(f"Accuracy: {accuracy:.4f}")

conf_matrix = confusion_matrix(true_labels, pred_labels)
print("Confusion Matrix:")
print(conf_matrix)

print("Classification Report:")
print(classification_report(true_labels, pred_labels))

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Accuracy: 0.9583
Confusion Matrix:
[[ 59   8]
 [  0 125]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.88      0.94        67
           1       0.94      1.00      0.97       125

    accuracy                           0.96       192
   macro avg       0.97      0.94      0.95       192
weighted avg       0.96      0.96      0.96       192

In [42]:
# Evaluate model on the full test set
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0141
Test Loss: 0.0162
Test Accuracy: 1.0000

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here