# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
import pandas as pd

filename = "tic-tac-toe.csv"

df = pd.read_csv(filename)

In [2]:
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [3]:
# Method_1: replacing 
# x: 1
# o: 0
# b: -1

# True: 1
# False: 0

cleaned_df = df.copy()
cleaned_df["class"] = df["class"].astype("int")

replacements = {"x":1,
                "o": 0,
                "b": -1}

# replacements = {"x":1,
#                 "o": -1,
#                 "b": 0}


cleaned_df = cleaned_df.replace(replacements)

y = cleaned_df["class"]

X = cleaned_df.drop("class", axis=1).astype(float)

X

      TL   TM   TR   ML   MM   MR   BL   BM   BR
0    1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
1    1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
2    1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
3    1.0  1.0  1.0  1.0  0.0  0.0  0.0 -1.0 -1.0
4    1.0  1.0  1.0  1.0  0.0  0.0 -1.0  0.0 -1.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...
953  0.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0
954  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  1.0
955  0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0
956  0.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0
957  0.0  0.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0

[958 rows x 9 columns]

In [4]:
# Version 2 of the dataset: one hot encoding
df.head()

one_hot_encoding = pd.get_dummies(df, drop_first=True)
one_hot_encoding = one_hot_encoding.astype(float)

y_2 = one_hot_encoding["class"]

X_2 = one_hot_encoding.drop("class", axis=1).astype(float)

X_2

,TL_o,TL_x,TM_o,TM_x,TR_o,TR_x,ML_o,ML_x,MM_o,MM_x,MR_o,MR_x,BL_o,BL_x,BM_o,BM_x,BR_o,BR_x
0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
1,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
3,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
954,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
955,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
956,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
957,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [5]:
# split dataset
from sklearn.model_selection import train_test_split

seed = 13
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=seed)

X_train.shape

(766, 9)

In [6]:
# # Normalize
# from keras.utils import normalize

# X_train = normalize(X_train, axis=1) #The axis=1 argument means the normalization is performed along the second axis (which represents the pixel values within each image).
# X_test = normalize(X_test, axis=1)

# print(X_train.shape[0], 'train samples')
# print(X_test.shape[0], 'test samples')

In [7]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Input

model = Sequential()
model.add(Input(shape=(9,)))
model.add(Dense(12, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(24, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(2, activation='softmax'))

model.summary()

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


# model = Sequential()
# model.add(Input(shape=(9,)))
# model.add(Dense(32, activation='relu'))
# model.add(Dropout(0.2))
# model.add(Dense(32, activation='relu'))
# model.add(Dropout(0.2))
# model.add(Dense(2, activation='softmax'))

# model.summary()

# model.compile(optimizer='adam',
#               loss='sparse_categorical_crossentropy',
#               metrics=['accuracy'])

2026-02-16 17:01:49.434220: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2026-02-16 17:01:49.434250: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-02-16 17:01:49.434256: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.92 GB
2026-02-16 17:01:49.434272: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-02-16 17:01:49.434282: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 12)             │           120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 12)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 24)             │           312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 24)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │            50 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 482 (1.88 KB)

 Trainable params: 482 (1.88 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
# split dataset 2
from sklearn.model_selection import train_test_split

seed = 13
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_2,y_2, test_size=0.2, random_state=seed)

X_train_2.shape

(766, 18)

In [9]:
# Normalize dataset 2
from keras.utils import normalize

X_train_2 = normalize(X_train_2, axis=1) #The axis=1 argument means the normalization is performed along the second axis (which represents the pixel values within each image).
X_test_2 = normalize(X_test_2, axis=1)

print(X_train_2.shape[0], 'train samples')
print(X_test_2.shape[0], 'test samples')

766 train samples
192 test samples

In [10]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Input, Flatten

model_2 = Sequential()
model_2.add(Input(shape=(18,)))
model_2.add(Dense(32, activation='relu'))
model_2.add(Dropout(0.2))
model_2.add(Dense(32, activation='relu'))
model_2.add(Dropout(0.2))
model_2.add(Dense(2, activation='softmax'))

model_2.summary()

model_2.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 32)             │           608 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 2)              │            66 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,730 (6.76 KB)

 Trainable params: 1,730 (6.76 KB)

 Non-trainable params: 0 (0.00 B)

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [11]:
# batch_size = 32
# epochs = 50

batch_size = 16
epochs = 30

history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, y_test))

Epoch 1/30

2026-02-16 17:01:50.011561: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

48/48 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5235 - loss: 0.7882 - val_accuracy: 0.6198 - val_loss: 0.6564
Epoch 2/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.6227 - loss: 0.6570 - val_accuracy: 0.6510 - val_loss: 0.6461
Epoch 3/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6188 - loss: 0.6634 - val_accuracy: 0.6615 - val_loss: 0.6427
Epoch 4/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.6462 - loss: 0.6486 - val_accuracy: 0.6510 - val_loss: 0.6463
Epoch 5/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6645 - loss: 0.6432 - val_accuracy: 0.6562 - val_loss: 0.6427
Epoch 6/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6436 - loss: 0.6636 - val_accuracy: 0.6667 - val_loss: 0.6395
Epoch 7/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6580 - loss: 0.6429 - val_accuracy: 0.6458 - val_loss: 0.6428
Epoch 8/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6658 - loss: 0.6406 - val_accuracy: 0.6562 - val_loss: 0.6402
Epoch 9/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6697 - loss: 0.6242 - val_accuracy: 0.6458 - val_loss: 0.6424
Epoch 10/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6488 - loss: 0.6432 - val_accuracy: 0.6615 - val_loss: 0.6400
Epoch 11/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6501 - loss: 0.6419 - val_accuracy: 0.6667 - val_loss: 0.6362
Epoch 12/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.6436 - loss: 0.6316 - val_accuracy: 0.6302 - val_loss: 0.6473
Epoch 13/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.6593 - loss: 0.6406 - val_accuracy: 0.6562 - val_loss: 0.6394
Epoch 14/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6749 - loss: 0.6452 - val_accuracy: 0.6562 - val_loss: 0.6379
Epoch 15/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6710 - loss: 0.6285 - val_accuracy: 0.6458 - val_loss: 0.6337
Epoch 16/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6449 - loss: 0.6346 - val_accuracy: 0.6510 - val_loss: 0.6383
Epoch 17/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6488 - loss: 0.6496 - val_accuracy: 0.6615 - val_loss: 0.6353
Epoch 18/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6593 - loss: 0.6584 - val_accuracy: 0.6510 - val_loss: 0.6362
Epoch 19/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.6527 - loss: 0.6362 - val_accuracy: 0.6250 - val_loss: 0.6419
Epoch 20/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6606 - loss: 0.6346 - val_accuracy: 0.6562 - val_loss: 0.6378
Epoch 21/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6593 - loss: 0.6384 - val_accuracy: 0.6562 - val_loss: 0.6397
Epoch 22/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6567 - loss: 0.6394 - val_accuracy: 0.6458 - val_loss: 0.6388
Epoch 23/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.6658 - loss: 0.6396 - val_accuracy: 0.6510 - val_loss: 0.6377
Epoch 24/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6789 - loss: 0.6290 - val_accuracy: 0.6406 - val_loss: 0.6411
Epoch 25/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6501 - loss: 0.6450 - val_accuracy: 0.6354 - val_loss: 0.6432
Epoch 26/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.6554 - loss: 0.6451 - val_accuracy: 0.6302 - val_loss: 0.6392
Epoch 27/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.6593 - loss: 0.6308 - val_accuracy: 0.6510 - val_loss: 0.6364
Epoch 28/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6436 - loss: 0.6395 - val_accuracy: 0.6615 - val_loss: 0.6355
Epoch 29/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6580 - loss: 0.6426 - val_accuracy: 0.6458 - val_loss: 0.6357
Epoch 30/30
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6514 - loss: 0.6395 - val_accuracy: 0.6354 - val_loss: 0.6404

In [12]:
score = model.evaluate(X_test, y_test)

print('Test loss:', score[0])
print('Test accuracy:', score[1])

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6354 - loss: 0.6404
Test loss: 0.6403724551200867
Test accuracy: 0.6354166865348816

In [13]:
batch_size = 32
epochs = 50


history_2 = model_2.fit(X_train_2, y_train_2,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test_2, y_test_2))

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.5953 - loss: 0.6669 - val_accuracy: 0.6146 - val_loss: 0.6569
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6540 - loss: 0.6312 - val_accuracy: 0.6146 - val_loss: 0.6396
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6710 - loss: 0.6086 - val_accuracy: 0.6302 - val_loss: 0.6212
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6984 - loss: 0.5813 - val_accuracy: 0.6615 - val_loss: 0.6041
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7037 - loss: 0.5741 - val_accuracy: 0.6875 - val_loss: 0.5855
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7337 - loss: 0.5519 - val_accuracy: 0.6979 - val_loss: 0.5665
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7245 - loss: 0.5314 - val_accuracy: 0.7135 - val_loss: 0.5559
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7546 - loss: 0.5132 - val_accuracy: 0.7135 - val_loss: 0.5397
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7402 - loss: 0.5146 - val_accuracy: 0.7188 - val_loss: 0.5279
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7742 - loss: 0.4840 - val_accuracy: 0.7500 - val_loss: 0.5190
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7493 - loss: 0.4940 - val_accuracy: 0.7500 - val_loss: 0.5036
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7572 - loss: 0.4890 - val_accuracy: 0.7604 - val_loss: 0.4936
Epoch 13/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7781 - loss: 0.4577 - val_accuracy: 0.7708 - val_loss: 0.4792
Epoch 14/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7950 - loss: 0.4412 - val_accuracy: 0.7708 - val_loss: 0.4592
Epoch 15/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8029 - loss: 0.4325 - val_accuracy: 0.7812 - val_loss: 0.4359
Epoch 16/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7950 - loss: 0.4198 - val_accuracy: 0.7969 - val_loss: 0.4181
Epoch 17/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8133 - loss: 0.4091 - val_accuracy: 0.8229 - val_loss: 0.3921
Epoch 18/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8290 - loss: 0.3961 - val_accuracy: 0.8125 - val_loss: 0.3842
Epoch 19/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8407 - loss: 0.3631 - val_accuracy: 0.8698 - val_loss: 0.3476
Epoch 20/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8708 - loss: 0.3469 - val_accuracy: 0.9062 - val_loss: 0.3222
Epoch 21/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8590 - loss: 0.3324 - val_accuracy: 0.9062 - val_loss: 0.2957
Epoch 22/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8760 - loss: 0.3164 - val_accuracy: 0.9115 - val_loss: 0.2735
Epoch 23/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9021 - loss: 0.2819 - val_accuracy: 0.9427 - val_loss: 0.2378
Epoch 24/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8890 - loss: 0.2803 - val_accuracy: 0.9896 - val_loss: 0.2063
Epoch 25/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8995 - loss: 0.2667 - val_accuracy: 0.9375 - val_loss: 0.2117
Epoch 26/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9256 - loss: 0.2526 - val_accuracy: 0.9688 - val_loss: 0.1862
Epoch 27/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9295 - loss: 0.2260 - val_accuracy: 0.9896 - val_loss: 0.1528
Epoch 28/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9439 - loss: 0.2090 - val_accuracy: 0.9896 - val_loss: 0.1376
Epoch 29/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9373 - loss: 0.2089 - val_accuracy: 0.9896 - val_loss: 0.1404
Epoch 30/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9399 - loss: 0.1972 - val_accuracy: 0.9896 - val_loss: 0.1089
Epoch 31/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9517 - loss: 0.1831 - val_accuracy: 0.9896 - val_loss: 0.1115
Epoch 32/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9634 - loss: 0.1607 - val_accuracy: 0.9896 - val_loss: 0.0961
Epoch 33/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9530 - loss: 0.1756 - val_accuracy: 0.9896 - val_loss: 0.0893
Epoch 34/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9661 - loss: 0.1462 - val_accuracy: 0.9896 - val_loss: 0.0819
Epoch 35/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9700 - loss: 0.1520 - val_accuracy: 0.9896 - val_loss: 0.0750
Epoch 36/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9648 - loss: 0.1520 - val_accuracy: 0.9896 - val_loss: 0.0702
Epoch 37/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9726 - loss: 0.1280 - val_accuracy: 0.9896 - val_loss: 0.0696
Epoch 38/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9687 - loss: 0.1266 - val_accuracy: 0.9896 - val_loss: 0.0636
Epoch 39/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9648 - loss: 0.1144 - val_accuracy: 0.9896 - val_loss: 0.0580
Epoch 40/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9674 - loss: 0.1266 - val_accuracy: 0.9896 - val_loss: 0.0731
Epoch 41/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9621 - loss: 0.1376 - val_accuracy: 0.9896 - val_loss: 0.0556
Epoch 42/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9674 - loss: 0.1247 - val_accuracy: 0.9896 - val_loss: 0.0521
Epoch 43/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9739 - loss: 0.1101 - val_accuracy: 0.9896 - val_loss: 0.0514
Epoch 44/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9687 - loss: 0.1106 - val_accuracy: 0.9896 - val_loss: 0.0498
Epoch 45/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9713 - loss: 0.1146 - val_accuracy: 0.9896 - val_loss: 0.0547
Epoch 46/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9687 - loss: 0.1143 - val_accuracy: 0.9896 - val_loss: 0.0514
Epoch 47/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9739 - loss: 0.1009 - val_accuracy: 0.9896 - val_loss: 0.0489
Epoch 48/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9739 - loss: 0.1133 - val_accuracy: 0.9896 - val_loss: 0.0485
Epoch 49/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9700 - loss: 0.1204 - val_accuracy: 0.9896 - val_loss: 0.0477
Epoch 50/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9739 - loss: 0.1047 - val_accuracy: 0.9896 - val_loss: 0.0462

In [14]:
score_2 = model_2.evaluate(X_test_2, y_test_2)

print('Test loss:', score_2[0])
print('Test accuracy:', score_2[1])

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9896 - loss: 0.0462
Test loss: 0.04622383043169975
Test accuracy: 0.9895833134651184

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [15]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Input
from keras.optimizers import Adam

model_3 = Sequential()
model_3.add(Input(shape=(18,)))
model_3.add(Dense(64, activation='relu'))
model_3.add(Dropout(0.1))
model_3.add(Dense(64, activation='relu'))
model_3.add(Dropout(0.1))
model_3.add(Dense(1, activation='sigmoid'))

model_3.summary()

model_3.compile(optimizer=Adam(learning_rate=0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,441 (21.25 KB)

 Trainable params: 5,441 (21.25 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
batch_size = 32
epochs = 50


history_3 = model_3.fit(X_train_2, y_train_2,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test_2, y_test_2))

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.6031 - loss: 0.6510 - val_accuracy: 0.6198 - val_loss: 0.6354
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6710 - loss: 0.5924 - val_accuracy: 0.6771 - val_loss: 0.6003
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7154 - loss: 0.5603 - val_accuracy: 0.7031 - val_loss: 0.5803
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7389 - loss: 0.5368 - val_accuracy: 0.7135 - val_loss: 0.5558
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7363 - loss: 0.5197 - val_accuracy: 0.7240 - val_loss: 0.5457
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7311 - loss: 0.5066 - val_accuracy: 0.7135 - val_loss: 0.5267
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7598 - loss: 0.4845 - val_accuracy: 0.7292 - val_loss: 0.5126
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7689 - loss: 0.4705 - val_accuracy: 0.7448 - val_loss: 0.4914
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7768 - loss: 0.4478 - val_accuracy: 0.7604 - val_loss: 0.4759
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7911 - loss: 0.4293 - val_accuracy: 0.8073 - val_loss: 0.4343
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8055 - loss: 0.4081 - val_accuracy: 0.8385 - val_loss: 0.4013
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8460 - loss: 0.3771 - val_accuracy: 0.8594 - val_loss: 0.3667
Epoch 13/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8668 - loss: 0.3450 - val_accuracy: 0.9115 - val_loss: 0.3236
Epoch 14/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8890 - loss: 0.3076 - val_accuracy: 0.9219 - val_loss: 0.2810
Epoch 15/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9008 - loss: 0.2783 - val_accuracy: 0.9896 - val_loss: 0.2377
Epoch 16/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9360 - loss: 0.2403 - val_accuracy: 0.9792 - val_loss: 0.2038
Epoch 17/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9452 - loss: 0.2200 - val_accuracy: 0.9896 - val_loss: 0.1700
Epoch 18/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9504 - loss: 0.1942 - val_accuracy: 0.9896 - val_loss: 0.1455
Epoch 19/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9621 - loss: 0.1671 - val_accuracy: 0.9896 - val_loss: 0.1351
Epoch 20/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9478 - loss: 0.1686 - val_accuracy: 0.9896 - val_loss: 0.1053
Epoch 21/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9608 - loss: 0.1584 - val_accuracy: 0.9896 - val_loss: 0.0944
Epoch 22/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9726 - loss: 0.1177 - val_accuracy: 0.9896 - val_loss: 0.0865
Epoch 23/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9700 - loss: 0.1246 - val_accuracy: 0.9896 - val_loss: 0.0766
Epoch 24/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9674 - loss: 0.1217 - val_accuracy: 0.9896 - val_loss: 0.0817
Epoch 25/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9700 - loss: 0.1145 - val_accuracy: 0.9896 - val_loss: 0.0769
Epoch 26/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9791 - loss: 0.1018 - val_accuracy: 0.9896 - val_loss: 0.0680
Epoch 27/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9778 - loss: 0.1155 - val_accuracy: 0.9896 - val_loss: 0.0640
Epoch 28/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9739 - loss: 0.0995 - val_accuracy: 0.9896 - val_loss: 0.0529
Epoch 29/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9778 - loss: 0.0969 - val_accuracy: 0.9896 - val_loss: 0.0533
Epoch 30/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9804 - loss: 0.0980 - val_accuracy: 0.9896 - val_loss: 0.0539
Epoch 31/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9804 - loss: 0.0873 - val_accuracy: 0.9896 - val_loss: 0.0538
Epoch 32/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9752 - loss: 0.0917 - val_accuracy: 0.9896 - val_loss: 0.0547
Epoch 33/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9804 - loss: 0.0835 - val_accuracy: 0.9896 - val_loss: 0.0516
Epoch 34/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9765 - loss: 0.0861 - val_accuracy: 0.9896 - val_loss: 0.0453
Epoch 35/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9804 - loss: 0.0937 - val_accuracy: 0.9896 - val_loss: 0.0471
Epoch 36/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9765 - loss: 0.0856 - val_accuracy: 0.9896 - val_loss: 0.0470
Epoch 37/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9752 - loss: 0.0958 - val_accuracy: 0.9896 - val_loss: 0.0488
Epoch 38/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9778 - loss: 0.0896 - val_accuracy: 0.9896 - val_loss: 0.0485
Epoch 39/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9817 - loss: 0.0862 - val_accuracy: 0.9896 - val_loss: 0.0468
Epoch 40/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9739 - loss: 0.0806 - val_accuracy: 0.9896 - val_loss: 0.0466
Epoch 41/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9765 - loss: 0.0800 - val_accuracy: 0.9896 - val_loss: 0.0447
Epoch 42/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9791 - loss: 0.0886 - val_accuracy: 0.9896 - val_loss: 0.0398
Epoch 43/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9778 - loss: 0.0890 - val_accuracy: 0.9896 - val_loss: 0.0433
Epoch 44/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9791 - loss: 0.0759 - val_accuracy: 0.9896 - val_loss: 0.0470
Epoch 45/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9804 - loss: 0.0832 - val_accuracy: 0.9896 - val_loss: 0.0447
Epoch 46/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9752 - loss: 0.0917 - val_accuracy: 0.9896 - val_loss: 0.0480
Epoch 47/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9739 - loss: 0.0915 - val_accuracy: 0.9896 - val_loss: 0.0406
Epoch 48/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9739 - loss: 0.0810 - val_accuracy: 0.9896 - val_loss: 0.0426
Epoch 49/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9791 - loss: 0.0734 - val_accuracy: 0.9896 - val_loss: 0.0435
Epoch 50/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9765 - loss: 0.0760 - val_accuracy: 0.9896 - val_loss: 0.0444

In [17]:
score_3 = model_3.evaluate(X_test_2, y_test_2)

print('Test loss:', score_3[0])
print('Test accuracy:', score_3[1])

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9896 - loss: 0.0444
Test loss: 0.04443689063191414
Test accuracy: 0.9895833134651184

**Which approach(es) did you find helpful to improve your model performance?**

The method that drastically changed my results was changing the way I treated the data.
The first method I tried I replaced x,o and b by 0,1, and -1. When I changed to one-hot-encoding
the performance of the model went from 0.7 to 0.97. 

A third variation on the dataset where instead of 

replacements = {"x":1,
                "o": 0,
                "b": -1}

we use: 
replacements = {"x":1,
                "o": -1,
                "b": 0}

This also improved the results from 0.7 to 0.9 during traing and 0.97 during the test.

Which is interesting to notice how we encode the data can drastically change the results we see.

Considering the hyperparameters for this case what helped improve the model:
- Increase the number of neurons. Increasing the layers did not help much for the data v1.
- Increasing the epochs.
- Changing the learning rate.