# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
# your code here
# your code here
import pandas as pd
import numpy as np

ttt = pd.read_csv('/Users/work/Documents/DSML25/week_6/6.1.lab-neural-networks/your-code/tic-tac-toe.csv')
ttt.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [2]:
ttt.isna().sum()

TL       0
TM       0
TR       0
ML       0
MM       0
MR       0
BL       0
BM       0
BR       0
class    0
dtype: int64

In [27]:
X = ttt.drop(columns='class')
y = ttt['class']

repl = {
    'x': 1,
    'o': 2,
    'b': 0
}

X = X.replace(repl).astype(int)
X.head()

/var/folders/_5/9xl167095gn7qzk16djnlv300000gp/T/ipykernel_18849/1749255653.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X = X.replace(repl).astype(int)

   TL  TM  TR  ML  MM  MR  BL  BM  BR
0   1   1   1   1   2   2   1   2   2
1   1   1   1   1   2   2   2   1   2
2   1   1   1   1   2   2   2   2   1
3   1   1   1   1   2   2   2   0   0
4   1   1   1   1   2   2   0   2   0

In [28]:
ttt.value_counts()

TL  TM  TR  ML  MM  MR  BL  BM  BR  class
b   b   b   b   o   o   x   x   x   True     1
x   b   x   x   o   o   x   b   o   True     1
            o   o   x   b   o   x   True     1
                        o   b   x   True     1
                x   b   o   o   x   True     1
                                            ..
o   o   o   b   x   x   x   o   x   False    1
                            x   o   False    1
            o   x   x   b   x   x   False    1
                        x   b   x   False    1
x   x   x   x   o   o   x   o   o   True     1
Name: count, Length: 958, dtype: int64

In [29]:
ttt.nunique()

TL       3
TM       3
TR       3
ML       3
MM       3
MR       3
BL       3
BM       3
BR       3
class    2
dtype: int64

In [35]:
import tensorflow as tf

import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Input, Flatten
from keras.optimizers import RMSprop

In [36]:
X_scaled = keras.utils.normalize(X.values, axis=1)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, random_state=8, test_size=.35)

In [74]:
# your code here
from keras.optimizers import Adam


##### Build the model

model = Sequential()
model.add(Input(shape=(9,))) 
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(2, activation='softmax'))



model.summary()
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_35 (Dense)                │ (None, 16)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_22 (Dropout)            │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_36 (Dense)                │ (None, 32)             │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_23 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_37 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_24 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_38 (Dense)                │ (None, 2)              │           130 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,946 (11.51 KB)

 Trainable params: 2,946 (11.51 KB)

 Non-trainable params: 0 (0.00 B)

In [77]:
# Train the model

batch_size = 10
epochs = 40

history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, y_test))

Epoch 1/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7665 - loss: 0.4334 - val_accuracy: 0.7470 - val_loss: 0.4858
Epoch 2/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step - accuracy: 0.7656 - loss: 0.4712 - val_accuracy: 0.7292 - val_loss: 0.4786
Epoch 3/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - accuracy: 0.7134 - loss: 0.4895 - val_accuracy: 0.7321 - val_loss: 0.4692
Epoch 4/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 731us/step - accuracy: 0.7026 - loss: 0.4945 - val_accuracy: 0.7411 - val_loss: 0.4713
Epoch 5/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 752us/step - accuracy: 0.7281 - loss: 0.4899 - val_accuracy: 0.7589 - val_loss: 0.4653
Epoch 6/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 741us/step - accuracy: 0.7393 - loss: 0.4679 - val_accuracy: 0.7530 - val_loss: 0.4680
Epoch 7/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.7314 - loss: 0.4624 - val_accuracy: 0.7440 - val_loss: 0.4643
Epoch 8/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - accuracy: 0.7301 - loss: 0.4797 - val_accuracy: 0.7500 - val_loss: 0.4600
Epoch 9/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 760us/step - accuracy: 0.7394 - loss: 0.4522 - val_accuracy: 0.7321 - val_loss: 0.4672
Epoch 10/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 762us/step - accuracy: 0.7539 - loss: 0.4495 - val_accuracy: 0.7411 - val_loss: 0.4645
Epoch 11/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - accuracy: 0.7510 - loss: 0.4455 - val_accuracy: 0.7530 - val_loss: 0.4662
Epoch 12/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 701us/step - accuracy: 0.7900 - loss: 0.4461 - val_accuracy: 0.7500 - val_loss: 0.4545
Epoch 13/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step - accuracy: 0.7500 - loss: 0.4540 - val_accuracy: 0.7560 - val_loss: 0.4525
Epoch 14/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - accuracy: 0.7437 - loss: 0.4670 - val_accuracy: 0.7440 - val_loss: 0.4535
Epoch 15/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - accuracy: 0.7552 - loss: 0.4592 - val_accuracy: 0.7530 - val_loss: 0.4608
Epoch 16/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step - accuracy: 0.7072 - loss: 0.4725 - val_accuracy: 0.7262 - val_loss: 0.4534
Epoch 17/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - accuracy: 0.7127 - loss: 0.4671 - val_accuracy: 0.7440 - val_loss: 0.4503
Epoch 18/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - accuracy: 0.7651 - loss: 0.4398 - val_accuracy: 0.7500 - val_loss: 0.4485
Epoch 19/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step - accuracy: 0.7453 - loss: 0.4525 - val_accuracy: 0.7500 - val_loss: 0.4465
Epoch 20/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.7573 - loss: 0.4351 - val_accuracy: 0.7589 - val_loss: 0.4438
Epoch 21/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step - accuracy: 0.7683 - loss: 0.4192 - val_accuracy: 0.7708 - val_loss: 0.4441
Epoch 22/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - accuracy: 0.7554 - loss: 0.4397 - val_accuracy: 0.7768 - val_loss: 0.4395
Epoch 23/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7523 - loss: 0.4375 - val_accuracy: 0.7798 - val_loss: 0.4364
Epoch 24/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 704us/step - accuracy: 0.7777 - loss: 0.4361 - val_accuracy: 0.7738 - val_loss: 0.4367
Epoch 25/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step - accuracy: 0.7406 - loss: 0.4618 - val_accuracy: 0.7738 - val_loss: 0.4373
Epoch 26/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 749us/step - accuracy: 0.7026 - loss: 0.4590 - val_accuracy: 0.7619 - val_loss: 0.4354
Epoch 27/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 739us/step - accuracy: 0.7893 - loss: 0.4116 - val_accuracy: 0.7560 - val_loss: 0.4397
Epoch 28/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 710us/step - accuracy: 0.7939 - loss: 0.4011 - val_accuracy: 0.7827 - val_loss: 0.4291
Epoch 29/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 771us/step - accuracy: 0.8020 - loss: 0.4179 - val_accuracy: 0.7560 - val_loss: 0.4379
Epoch 30/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 775us/step - accuracy: 0.7459 - loss: 0.4151 - val_accuracy: 0.7679 - val_loss: 0.4427
Epoch 31/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 737us/step - accuracy: 0.7832 - loss: 0.4252 - val_accuracy: 0.7827 - val_loss: 0.4270
Epoch 32/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 749us/step - accuracy: 0.7426 - loss: 0.4380 - val_accuracy: 0.7887 - val_loss: 0.4288
Epoch 33/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 694us/step - accuracy: 0.7832 - loss: 0.4131 - val_accuracy: 0.7768 - val_loss: 0.4383
Epoch 34/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step - accuracy: 0.7747 - loss: 0.4386 - val_accuracy: 0.7738 - val_loss: 0.4381
Epoch 35/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step - accuracy: 0.7693 - loss: 0.4328 - val_accuracy: 0.7768 - val_loss: 0.4285
Epoch 36/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7785 - loss: 0.3936 - val_accuracy: 0.7619 - val_loss: 0.4249
Epoch 37/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - accuracy: 0.7789 - loss: 0.4012 - val_accuracy: 0.7768 - val_loss: 0.4291
Epoch 38/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - accuracy: 0.7662 - loss: 0.4274 - val_accuracy: 0.7708 - val_loss: 0.4331
Epoch 39/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 728us/step - accuracy: 0.7945 - loss: 0.4039 - val_accuracy: 0.7798 - val_loss: 0.4208
Epoch 40/40
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - accuracy: 0.8009 - loss: 0.3794 - val_accuracy: 0.7708 - val_loss: 0.4378

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [78]:
# your code here

score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.4378010928630829
Test accuracy: 0.7708333134651184

In [69]:
model.save('tic-tac-toe.keras')

In [79]:
my_model=tf.keras.models.load_model("tic-tac-toe.keras")

In [80]:
predictions = my_model.predict(X_test)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [90]:
import numpy as np

print(np.argmax(predictions[0:5], axis=1))

[0 1 0 1 1]

In [114]:
#experiment with new data
to_pred = [0,5,36,78, 104, 456]
to_pred_X = keras.utils.normalize(np.array([X.values[x] for x in to_pred], dtype=float), axis=1)
observed_y = [bool(y.values[x]) for x in to_pred]

predictions = my_model.predict(to_pred_X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

In [ ]:
predicted_y = [bool(np.argmax(predictions[x])) for x in range(len(predictions))]
print(predicted_y)
print()

[True, False, True, True, True, True]

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [ ]:
# your code here

**Which approach(es) did you find helpful to improve your model performance?**

In [153]:
# your answer here

model = Sequential()
model.add(Input(shape=(9,))) 
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.1))

model.add(Dense(2, activation='softmax'))



model.summary()
optimizer = Adam(learning_rate=0.005)
model.compile(optimizer=optimizer,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

Model: "sequential_27"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_107 (Dense)               │ (None, 16)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_60 (Dropout)            │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_108 (Dense)               │ (None, 32)             │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_109 (Dense)               │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_61 (Dropout)            │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_110 (Dense)               │ (None, 2)              │            34 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,266 (4.95 KB)

 Trainable params: 1,266 (4.95 KB)

 Non-trainable params: 0 (0.00 B)

In [154]:
batch_size = 10
epochs = 60

from keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, y_test),
                    callbacks=[early_stop])

score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Epoch 1/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6048 - loss: 0.6630 - val_accuracy: 0.6518 - val_loss: 0.6255
Epoch 2/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6536 - loss: 0.6198 - val_accuracy: 0.6518 - val_loss: 0.6089
Epoch 3/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step - accuracy: 0.6502 - loss: 0.6255 - val_accuracy: 0.6518 - val_loss: 0.5947
Epoch 4/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step - accuracy: 0.6518 - loss: 0.5837 - val_accuracy: 0.6518 - val_loss: 0.5635
Epoch 5/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step - accuracy: 0.6744 - loss: 0.5606 - val_accuracy: 0.6696 - val_loss: 0.5455
Epoch 6/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 739us/step - accuracy: 0.7027 - loss: 0.5475 - val_accuracy: 0.6994 - val_loss: 0.5356
Epoch 7/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6967 - loss: 0.5366 - val_accuracy: 0.6994 - val_loss: 0.5356
Epoch 8/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 773us/step - accuracy: 0.7615 - loss: 0.4700 - val_accuracy: 0.6696 - val_loss: 0.5500
Epoch 9/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - accuracy: 0.7175 - loss: 0.5009 - val_accuracy: 0.6935 - val_loss: 0.5334
Epoch 10/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - accuracy: 0.7538 - loss: 0.4921 - val_accuracy: 0.7292 - val_loss: 0.5060
Epoch 11/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step - accuracy: 0.7728 - loss: 0.4711 - val_accuracy: 0.6815 - val_loss: 0.5432
Epoch 12/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - accuracy: 0.7591 - loss: 0.4731 - val_accuracy: 0.7351 - val_loss: 0.4861
Epoch 13/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step - accuracy: 0.7555 - loss: 0.4633 - val_accuracy: 0.7262 - val_loss: 0.4858
Epoch 14/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step - accuracy: 0.7774 - loss: 0.4472 - val_accuracy: 0.6875 - val_loss: 0.5322
Epoch 15/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - accuracy: 0.7788 - loss: 0.4549 - val_accuracy: 0.7143 - val_loss: 0.5052
Epoch 16/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7746 - loss: 0.4318 - val_accuracy: 0.7113 - val_loss: 0.4957
Epoch 17/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step - accuracy: 0.7984 - loss: 0.4209 - val_accuracy: 0.7440 - val_loss: 0.4870
Epoch 18/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 728us/step - accuracy: 0.8003 - loss: 0.4085 - val_accuracy: 0.7321 - val_loss: 0.4744
Epoch 19/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.7761 - loss: 0.4146 - val_accuracy: 0.7173 - val_loss: 0.5061
Epoch 20/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - accuracy: 0.8026 - loss: 0.4282 - val_accuracy: 0.7530 - val_loss: 0.4790
Epoch 21/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 737us/step - accuracy: 0.8223 - loss: 0.3948 - val_accuracy: 0.7113 - val_loss: 0.5281
Epoch 22/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 694us/step - accuracy: 0.7654 - loss: 0.4648 - val_accuracy: 0.7143 - val_loss: 0.6069
Epoch 23/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step - accuracy: 0.7561 - loss: 0.4650 - val_accuracy: 0.7381 - val_loss: 0.4912
Epoch 24/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.8243 - loss: 0.3947 - val_accuracy: 0.7440 - val_loss: 0.4646
Epoch 25/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step - accuracy: 0.8353 - loss: 0.3822 - val_accuracy: 0.7292 - val_loss: 0.5027
Epoch 26/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - accuracy: 0.7764 - loss: 0.4282 - val_accuracy: 0.7440 - val_loss: 0.4797
Epoch 27/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 755us/step - accuracy: 0.8061 - loss: 0.4042 - val_accuracy: 0.7381 - val_loss: 0.4703
Epoch 28/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.7941 - loss: 0.3995 - val_accuracy: 0.7381 - val_loss: 0.5052
Epoch 29/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7974 - loss: 0.4022 - val_accuracy: 0.7708 - val_loss: 0.4426
Epoch 30/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step - accuracy: 0.8172 - loss: 0.3950 - val_accuracy: 0.7232 - val_loss: 0.4952
Epoch 31/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - accuracy: 0.7668 - loss: 0.4242 - val_accuracy: 0.7708 - val_loss: 0.4624
Epoch 32/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step - accuracy: 0.7929 - loss: 0.4500 - val_accuracy: 0.7619 - val_loss: 0.4525
Epoch 33/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step - accuracy: 0.8115 - loss: 0.3933 - val_accuracy: 0.7500 - val_loss: 0.4510
Epoch 34/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 777us/step - accuracy: 0.8134 - loss: 0.3674 - val_accuracy: 0.7113 - val_loss: 0.5165
Epoch 35/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.8292 - loss: 0.3757 - val_accuracy: 0.7500 - val_loss: 0.4638
Epoch 36/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step - accuracy: 0.7897 - loss: 0.4245 - val_accuracy: 0.7857 - val_loss: 0.4377
Epoch 37/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.8189 - loss: 0.3790 - val_accuracy: 0.7857 - val_loss: 0.4405
Epoch 38/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 743us/step - accuracy: 0.8303 - loss: 0.3519 - val_accuracy: 0.7679 - val_loss: 0.4547
Epoch 39/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.8295 - loss: 0.3596 - val_accuracy: 0.7857 - val_loss: 0.4101
Epoch 40/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.8118 - loss: 0.3602 - val_accuracy: 0.7768 - val_loss: 0.4219
Epoch 41/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.8658 - loss: 0.3313 - val_accuracy: 0.7530 - val_loss: 0.4751
Epoch 42/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 761us/step - accuracy: 0.8573 - loss: 0.3272 - val_accuracy: 0.7798 - val_loss: 0.4112
Epoch 43/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - accuracy: 0.8139 - loss: 0.3871 - val_accuracy: 0.7827 - val_loss: 0.4283
Epoch 44/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.8218 - loss: 0.3743 - val_accuracy: 0.7619 - val_loss: 0.4667
Epoch 45/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 755us/step - accuracy: 0.7905 - loss: 0.4046 - val_accuracy: 0.7917 - val_loss: 0.4238
Epoch 46/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.8678 - loss: 0.3097 - val_accuracy: 0.8095 - val_loss: 0.3879
Epoch 47/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step - accuracy: 0.8166 - loss: 0.3542 - val_accuracy: 0.7887 - val_loss: 0.4175
Epoch 48/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - accuracy: 0.8419 - loss: 0.3375 - val_accuracy: 0.7887 - val_loss: 0.4003
Epoch 49/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 781us/step - accuracy: 0.8478 - loss: 0.3214 - val_accuracy: 0.7946 - val_loss: 0.3950
Epoch 50/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - accuracy: 0.8299 - loss: 0.3271 - val_accuracy: 0.7738 - val_loss: 0.4675
Epoch 51/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8299 - loss: 0.3640 - val_accuracy: 0.7738 - val_loss: 0.4146
Epoch 52/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - accuracy: 0.8568 - loss: 0.3088 - val_accuracy: 0.7827 - val_loss: 0.3843
Epoch 53/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 781us/step - accuracy: 0.8634 - loss: 0.3016 - val_accuracy: 0.8125 - val_loss: 0.3764
Epoch 54/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.8369 - loss: 0.3377 - val_accuracy: 0.7917 - val_loss: 0.3912
Epoch 55/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.8466 - loss: 0.3401 - val_accuracy: 0.7917 - val_loss: 0.3950
Epoch 56/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.8567 - loss: 0.3055 - val_accuracy: 0.7946 - val_loss: 0.4006
Epoch 57/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.8606 - loss: 0.3032 - val_accuracy: 0.8006 - val_loss: 0.3843
Epoch 58/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.8259 - loss: 0.3756 - val_accuracy: 0.8095 - val_loss: 0.3928
Epoch 59/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step - accuracy: 0.8535 - loss: 0.2990 - val_accuracy: 0.7857 - val_loss: 0.3929
Epoch 60/60
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 776us/step - accuracy: 0.8374 - loss: 0.3038 - val_accuracy: 0.8155 - val_loss: 0.3747
Test loss: 0.3746989071369171
Test accuracy: 0.8154761791229248

In [ ]:
# testing other options

In [ ]:
model = Sequential()
model.add(Input(shape=(9,)))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.1))

model.add(Dense(2, activation='softmax'))

model.summary()
optimizer = Adam(learning_rate=0.005)
model.compile(optimizer=optimizer,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

batch_size = 16  # Changed batch size
epochs = 60

from keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)  # Reduced patience
history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, y_test),
                    callbacks=[early_stop])

score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Model: "sequential_31"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_122 (Dense)               │ (None, 16)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_69 (Dropout)            │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_123 (Dense)               │ (None, 32)             │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_70 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_124 (Dense)               │ (None, 2)              │            66 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 770 (3.01 KB)

 Trainable params: 770 (3.01 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6566 - loss: 0.6645 - val_accuracy: 0.6518 - val_loss: 0.6375
Epoch 2/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6585 - loss: 0.6280 - val_accuracy: 0.6518 - val_loss: 0.6201
Epoch 3/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6635 - loss: 0.6234 - val_accuracy: 0.6577 - val_loss: 0.6120
Epoch 4/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6486 - loss: 0.6229 - val_accuracy: 0.6518 - val_loss: 0.6084
Epoch 5/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6791 - loss: 0.5968 - val_accuracy: 0.6518 - val_loss: 0.5969
Epoch 6/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6892 - loss: 0.5809 - val_accuracy: 0.6458 - val_loss: 0.5807
Epoch 7/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6354 - loss: 0.5834 - val_accuracy: 0.6518 - val_loss: 0.5659
Epoch 8/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6791 - loss: 0.5508 - val_accuracy: 0.6726 - val_loss: 0.5448
Epoch 9/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7057 - loss: 0.5437 - val_accuracy: 0.6786 - val_loss: 0.5518
Epoch 10/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7275 - loss: 0.5261 - val_accuracy: 0.7321 - val_loss: 0.5319
Epoch 11/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6796 - loss: 0.5314 - val_accuracy: 0.7202 - val_loss: 0.5193
Epoch 12/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7688 - loss: 0.4967 - val_accuracy: 0.7351 - val_loss: 0.4939
Epoch 13/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7666 - loss: 0.4746 - val_accuracy: 0.7411 - val_loss: 0.4994
Epoch 14/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7464 - loss: 0.4803 - val_accuracy: 0.7321 - val_loss: 0.4910
Epoch 15/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.7353 - loss: 0.4833 - val_accuracy: 0.7470 - val_loss: 0.4907
Epoch 16/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7566 - loss: 0.4691 - val_accuracy: 0.7440 - val_loss: 0.4780
Epoch 17/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7707 - loss: 0.4560 - val_accuracy: 0.7411 - val_loss: 0.4908
Epoch 18/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.7349 - loss: 0.4699 - val_accuracy: 0.7411 - val_loss: 0.4915
Epoch 19/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.7735 - loss: 0.4583 - val_accuracy: 0.7411 - val_loss: 0.4692
Epoch 20/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 786us/step - accuracy: 0.7584 - loss: 0.4655 - val_accuracy: 0.7500 - val_loss: 0.4825
Epoch 21/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7967 - loss: 0.4517 - val_accuracy: 0.7589 - val_loss: 0.4713
Epoch 22/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.7742 - loss: 0.4546 - val_accuracy: 0.7321 - val_loss: 0.4760
Epoch 23/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - accuracy: 0.8046 - loss: 0.4350 - val_accuracy: 0.7351 - val_loss: 0.4816
Epoch 24/60
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7543 - loss: 0.4545 - val_accuracy: 0.7292 - val_loss: 0.5035
Test loss: 0.4691718518733978
Test accuracy: 0.7410714030265808