# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [54]:
# Iporting libraries
import pandas as pd

In [55]:
# Reading the file and converting it to data frame
df = pd.read_csv('tic-tac-toe.csv')
print(df.shape) # Shape of the data frame
df.head() # Head

(958, 10)

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [56]:
# does it has empty rows?
df.isna().sum()

TL       0
TM       0
TR       0
ML       0
MM       0
MR       0
BL       0
BM       0
BR       0
class    0
dtype: int64

In [57]:
# does it has duplicated rows?
df.duplicated().sum()

np.int64(0)

In [58]:
# Separate the inputs and output
X = df.drop('class', axis=1)
y = df['class']
X.head()

  TL TM TR ML MM MR BL BM BR
0  x  x  x  x  o  o  x  o  o
1  x  x  x  x  o  o  o  x  o
2  x  x  x  x  o  o  o  o  x
3  x  x  x  x  o  o  o  b  b
4  x  x  x  x  o  o  b  o  b

In [59]:
y.value_counts()

class
True     626
False    332
Name: count, dtype: int64

In [ ]:
#One-hot encoding for X, maping y
X_hot = pd.get_dummies(X)
y_hot = y.map({True:1, False:0})

In [61]:
X_hot.head()

,TL_b,TL_o,TL_x,TM_b,TM_o,TM_x,TR_b,TR_o,TR_x,ML_b,...,MR_x,BL_b,BL_o,BL_x,BM_b,BM_o,BM_x,BR_b,BR_o,BR_x
0,False,False,True,False,False,True,False,False,True,False,...,False,False,False,True,False,True,False,False,True,False
1,False,False,True,False,False,True,False,False,True,False,...,False,False,True,False,False,False,True,False,True,False
2,False,False,True,False,False,True,False,False,True,False,...,False,False,True,False,False,True,False,False,False,True
3,False,False,True,False,False,True,False,False,True,False,...,False,False,True,False,True,False,False,True,False,False
4,False,False,True,False,False,True,False,False,True,False,...,False,True,False,False,False,True,False,True,False,False

In [62]:
# Checking the new sice
print(X_hot.shape, y_hot.shape)

(958, 27) (958,)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [63]:
# Split training and test data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_hot, y_hot, test_size=0.2, random_state=42)

X_train.shape

(766, 27)

In [ ]:
# Create Sequential model
from keras.models import Sequential
from keras.layers import Dense, Dropout, Input

model = Sequential()
model.add(Input(shape=(27,))) # Since we have 27 columns
model.add(Dense(12, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(24, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(2, activation='softmax'))

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 12)             │           336 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 12)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 24)             │           312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 24)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │            50 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 698 (2.73 KB)

 Trainable params: 698 (2.73 KB)

 Non-trainable params: 0 (0.00 B)

In [65]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])

In [67]:
batch_size = 64
epochs = 20

history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, y_test))

Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.6057 - loss: 0.6779 - val_accuracy: 0.6562 - val_loss: 0.6443
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6279 - loss: 0.6655 - val_accuracy: 0.6458 - val_loss: 0.6332
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6488 - loss: 0.6545 - val_accuracy: 0.6354 - val_loss: 0.6260
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6593 - loss: 0.6373 - val_accuracy: 0.6510 - val_loss: 0.6176
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6593 - loss: 0.6295 - val_accuracy: 0.6510 - val_loss: 0.6104
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6436 - loss: 0.6322 - val_accuracy: 0.6562 - val_loss: 0.6021
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6789 - loss: 0.6270 - val_accuracy: 0.6719 - val_loss: 0.5944
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6684 - loss: 0.6123 - val_accuracy: 0.6719 - val_loss: 0.5873
Epoch 9/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6815 - loss: 0.6059 - val_accuracy: 0.6927 - val_loss: 0.5792
Epoch 10/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6854 - loss: 0.6022 - val_accuracy: 0.7031 - val_loss: 0.5722
Epoch 11/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7037 - loss: 0.5886 - val_accuracy: 0.7083 - val_loss: 0.5651
Epoch 12/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6997 - loss: 0.5805 - val_accuracy: 0.7240 - val_loss: 0.5583
Epoch 13/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6997 - loss: 0.5870 - val_accuracy: 0.7344 - val_loss: 0.5514
Epoch 14/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7141 - loss: 0.5655 - val_accuracy: 0.7344 - val_loss: 0.5455
Epoch 15/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7050 - loss: 0.5648 - val_accuracy: 0.7396 - val_loss: 0.5392
Epoch 16/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7272 - loss: 0.5565 - val_accuracy: 0.7396 - val_loss: 0.5327
Epoch 17/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7154 - loss: 0.5543 - val_accuracy: 0.7344 - val_loss: 0.5279
Epoch 18/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7206 - loss: 0.5487 - val_accuracy: 0.7344 - val_loss: 0.5235
Epoch 19/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7154 - loss: 0.5364 - val_accuracy: 0.7448 - val_loss: 0.5173
Epoch 20/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7637 - loss: 0.5168 - val_accuracy: 0.7396 - val_loss: 0.5123

In [68]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.5122570395469666
Test accuracy: 0.7395833134651184

In [70]:
model.save('tic-tac-toe.keras')

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [72]:
import numpy as np
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [76]:
print(y_pred[:10])

[1 1 1 1 0 1 1 0 1 1]

In [77]:
results = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

print(results.head(10))

   Actual  Predicted
0       0          1
1       1          1
2       1          1
3       0          1
4       0          0
5       1          1
6       1          1
7       1          0
8       1          1
9       0          1

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [78]:
model_imp = Sequential()
model_imp.add(Input(shape=(27,)))

# Layer 1
model_imp.add(Dense(128, activation='relu'))
# Layer 2 (New/Extra)
model_imp.add(Dense(64, activation='relu'))
# Layer 3
model_imp.add(Dense(32, activation='relu'))

model_imp.add(Dense(2, activation='softmax'))

In [79]:
from tensorflow.keras.optimizers import Adam
custom_adam = Adam(learning_rate=0.0005)

model_imp.compile(optimizer=custom_adam,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [80]:
batch_size = 64
epochs = 20

history = model_imp.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, y_test))

Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6554 - loss: 0.6294 - val_accuracy: 0.6510 - val_loss: 0.6114
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6710 - loss: 0.5907 - val_accuracy: 0.6979 - val_loss: 0.5810
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7454 - loss: 0.5555 - val_accuracy: 0.7240 - val_loss: 0.5570
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7637 - loss: 0.5245 - val_accuracy: 0.7500 - val_loss: 0.5322
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7768 - loss: 0.4950 - val_accuracy: 0.7500 - val_loss: 0.5098
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7846 - loss: 0.4675 - val_accuracy: 0.7812 - val_loss: 0.4862
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7977 - loss: 0.4407 - val_accuracy: 0.7812 - val_loss: 0.4639
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8172 - loss: 0.4107 - val_accuracy: 0.7865 - val_loss: 0.4385
Epoch 9/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8407 - loss: 0.3789 - val_accuracy: 0.8125 - val_loss: 0.4063
Epoch 10/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8603 - loss: 0.3422 - val_accuracy: 0.8542 - val_loss: 0.3728
Epoch 11/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9060 - loss: 0.3038 - val_accuracy: 0.8698 - val_loss: 0.3377
Epoch 12/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9230 - loss: 0.2660 - val_accuracy: 0.8854 - val_loss: 0.3038
Epoch 13/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9452 - loss: 0.2258 - val_accuracy: 0.9219 - val_loss: 0.2625
Epoch 14/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9674 - loss: 0.1868 - val_accuracy: 0.9479 - val_loss: 0.2310
Epoch 15/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9713 - loss: 0.1622 - val_accuracy: 0.9219 - val_loss: 0.2210
Epoch 16/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9778 - loss: 0.1334 - val_accuracy: 0.9219 - val_loss: 0.2052
Epoch 17/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9804 - loss: 0.1164 - val_accuracy: 0.9688 - val_loss: 0.1662
Epoch 18/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9843 - loss: 0.0949 - val_accuracy: 0.9740 - val_loss: 0.1447
Epoch 19/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9883 - loss: 0.0776 - val_accuracy: 0.9688 - val_loss: 0.1403
Epoch 20/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9909 - loss: 0.0658 - val_accuracy: 0.9688 - val_loss: 0.1286

In [81]:
score = model_imp.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.128593310713768
Test accuracy: 0.96875

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# I only modified what you told me at the same time: layers, Adam optimazer and amount of epochs