# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

## 1.

In [3]:
import pandas as pd

tic_tac_toe_data = pd.read_csv("tic-tac-toe.csv")

tic_tac_toe_data.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

## 2.

In [4]:
tic_tac_toe_data.shape

(958, 10)

In [5]:
tic_tac_toe_data.describe()

         TL   TM   TR   ML   MM   MR   BL   BM   BR class
count   958  958  958  958  958  958  958  958  958   958
unique    3    3    3    3    3    3    3    3    3     2
top       x    x    x    x    x    x    x    x    x  True
freq    418  378  418  378  458  378  418  378  418   626

In [6]:
tic_tac_toe_data.isnull().sum()

TL       0
TM       0
TR       0
ML       0
MM       0
MR       0
BL       0
BM       0
BR       0
class    0
dtype: int64

In [7]:
tic_tac_toe_data.info()
print(tic_tac_toe_data.dtypes)

<class 'pandas.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    str
 1   TM      958 non-null    str
 2   TR      958 non-null    str
 3   ML      958 non-null    str
 4   MM      958 non-null    str
 5   MR      958 non-null    str
 6   BL      958 non-null    str
 7   BM      958 non-null    str
 8   BR      958 non-null    str
 9   class   958 non-null    bool
dtypes: bool(1), str(9)
memory usage: 68.4 KB
TL        str
TM        str
TR        str
ML        str
MM        str
MR        str
BL        str
BM        str
BR        str
class    bool
dtype: object

## 3.

In [8]:
tic_tac_toe_data = tic_tac_toe_data.replace({
    'x': 1,
    'o': -1,
    'b': 0,
    'positive': 1,
    'negative': 0
})

In [9]:
tic_tac_toe_data.info()
print(tic_tac_toe_data.dtypes)

<class 'pandas.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB
TL       object
TM       object
TR       object
ML       object
MM       object
MR       object
BL       object
BM       object
BR       object
class      bool
dtype: object

In [10]:
tic_tac_toe_data.head()

  TL TM TR ML  MM  MR  BL  BM  BR  class
0  1  1  1  1  -1  -1   1  -1  -1   True
1  1  1  1  1  -1  -1  -1   1  -1   True
2  1  1  1  1  -1  -1  -1  -1   1   True
3  1  1  1  1  -1  -1  -1   0   0   True
4  1  1  1  1  -1  -1   0  -1   0   True

## 4.

In [11]:
X = tic_tac_toe_data.drop('class', axis=1)

y = tic_tac_toe_data['class']

## 5.

In [12]:
X_norm = (X - X.mean()) / X.std()

X_norm.head()

,TL,TM,TR,ML,MM,MR,BL,BM,BR
0,1.034629,1.106252,1.034629,1.106252,-1.241346,-1.222956,1.034629,-1.222956,-1.230913
1,1.034629,1.106252,1.034629,1.106252,-1.241346,-1.222956,-1.230913,1.106252,-1.230913
2,1.034629,1.106252,1.034629,1.106252,-1.241346,-1.222956,-1.230913,-1.222956,1.034629
3,1.034629,1.106252,1.034629,1.106252,-1.241346,-1.222956,-1.230913,-0.058352,-0.098142
4,1.034629,1.106252,1.034629,1.106252,-1.241346,-1.222956,-0.098142,-1.222956,-0.098142

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

## 1.

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_norm,
    y,
    test_size=0.3,
    random_state=42
)

In [27]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(670, 9)
(288, 9)
(670,)
(288,)

In [14]:
import sys
print(sys.executable)

c:\Users\d_fon\ironhack-env\Scripts\python.exe

In [15]:
import sys
!{sys.executable} -m pip install tensorflow

Requirement already satisfied: tensorflow in c:\Users\d_fon\ironhack-env\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (7.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (84.0.0)
Requirement already satisfied: six>=1.12.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (1.84.0)
Requirement already satisfied: keras>=3.12.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (2.5.3)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in c:\Users\d_fon\ironhack-env\Lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\Users\d_fon\ironhack-env\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\Users\d_fon\ironhack-env\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

## 2.

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

In [17]:
!{sys.executable} -m pip install tensorflow

Requirement already satisfied: tensorflow in c:\Users\d_fon\ironhack-env\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (7.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (84.0.0)
Requirement already satisfied: six>=1.12.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (1.84.0)
Requirement already satisfied: keras>=3.12.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (2.5.3)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in c:\Users\d_fon\ironhack-env\Lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\Users\d_fon\ironhack-env\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\Users\d_fon\ironhack-env\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\d_fon\ironhack-env\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [18]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "tensorflow"
])

0

In [19]:
import tensorflow as tf

print(tf.__version__)

2.21.0

## 3.

In [20]:
# 3. Add layers
model.add(Dense(32, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(16, activation='relu'))
model.add(Dense(2, activation='softmax'))

c:\Users\d_fon\ironhack-env\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

## 4.

In [21]:
# 4. Compile
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

## 5.

In [24]:
X_train_np = X_train.to_numpy(dtype="float32")
X_test_np = X_test.to_numpy(dtype="float32")

y_train_np = y_train.to_numpy(dtype="int32")
y_test_np = y_test.to_numpy(dtype="int32")

In [25]:
history = model.fit(
    X_train_np,
    y_train_np,
    epochs=50
)

Epoch 1/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6373 - loss: 0.6527
Epoch 2/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6448 - loss: 0.6073
Epoch 3/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6821 - loss: 0.5779
Epoch 4/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7119 - loss: 0.5559
Epoch 5/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.5366
Epoch 6/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7448 - loss: 0.5175
Epoch 7/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7701 - loss: 0.5000
Epoch 8/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7791 - loss: 0.4815
Epoch 9/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7940 - loss: 0.4642
Epoch 10/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8104 - loss: 0.4469
Epoch 11/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8239 - loss: 0.4297
Epoch 12/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8388 - loss: 0.4129
Epoch 13/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8373 - loss: 0.3958
Epoch 14/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8463 - loss: 0.3790
Epoch 15/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8657 - loss: 0.3605
Epoch 16/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8672 - loss: 0.3430
Epoch 17/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8791 - loss: 0.3253
Epoch 18/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8896 - loss: 0.3079
Epoch 19/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8940 - loss: 0.2895
Epoch 20/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9104 - loss: 0.2740
Epoch 21/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9313 - loss: 0.2578
Epoch 22/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9299 - loss: 0.2399
Epoch 23/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9418 - loss: 0.2235
Epoch 24/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9522 - loss: 0.2075
Epoch 25/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9567 - loss: 0.1923
Epoch 26/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9567 - loss: 0.1778
Epoch 27/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9672 - loss: 0.1632
Epoch 28/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9716 - loss: 0.1497
Epoch 29/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9776 - loss: 0.1370
Epoch 30/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9821 - loss: 0.1246
Epoch 31/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9910 - loss: 0.1141
Epoch 32/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9910 - loss: 0.1043
Epoch 33/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9925 - loss: 0.0942
Epoch 34/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9910 - loss: 0.0860
Epoch 35/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9925 - loss: 0.0781
Epoch 36/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9940 - loss: 0.0714
Epoch 37/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9955 - loss: 0.0644
Epoch 38/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9955 - loss: 0.0583
Epoch 39/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9955 - loss: 0.0530
Epoch 40/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9955 - loss: 0.0480
Epoch 41/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9955 - loss: 0.0444
Epoch 42/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9955 - loss: 0.0404
Epoch 43/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9970 - loss: 0.0368
Epoch 44/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9970 - loss: 0.0340
Epoch 45/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9970 - loss: 0.0314
Epoch 46/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9970 - loss: 0.0289
Epoch 47/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9970 - loss: 0.0271
Epoch 48/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9985 - loss: 0.0249
Epoch 49/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9985 - loss: 0.0231
Epoch 50/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9985 - loss: 0.0216

## 6.

In [26]:
test_loss, test_accuracy = model.evaluate(
    X_test_np,
    y_test_np
)

print(test_loss)
print(test_accuracy)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9896 - loss: 0.0597
0.059702318161726
0.9895833134651184

## 7.

In [29]:
# 7. Save
model.save("tic-tac-toe.keras")

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [31]:
from tensorflow.keras.models import load_model
import numpy as np

loaded_model = load_model("tic-tac-toe.keras")

sample = X_test.sample(5, random_state=42)

sample_np = sample.to_numpy(dtype="float32")

predictions = loaded_model.predict(sample_np)

predicted_classes = np.argmax(predictions, axis=1)

actual_classes = y_test.loc[sample.index].astype(int)

print("Predicted:", predicted_classes)
print("Actual:   ", actual_classes.values)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 295ms/step
Predicted: [0 1 0 0 1]
Actual:    [0 1 0 0 1]

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [33]:
test_loss, test_accuracy = model.evaluate(
    X_test_np,
    y_test_np
)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9896 - loss: 0.0597
Test Loss: 0.059702318161726
Test Accuracy: 0.9895833134651184

In [34]:
model = Sequential()

model.add(Dense(32, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))

model.add(Dense(2, activation='softmax'))

c:\Users\d_fon\ironhack-env\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [35]:
optimizer = tf.keras.optimizers.Adam(
    learning_rate=0.001
)

In [36]:
model.compile(
    optimizer=optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [38]:
history = model.fit(
    X_train_np,
    y_train_np,
    epochs=100,
    validation_split=0.2
)

Epoch 1/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6343 - loss: 0.7371 - val_accuracy: 0.6940 - val_loss: 0.6278
Epoch 2/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6362 - loss: 0.6697 - val_accuracy: 0.6940 - val_loss: 0.6202
Epoch 3/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6362 - loss: 0.6347 - val_accuracy: 0.6866 - val_loss: 0.6054
Epoch 4/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6343 - loss: 0.6089 - val_accuracy: 0.6940 - val_loss: 0.5912
Epoch 5/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6437 - loss: 0.5852 - val_accuracy: 0.6866 - val_loss: 0.5781
Epoch 6/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6660 - loss: 0.5635 - val_accuracy: 0.6940 - val_loss: 0.5674
Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6866 - loss: 0.5435 - val_accuracy: 0.7015 - val_loss: 0.5575
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7201 - loss: 0.5254 - val_accuracy: 0.7313 - val_loss: 0.5455
Epoch 9/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7313 - loss: 0.5096 - val_accuracy: 0.7239 - val_loss: 0.5358
Epoch 10/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7537 - loss: 0.4945 - val_accuracy: 0.7537 - val_loss: 0.5251
Epoch 11/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7817 - loss: 0.4783 - val_accuracy: 0.7537 - val_loss: 0.5118
Epoch 12/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7836 - loss: 0.4650 - val_accuracy: 0.7463 - val_loss: 0.5007
Epoch 13/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8022 - loss: 0.4491 - val_accuracy: 0.7612 - val_loss: 0.4848
Epoch 14/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8190 - loss: 0.4335 - val_accuracy: 0.7985 - val_loss: 0.4779
Epoch 15/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8358 - loss: 0.4190 - val_accuracy: 0.8060 - val_loss: 0.4637
Epoch 16/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8563 - loss: 0.4036 - val_accuracy: 0.8209 - val_loss: 0.4492
Epoch 17/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8638 - loss: 0.3880 - val_accuracy: 0.8209 - val_loss: 0.4387
Epoch 18/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8881 - loss: 0.3749 - val_accuracy: 0.8507 - val_loss: 0.4242
Epoch 19/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8918 - loss: 0.3534 - val_accuracy: 0.8507 - val_loss: 0.4056
Epoch 20/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9216 - loss: 0.3297 - val_accuracy: 0.8582 - val_loss: 0.3946
Epoch 21/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9328 - loss: 0.3080 - val_accuracy: 0.8657 - val_loss: 0.3809
Epoch 22/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9254 - loss: 0.2843 - val_accuracy: 0.8657 - val_loss: 0.3619
Epoch 23/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9515 - loss: 0.2597 - val_accuracy: 0.8881 - val_loss: 0.3490
Epoch 24/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9496 - loss: 0.2356 - val_accuracy: 0.8955 - val_loss: 0.3283
Epoch 25/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9683 - loss: 0.2138 - val_accuracy: 0.8955 - val_loss: 0.3062
Epoch 26/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9701 - loss: 0.1908 - val_accuracy: 0.9104 - val_loss: 0.2922
Epoch 27/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9795 - loss: 0.1711 - val_accuracy: 0.9328 - val_loss: 0.2740
Epoch 28/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9795 - loss: 0.1531 - val_accuracy: 0.9328 - val_loss: 0.2552
Epoch 29/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9869 - loss: 0.1350 - val_accuracy: 0.9328 - val_loss: 0.2409
Epoch 30/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9888 - loss: 0.1182 - val_accuracy: 0.9328 - val_loss: 0.2283
Epoch 31/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9888 - loss: 0.1053 - val_accuracy: 0.9403 - val_loss: 0.2146
Epoch 32/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9888 - loss: 0.0931 - val_accuracy: 0.9552 - val_loss: 0.2019
Epoch 33/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9907 - loss: 0.0816 - val_accuracy: 0.9552 - val_loss: 0.1931
Epoch 34/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9907 - loss: 0.0721 - val_accuracy: 0.9552 - val_loss: 0.1765
Epoch 35/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9963 - loss: 0.0635 - val_accuracy: 0.9552 - val_loss: 0.1662
Epoch 36/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9963 - loss: 0.0558 - val_accuracy: 0.9552 - val_loss: 0.1593
Epoch 37/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9981 - loss: 0.0497 - val_accuracy: 0.9552 - val_loss: 0.1554
Epoch 38/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9981 - loss: 0.0435 - val_accuracy: 0.9552 - val_loss: 0.1418
Epoch 39/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9981 - loss: 0.0386 - val_accuracy: 0.9552 - val_loss: 0.1362
Epoch 40/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9981 - loss: 0.0346 - val_accuracy: 0.9552 - val_loss: 0.1284
Epoch 41/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0305 - val_accuracy: 0.9552 - val_loss: 0.1228
Epoch 42/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0273 - val_accuracy: 0.9552 - val_loss: 0.1187
Epoch 43/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9981 - loss: 0.0247 - val_accuracy: 0.9552 - val_loss: 0.1109
Epoch 44/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0223 - val_accuracy: 0.9552 - val_loss: 0.1078
Epoch 45/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0196 - val_accuracy: 0.9552 - val_loss: 0.1034
Epoch 46/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0177 - val_accuracy: 0.9552 - val_loss: 0.1022
Epoch 47/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0158 - val_accuracy: 0.9552 - val_loss: 0.0960
Epoch 48/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0144 - val_accuracy: 0.9552 - val_loss: 0.0924
Epoch 49/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0130 - val_accuracy: 0.9552 - val_loss: 0.0911
Epoch 50/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0118 - val_accuracy: 0.9552 - val_loss: 0.0884
Epoch 51/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0107 - val_accuracy: 0.9552 - val_loss: 0.0848
Epoch 52/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0098 - val_accuracy: 0.9552 - val_loss: 0.0845
Epoch 53/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0089 - val_accuracy: 0.9552 - val_loss: 0.0828
Epoch 54/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0082 - val_accuracy: 0.9552 - val_loss: 0.0806
Epoch 55/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0076 - val_accuracy: 0.9552 - val_loss: 0.0789
Epoch 56/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0070 - val_accuracy: 0.9552 - val_loss: 0.0782
Epoch 57/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0064 - val_accuracy: 0.9627 - val_loss: 0.0747
Epoch 58/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0060 - val_accuracy: 0.9627 - val_loss: 0.0735
Epoch 59/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.9552 - val_loss: 0.0728
Epoch 60/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0052 - val_accuracy: 0.9627 - val_loss: 0.0713
Epoch 61/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0048 - val_accuracy: 0.9627 - val_loss: 0.0701
Epoch 62/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.9701 - val_loss: 0.0681
Epoch 63/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0042 - val_accuracy: 0.9701 - val_loss: 0.0670
Epoch 64/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0040 - val_accuracy: 0.9701 - val_loss: 0.0671
Epoch 65/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0038 - val_accuracy: 0.9701 - val_loss: 0.0658
Epoch 66/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.9701 - val_loss: 0.0646
Epoch 67/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.9701 - val_loss: 0.0646
Epoch 68/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.9701 - val_loss: 0.0637
Epoch 69/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.9701 - val_loss: 0.0626
Epoch 70/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.9701 - val_loss: 0.0625
Epoch 71/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9701 - val_loss: 0.0616
Epoch 72/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.9701 - val_loss: 0.0612
Epoch 73/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.9701 - val_loss: 0.0604
Epoch 74/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.9776 - val_loss: 0.0593
Epoch 75/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9701 - val_loss: 0.0589
Epoch 76/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.9776 - val_loss: 0.0586
Epoch 77/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.9776 - val_loss: 0.0580
Epoch 78/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.9776 - val_loss: 0.0582
Epoch 79/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.9776 - val_loss: 0.0577
Epoch 80/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.9776 - val_loss: 0.0569
Epoch 81/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.9776 - val_loss: 0.0570
Epoch 82/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.9776 - val_loss: 0.0567
Epoch 83/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.9776 - val_loss: 0.0564
Epoch 84/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.9776 - val_loss: 0.0560
Epoch 85/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.9776 - val_loss: 0.0560
Epoch 86/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9776 - val_loss: 0.0555
Epoch 87/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9776 - val_loss: 0.0553
Epoch 88/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.9776 - val_loss: 0.0550
Epoch 89/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.9776 - val_loss: 0.0545
Epoch 90/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9776 - val_loss: 0.0545
Epoch 91/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9776 - val_loss: 0.0539
Epoch 92/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9776 - val_loss: 0.0537
Epoch 93/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.9776 - val_loss: 0.0527
Epoch 94/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.8410e-04 - val_accuracy: 0.9776 - val_loss: 0.0532
Epoch 95/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.4903e-04 - val_accuracy: 0.9776 - val_loss: 0.0526
Epoch 96/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.1758e-04 - val_accuracy: 0.9776 - val_loss: 0.0524
Epoch 97/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.8918e-04 - val_accuracy: 0.9776 - val_loss: 0.0520
Epoch 98/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.5864e-04 - val_accuracy: 0.9776 - val_loss: 0.0521
Epoch 99/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.2988e-04 - val_accuracy: 0.9776 - val_loss: 0.0517
Epoch 100/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.0318e-04 - val_accuracy: 0.9776 - val_loss: 0.0508

In [40]:
test_loss, test_accuracy = model.evaluate(
    X_test_np,
    y_test_np.astype(int)
)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9826 - loss: 0.0619
Test Loss: 0.06185368821024895
Test Accuracy: 0.9826388955116272

**Which approach(es) did you find helpful to improve your model performance?**

- Increasing the number of epochs and adding more complexity did not improve the model. The original model was already sufficient for this problem.