# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.utils import to_categorical

In [2]:
# your code here
df = pd.read_csv("tic-tac-toe.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

In [4]:
df.describe()

         TL   TM   TR   ML   MM   MR   BL   BM   BR class
count   958  958  958  958  958  958  958  958  958   958
unique    3    3    3    3    3    3    3    3    3     2
top       x    x    x    x    x    x    x    x    x  True
freq    418  378  418  378  458  378  418  378  418   626

In [5]:
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df = pd.get_dummies(df)

In [8]:
df

,class,TL_b,TL_o,TL_x,TM_b,TM_o,TM_x,TR_b,TR_o,TR_x,...,MR_x,BL_b,BL_o,BL_x,BM_b,BM_o,BM_x,BR_b,BR_o,BR_x
0,True,False,False,True,False,False,True,False,False,True,...,False,False,False,True,False,True,False,False,True,False
1,True,False,False,True,False,False,True,False,False,True,...,False,False,True,False,False,False,True,False,True,False
2,True,False,False,True,False,False,True,False,False,True,...,False,False,True,False,False,True,False,False,False,True
3,True,False,False,True,False,False,True,False,False,True,...,False,False,True,False,True,False,False,True,False,False
4,True,False,False,True,False,False,True,False,False,True,...,False,True,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953,False,False,True,False,False,False,True,False,False,True,...,False,False,True,False,False,False,True,False,False,True
954,False,False,True,False,False,False,True,False,True,False,...,False,False,False,True,False,True,False,False,False,True
955,False,False,True,False,False,False,True,False,True,False,...,True,False,False,True,False,True,False,False,False,True
956,False,False,True,False,False,False,True,False,True,False,...,True,False,False,True,False,True,False,False,False,True
957,False,False,True,False,False,True,False,False,False,True,...,False,False,True,False,False,False,True,False,False,True

In [9]:
x = df.drop(columns="class")
y = df[["class"]]

In [10]:
y_cat = to_categorical(y, num_classes=2)

In [11]:
scaler = StandardScaler()

In [12]:
x_scaled = scaler.fit_transform(x)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
# your code here
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_cat, random_state=1)

In [15]:
from tensorflow.keras.models import Sequential

In [16]:
model = Sequential()

In [17]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import RMSprop

In [18]:
num_classes = 2

In [19]:
model1 = Sequential()
model1.add(Dense(16, activation='relu', input_shape=(27,)))
model1.add(Dense(16, activation='relu'))
model1.add(Dense(2, activation='softmax'))

model1.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
history = model1.fit(x_train, y_train, batch_size=16, epochs=25, validation_data=(x_test, y_test))

Epoch 1/25

c:\Programming\Ironhack\ai\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5641 - loss: 0.7020 - val_accuracy: 0.7083 - val_loss: 0.6247
Epoch 2/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6685 - loss: 0.6257 - val_accuracy: 0.7375 - val_loss: 0.5963
Epoch 3/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7089 - loss: 0.5908 - val_accuracy: 0.7500 - val_loss: 0.5709
Epoch 4/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7312 - loss: 0.5574 - val_accuracy: 0.7542 - val_loss: 0.5506
Epoch 5/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7493 - loss: 0.5300 - val_accuracy: 0.7542 - val_loss: 0.5290
Epoch 6/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7632 - loss: 0.5005 - val_accuracy: 0.7625 - val_loss: 0.5091
Epoch 7/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7744 - loss: 0.4782 - val_accuracy: 0.7625 - val_loss: 0.4924
Epoch 8/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7786 - loss: 0.4571 - val_accuracy: 0.7708 - val_loss: 0.4799
Epoch 9/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7953 - loss: 0.4351 - val_accuracy: 0.7625 - val_loss: 0.4699
Epoch 10/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8106 - loss: 0.4133 - val_accuracy: 0.7583 - val_loss: 0.4530
Epoch 11/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8259 - loss: 0.3908 - val_accuracy: 0.7667 - val_loss: 0.4359
Epoch 12/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8468 - loss: 0.3686 - val_accuracy: 0.7625 - val_loss: 0.4216
Epoch 13/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8482 - loss: 0.3467 - val_accuracy: 0.7917 - val_loss: 0.3982
Epoch 14/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8719 - loss: 0.3228 - val_accuracy: 0.8042 - val_loss: 0.3817
Epoch 15/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8858 - loss: 0.2993 - val_accuracy: 0.8167 - val_loss: 0.3603
Epoch 16/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8997 - loss: 0.2763 - val_accuracy: 0.8208 - val_loss: 0.3394
Epoch 17/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9095 - loss: 0.2536 - val_accuracy: 0.8500 - val_loss: 0.3187
Epoch 18/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9276 - loss: 0.2305 - val_accuracy: 0.8667 - val_loss: 0.3003
Epoch 19/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9373 - loss: 0.2097 - val_accuracy: 0.8750 - val_loss: 0.2812
Epoch 20/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9457 - loss: 0.1891 - val_accuracy: 0.9000 - val_loss: 0.2616
Epoch 21/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9457 - loss: 0.1698 - val_accuracy: 0.9042 - val_loss: 0.2452
Epoch 22/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9540 - loss: 0.1514 - val_accuracy: 0.9042 - val_loss: 0.2294
Epoch 23/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9610 - loss: 0.1362 - val_accuracy: 0.9167 - val_loss: 0.2155
Epoch 24/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9666 - loss: 0.1219 - val_accuracy: 0.9208 - val_loss: 0.2037
Epoch 25/25
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9735 - loss: 0.1088 - val_accuracy: 0.9208 - val_loss: 0.1904

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [20]:
import numpy as np

In [21]:
score = model1.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.19042867422103882
Test accuracy: 0.9208333492279053

In [23]:
# Pick 5 random rows
sample_idx = np.random.choice(len(x_test), 10, replace=False)
x_sample = x_test[sample_idx]
y_sample = y_test[sample_idx]

pred_probs = model1.predict(x_sample)
pred_classes = np.argmax(pred_probs, axis=1)
true_classes = np.argmax(y_sample, axis=1)

for i in range(len(x_sample)):
    print(f"Predicted: {pred_classes[i]}, True: {true_classes[i]}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
Predicted: 0, True: 0
Predicted: 0, True: 0
Predicted: 1, True: 1
Predicted: 0, True: 0
Predicted: 1, True: 1
Predicted: 1, True: 1
Predicted: 0, True: 0
Predicted: 1, True: 1
Predicted: 0, True: 0
Predicted: 1, True: 1

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [26]:
# Experiment 2: different learning rate
model2 = Sequential([
    Dense(16, activation='relu', input_shape=(27,)),
    Dense(16, activation='relu'),
    Dense(2, activation='softmax')
])
model2.compile(optimizer=tf.keras.optimizers.Adam(0.05), loss='categorical_crossentropy', metrics=['accuracy'])
history2 = model2.fit(x_train, y_train, epochs=30, validation_data=(x_test, y_test))

Epoch 1/30

c:\Programming\Ironhack\ai\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6365 - loss: 0.6433 - val_accuracy: 0.7125 - val_loss: 0.5151
Epoch 2/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7423 - loss: 0.4564 - val_accuracy: 0.8208 - val_loss: 0.3815
Epoch 3/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8538 - loss: 0.3175 - val_accuracy: 0.8333 - val_loss: 0.3300
Epoch 4/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9025 - loss: 0.2373 - val_accuracy: 0.8875 - val_loss: 0.2282
Epoch 5/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8969 - loss: 0.2295 - val_accuracy: 0.9167 - val_loss: 0.2087
Epoch 6/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9457 - loss: 0.1516 - val_accuracy: 0.9625 - val_loss: 0.1499
Epoch 7/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9554 - loss: 0.1368 - val_accuracy: 0.9333 - val_loss: 0.1812
Epoch 8/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9708 - loss: 0.0871 - val_accuracy: 0.9667 - val_loss: 0.0789
Epoch 9/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9735 - loss: 0.0688 - val_accuracy: 0.9667 - val_loss: 0.1014
Epoch 10/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9777 - loss: 0.0483 - val_accuracy: 0.9792 - val_loss: 0.0521
Epoch 11/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9847 - loss: 0.0391 - val_accuracy: 0.9750 - val_loss: 0.1031
Epoch 12/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9944 - loss: 0.0217 - val_accuracy: 0.9708 - val_loss: 0.0787
Epoch 13/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9944 - loss: 0.0223 - val_accuracy: 0.9500 - val_loss: 0.1932
Epoch 14/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9861 - loss: 0.0412 - val_accuracy: 0.9583 - val_loss: 0.1481
Epoch 15/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9721 - loss: 0.0946 - val_accuracy: 0.9500 - val_loss: 0.1136
Epoch 16/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9568 - loss: 0.1271 - val_accuracy: 0.9042 - val_loss: 0.2385
Epoch 17/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9666 - loss: 0.0749 - val_accuracy: 0.9583 - val_loss: 0.1676
Epoch 18/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9889 - loss: 0.0401 - val_accuracy: 0.9667 - val_loss: 0.1592
Epoch 19/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9861 - loss: 0.0420 - val_accuracy: 0.9833 - val_loss: 0.0656
Epoch 20/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9847 - loss: 0.0500 - val_accuracy: 0.9542 - val_loss: 0.1831
Epoch 21/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9666 - loss: 0.1398 - val_accuracy: 0.9000 - val_loss: 0.5527
Epoch 22/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9443 - loss: 0.1995 - val_accuracy: 0.9250 - val_loss: 0.3059
Epoch 23/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9666 - loss: 0.1015 - val_accuracy: 0.9458 - val_loss: 0.2464
Epoch 24/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9763 - loss: 0.0795 - val_accuracy: 0.9833 - val_loss: 0.0602
Epoch 25/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9861 - loss: 0.0482 - val_accuracy: 0.9708 - val_loss: 0.0916
Epoch 26/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9958 - loss: 0.0173 - val_accuracy: 0.9792 - val_loss: 0.0812
Epoch 27/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9986 - loss: 0.0118 - val_accuracy: 0.9792 - val_loss: 0.0614
Epoch 28/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9986 - loss: 0.0054 - val_accuracy: 0.9750 - val_loss: 0.0788
Epoch 29/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9986 - loss: 0.0057 - val_accuracy: 0.9750 - val_loss: 0.0981
Epoch 30/30
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.9750 - val_loss: 0.1112

In [27]:
score = model2.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

# Pick 5 random rows
sample_idx = np.random.choice(len(x_test), 10, replace=False)
x_sample = x_test[sample_idx]
y_sample = y_test[sample_idx]

pred_probs = model2.predict(x_sample)
pred_classes = np.argmax(pred_probs, axis=1)
true_classes = np.argmax(y_sample, axis=1)

for i in range(len(x_sample)):
    print(f"Predicted: {pred_classes[i]}, True: {true_classes[i]}")

Test loss: 0.11118751019239426
Test accuracy: 0.9750000238418579
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Predicted: 1, True: 1
Predicted: 1, True: 1
Predicted: 1, True: 1
Predicted: 1, True: 1
Predicted: 1, True: 1
Predicted: 1, True: 1
Predicted: 0, True: 0
Predicted: 0, True: 0
Predicted: 0, True: 0
Predicted: 0, True: 0